// UniMap — Dataset Università Europee (QS 2027)
// Triennali in inglese (eccetto Italia), ranking ≤ 500, no UK/USA
// Dati: tasse, affitto, vita, test ammissione, fit score per profilo Giovanni (ITIS Rossi, informatica/AI/robotica)

const UNIVERSITIES = [

  // ─── SVIZZERA ─────────────────────────────────────────────────────────────
  {
    id: "eth_zurich",
    nome: "ETH Zürich",
    citta: "Zurigo",
    paese: "Svizzera",
    bandiera: "🇨🇭",
    lat: 47.3769,
    lng: 8.5480,
    qs2027: 8,
    qs2026: 7,
    punteggio_qs: 100,
    // Costi
    tasse_annue_eu: "~730 CHF/semestre (~1.600 €/anno)",
    affitto_mensile: "900–1.400 CHF (~950–1.500 €) — Zurigo è carissima",
    costo_vita_totale: "~1.800–2.400 €/mese totali",
    budget_rating: 1, // 1=difficile, 5=agevole con 600-800€
    // Lingua e lauree
    lingua_triennale: "Tedesco (triennale). Magistrali in inglese.",
    lingua_triennale_flag: "⚠️ TEDESCO",
    lauree_cs: "B.Sc. Informatica (tedesco), Ingegneria Elettrica e IT, Matematica, Physics",
    altre_ingegnerie: "Meccanica, Civile, Materiali, Architettura, Chimica",
    // Ammissione
    requisiti_ammissione: "Test specifico ETH (esame di ammissione se non hai maturità svizzera). Media voti superiori molto alta (≥8/10). Matematica avanzata.",
    test_lingua: "Non richiesto per triennale tedesca. C1 per magistrali in inglese.",
    difficolta_ammissione: 5, // 1=facile, 5=molto selettivo
    // Vita
    qualita_vita: "Altissima. Zurigo è la città con la qualità della vita più alta al mondo, ma anche la più cara.",
    soddisfazione_studenti: "Eccezionale. Campus iconico, networking globale, connessioni con industria top (Google, Microsoft, SAP hanno uffici qui).",
    rapporto_studio_vita: "Molto intenso, poca vita sociale durante gli esami. Ma la città offre moltissimo nel tempo libero.",
    approccio_didattico: "Teorico-rigoroso con forte base matematica. Labs di ricerca avanzatissimi. Meno project-based della Aalborg, ma qualità della ricerca impareggiabile.",
    borse_sussidi: "Excellence Scholarships per studenti stranieri. Non ci sono sussidi statali automatici come in Danimarca.",
    // Fit Giovanni
    fit_score: 6,
    fit_note: "Eccellente per qualità ma triennale in tedesco e costi proibitivi rendono difficile l'accesso con 600-800€/mese.",
    punti_forza: ["Ranking #8 nel mondo", "Ricerca AI di punta", "Networking top globale"],
    punti_deboli: ["Triennale in tedesco", "Costosissima (1.800€+ /mese)", "Ammissione durissima"],
    url: "https://ethz.ch/en",
  },

  {
    id: "epfl",
    nome: "EPFL",
    citta: "Losanna",
    paese: "Svizzera",
    bandiera: "🇨🇭",
    lat: 46.5191,
    lng: 6.5668,
    qs2027: 22,
    qs2026: 23,
    punteggio_qs: 93.5,
    tasse_annue_eu: "~730 CHF/semestre (~1.600 €/anno)",
    affitto_mensile: "700–1.100 CHF (~750–1.200 €) — meno cara di Zurigo",
    costo_vita_totale: "~1.500–2.000 €/mese totali",
    budget_rating: 1,
    lingua_triennale: "Francese (triennale). Magistrali in inglese/francese.",
    lingua_triennale_flag: "⚠️ FRANCESE",
    lauree_cs: "B.Sc. Informatica (francese), Communication Systems, Microengineering",
    altre_ingegnerie: "Elettrica, Meccanica, Chimica, Fisica, Architettura",
    requisiti_ammissione: "Esame di ammissione EPFL per studenti con maturità straniera. Media voti alta.",
    test_lingua: "Francese per triennale. IELTS/TOEFL per magistrali inglesi.",
    difficolta_ammissione: 5,
    qualita_vita: "Splendida. Losanna sul Lago Lemano, clima mite, ottima mobilità.",
    soddisfazione_studenti: "Altissima. Ambiente internazionale, campus moderno e dinamico.",
    rapporto_studio_vita: "Molto intenso nei primi anni ('mise à niveau' rigorosa). Poi si equilibra.",
    approccio_didattico: "Teorico-matematico rigoroso. Labs di ricerca eccellenti. Ottimo per robotica e AI.",
    borse_sussidi: "Excellence Fellowship per studenti stranieri meritevoli.",
    fit_score: 5,
    fit_note: "Top per qualità ma triennale in francese e costi oltre budget.",
    punti_forza: ["Ranking #22 mondo", "Ottima robotica e AI", "Ambiente internazionale"],
    punti_deboli: ["Triennale in francese", "Costosissima", "Ammissione selettiva"],
    url: "https://www.epfl.ch/en",
  },

  // ─── GERMANIA ─────────────────────────────────────────────────────────────
  {
    id: "tum",
    nome: "Technical University of Munich (TUM)",
    citta: "Monaco di Baviera",
    paese: "Germania",
    bandiera: "🇩🇪",
    lat: 48.1497,
    lng: 11.5679,
    qs2027: 25,
    qs2026: 28,
    punteggio_qs: 91.8,
    tasse_annue_eu: "~144 €/anno (solo tasse amministrative, università gratuita)",
    affitto_mensile: "500–800 € (Monaco è la città più cara di Germania; liste d'attesa lunghe)",
    costo_vita_totale: "~900–1.300 €/mese",
    budget_rating: 2,
    lingua_triennale: "Inglese (Informatics BSc completamente in inglese!)",
    lingua_triennale_flag: "✅ INGLESE",
    lauree_cs: "B.Sc. Informatics (inglese), Electrical Engineering, Computer Engineering, Data Engineering",
    altre_ingegnerie: "Meccanica, Aerospaziale, Biomedica, Chimica, Civile, Robotica (magistrale)",
    requisiti_ammissione: "Media voti superiori alta. Test online di matematica/logica (aptitude test) per alcuni corsi. Lettera motivazione.",
    test_lingua: "IELTS 6.5+ o TOEFL 88+ per Informatics BSc in inglese.",
    difficolta_ammissione: 4,
    qualita_vita: "Ottima. Monaco è ricca di cultura, birra 🍺, natura (Alpi vicine). Molto cara ma sicura e organizzata.",
    soddisfazione_studenti: "Altissima. TUM è costantemente nella top 3 europea per ingegneria.",
    rapporto_studio_vita: "Intenso ma bilanciato. Gli studenti hanno vita sociale attiva. Festival (Oktoberfest!) e vita notturna vivace.",
    approccio_didattico: "Forte base teorica con laboratori pratici. Collaborazioni con BMW, Siemens, MAN, Airbus. Robot Lab disponibili.",
    borse_sussidi: "BAföG (sussidio statale tedesco ~850€/mese per chi ne ha diritto, ma solo per residenti UE). Nessun sussidio automatico per italiani.",
    fit_score: 9,
    fit_note: "Eccellente fit: triennale in inglese, quasi gratis, top 25 mondiale, laboratori AI e robotica di prima classe. Monaco è cara ma gestibile.",
    punti_forza: ["#25 mondo", "BSc Informatics in inglese", "Quasi gratis (144€/anno)", "Eccellente robotica/AI"],
    punti_deboli: ["Monaco cara (900-1300€/mese)", "Liste d'attesa alloggi", "Ammissione competitiva"],
    url: "https://www.tum.de/en/",
  },

  {
    id: "rwth",
    nome: "RWTH Aachen University",
    citta: "Aachen",
    paese: "Germania",
    bandiera: "🇩🇪",
    lat: 50.7753,
    lng: 6.0839,
    qs2027: 104,
    qs2026: 106,
    punteggio_qs: 57.3,
    tasse_annue_eu: "~270 €/anno (tasse amministrative)",
    affitto_mensile: "300–500 € (Aachen è molto economica!)",
    costo_vita_totale: "~600–900 €/mese",
    budget_rating: 4,
    lingua_triennale: "Tedesco (quasi tutti i BSc). Solo alcuni programmi doppi in inglese.",
    lingua_triennale_flag: "⚠️ TEDESCO (alcuni doppio)",
    lauree_cs: "B.Sc. Informatik (tedesco), B.Sc. Electrical Engineering and IT (tedesco), Computer Science + Mathematics",
    altre_ingegnerie: "Meccanica, Civile, Chimica, Mineraria, Aerospaziale",
    requisiti_ammissione: "Media voti buona. Test attitudinale matematico per alcuni corsi. Nessun esame di ammissione centralizzato.",
    test_lingua: "Non richiesto per corsi tedeschi. TestDaF o DSH per iscriversi.",
    difficolta_ammissione: 3,
    qualita_vita: "Molto buona. Aachen è una piccola città universitaria a misura di studente, confinante con Belgio e Olanda.",
    soddisfazione_studenti: "Alta. Università storica con forte tradizione ingegneristica.",
    rapporto_studio_vita: "Buono. La città ruota attorno all'università, molto vivace socialmente.",
    approccio_didattico: "Molto teorico-rigoroso alla tedesca. Eccellente per reti, embedded e ricerca hardware.",
    borse_sussidi: "DAAD per studenti internazionali. BAföG potenzialmente accessibile.",
    fit_score: 5,
    fit_note: "Ottima università ma corsi di informatica quasi tutti in tedesco. Valida se studi tedesco in parallelo.",
    punti_forza: ["#104 mondo", "Quasi gratis", "Aachen economica", "Ottima per embedded/EE"],
    punti_deboli: ["Principalmente in tedesco", "Servirebbe B1/B2 tedesco", "Più teorica che pratica"],
    url: "https://www.rwth-aachen.de/cms/root/Studium/~aaaa/Studieren-an-der-RWTH/",
  },

  {
    id: "kit",
    nome: "KIT – Karlsruhe Institute of Technology",
    citta: "Karlsruhe",
    paese: "Germania",
    bandiera: "🇩🇪",
    lat: 49.0069,
    lng: 8.4037,
    qs2027: 110,
    qs2026: 116,
    punteggio_qs: 55.2,
    tasse_annue_eu: "~153 €/semestre (~310 €/anno)",
    affitto_mensile: "320–500 €",
    costo_vita_totale: "~650–900 €/mese",
    budget_rating: 4,
    lingua_triennale: "Tedesco (quasi tutti i BSc). Qualche traccia in inglese.",
    lingua_triennale_flag: "⚠️ TEDESCO",
    lauree_cs: "B.Sc. Informatik (tedesco), Information Engineering, Electrical Engineering",
    altre_ingegnerie: "Meccanica, Civile, Chimica, Fisica, Architettura",
    requisiti_ammissione: "Media buona. In alcuni corsi nessun NC; in altri test attitudinale.",
    test_lingua: "TestDaF / DSH per iscriversi in tedesco.",
    difficolta_ammissione: 3,
    qualita_vita: "Buona. Karlsruhe è una città media, vivace, vicina alla Foresta Nera.",
    soddisfazione_studenti: "Alta. Campus moderno, ottimi laboratori.",
    rapporto_studio_vita: "Bilanciato. Meno frenetico di Monaco.",
    approccio_didattico: "Solida base teorica. Ottimi laboratori embedded e robotica. Tra le prime in Germania per CS.",
    borse_sussidi: "DAAD scholarships. BAföG.",
    fit_score: 5,
    fit_note: "Simile a RWTH: eccellente ma richiede tedesco per la triennale.",
    punti_forza: ["#110 mondo", "Quasi gratis", "Ottimo per CS ed embedded"],
    punti_deboli: ["Triennale in tedesco", "Servirebbe padronanza tedesco"],
    url: "https://www.kit.edu/english/",
  },

  {
    id: "tu_berlin",
    nome: "Technische Universität Berlin",
    citta: "Berlino",
    paese: "Germania",
    bandiera: "🇩🇪",
    lat: 52.5121,
    lng: 13.3267,
    qs2027: 158,
    qs2026: 147,
    punteggio_qs: 43.6,
    tasse_annue_eu: "~360 €/semestre (include trasporti pubblici!)",
    affitto_mensile: "500–800 €",
    costo_vita_totale: "~900–1.300 €/mese",
    budget_rating: 3,
    lingua_triennale: "Tedesco (BSc). Magistrali spesso in inglese.",
    lingua_triennale_flag: "⚠️ TEDESCO",
    lauree_cs: "B.Sc. Informatik (tedesco), Elektrotechnik, Computer Engineering",
    altre_ingegnerie: "Meccanica, Civile, Chimica, Planning and Design",
    requisiti_ammissione: "Media buona. Nessun esame centralizzato obbligatorio.",
    test_lingua: "TestDaF/DSH per triennale tedesca.",
    difficolta_ammissione: 3,
    qualita_vita: "Eccezionale. Berlino è la capitale culturale d'Europa: arte, musica, startup, storia.",
    soddisfazione_studenti: "Alta, soprattutto per la vita cittadina. Campus nella capitale.",
    rapporto_studio_vita: "Molto buono. Berlino offre una vita sociale incredibile e prezzi relativamente contenuti per una capitale.",
    approccio_didattico: "Teorico con buoni laboratori. Vicina all'ecosistema startup berlinese.",
    borse_sussidi: "DAAD, BAföG.",
    fit_score: 5,
    fit_note: "Berlino è fantastica ma la triennale è in tedesco. Se impari il tedesco, è una scelta di vita straordinaria.",
    punti_forza: ["Berlino = città incredibile", "Ecosistema startup top", "Abbordabile per una capitale"],
    punti_deboli: ["Triennale in tedesco", "Ranking non altissimo rispetto a TUM"],
    url: "https://www.tu.berlin/en/",
  },

  {
    id: "tu_darmstadt",
    nome: "Technical University of Darmstadt",
    citta: "Darmstadt",
    paese: "Germania",
    bandiera: "🇩🇪",
    lat: 49.8728,
    lng: 8.6512,
    qs2027: 250,
    qs2026: 246,
    punteggio_qs: 33.4,
    tasse_annue_eu: "~260 €/semestre (~520 €/anno)",
    affitto_mensile: "350–550 €",
    costo_vita_totale: "~700–1.000 €/mese",
    budget_rating: 3,
    lingua_triennale: "Inglese (B.Sc. Computer Science completamente in inglese!)",
    lingua_triennale_flag: "✅ INGLESE",
    lauree_cs: "B.Sc. Computer Science (inglese!), Informatik (tedesco), Electrical Engineering",
    altre_ingegnerie: "Meccanica, Civile, Chimica, Architettura",
    requisiti_ammissione: "Media voti buona. Nessun esame di ammissione per il BSc CS. Selezione per GPA.",
    test_lingua: "IELTS 6.5 o TOEFL 90 per il BSc CS in inglese.",
    difficolta_ammissione: 3,
    qualita_vita: "Buona. Darmstadt è una città media vicina a Francoforte (30 min). Campus moderno.",
    soddisfazione_studenti: "Alta. Rinomata per l'informatica in Germania.",
    rapporto_studio_vita: "Bilanciato. Vicino a Francoforte per la vita notturna.",
    approccio_didattico: "Ottimo approccio pratico-teorico. Buoni laboratori di cybersecurity, AI, reti.",
    borse_sussidi: "DAAD. BAföG.",
    fit_score: 8,
    fit_note: "Gemma nascosta: BSc CS completamente in inglese, quasi gratis, ottima per informatica. Meno cara di Monaco.",
    punti_forza: ["BSc CS in inglese", "Quasi gratis (~520€/anno)", "Forte per CS e cybersecurity", "Vicina a Francoforte"],
    punti_deboli: ["Ranking 250° (non top)", "Darmstadt non è una grande città"],
    url: "https://www.tu-darmstadt.de/index.en.jsp",
  },

  // ─── PAESI BASSI ──────────────────────────────────────────────────────────
  {
    id: "tudelft",
    nome: "TU Delft",
    citta: "Delft",
    paese: "Paesi Bassi",
    bandiera: "🇳🇱",
    lat: 52.0016,
    lng: 4.3718,
    qs2027: 48,
    qs2026: 47,
    punteggio_qs: 84.5,
    tasse_annue_eu: "~2.530 €/anno (tariffa standard EU)",
    affitto_mensile: "600–950 € (crisi alloggi gravissima nei Paesi Bassi)",
    costo_vita_totale: "~1.100–1.500 €/mese",
    budget_rating: 2,
    lingua_triennale: "Inglese (B.Sc. Computer Science and Engineering completamente in inglese)",
    lingua_triennale_flag: "✅ INGLESE",
    lauree_cs: "B.Sc. Computer Science and Engineering (inglese), Electrical Engineering, Applied Mathematics",
    altre_ingegnerie: "Aerospaziale (famosa!), Civile, Architettura, Applied Physics, Nanobiology",
    requisiti_ammissione: "Matching & Selection: test online matematica + logica. Certificato inglese B2/C1. A volte colloquio.",
    test_lingua: "IELTS 6.5+ o B2 Cambridge (il tuo B2 quasi-C1 va bene!).",
    difficolta_ammissione: 3,
    qualita_vita: "Ottima. Campus spettacolare. Delft è una città bellissima a 15 min da Den Haag e 1h da Amsterdam.",
    soddisfazione_studenti: "Altissima per il lato didattico. Lo stress per trovare casa abbassa la media.",
    rapporto_studio_vita: "Sistema a quarti (4 periodi/anno), ritmo intenso. Molta componente pratica e teamwork.",
    approccio_didattico: "Project-Based Learning forte. Lavori costantemente su progetti di squadra. Altissima componente pratica.",
    borse_sussidi: "DUO (prestito studentesco olandese ~1.100 €/mese per studenti EU, da restituire lentamente). Borse Holland Scholarship.",
    fit_score: 8,
    fit_note: "Ottimo per CS con project-based learning. Il budget è un po' stretto (1.100-1.500€ contro i tuoi 600-800€) ma il DUO loan aiuta.",
    punti_forza: ["#48 mondo", "BSc CS in inglese", "Project-Based Learning", "Olanda ottima per networking tech"],
    punti_deboli: ["2.530€/anno tasse", "Crisi alloggi gravissima", "Budget stretto"],
    url: "https://www.tudelft.nl/en/",
  },

  {
    id: "tue",
    nome: "TU Eindhoven (TU/e)",
    citta: "Eindhoven",
    paese: "Paesi Bassi",
    bandiera: "🇳🇱",
    lat: 51.4478,
    lng: 5.4856,
    qs2027: 152,
    qs2026: 124,
    punteggio_qs: 44.8,
    tasse_annue_eu: "~2.530 €/anno",
    affitto_mensile: "550–850 € (crisi alloggi, ma meno grave che a Delft/Amsterdam)",
    costo_vita_totale: "~1.000–1.400 €/mese",
    budget_rating: 2,
    lingua_triennale: "Inglese (quasi tutte le triennali!)",
    lingua_triennale_flag: "✅ INGLESE",
    lauree_cs: "B.Sc. Computer Science and Engineering (inglese), Data Science, Electrical Engineering",
    altre_ingegnerie: "Meccanica, Industrial Design, Automotive, Biomedical",
    requisiti_ammissione: "Selection procedure online (matematica + logica). B2 inglese. Lettera motivazione.",
    test_lingua: "IELTS 6.5 o B2 Cambridge.",
    difficolta_ammissione: 3,
    qualita_vita: "Buona. Eindhoven è la città di ASML e Philips. Meno turistica di Amsterdam, ma dinamica.",
    soddisfazione_studenti: "Alta. Ambiente molto focalizzato su innovazione e tech. Startup culture vivace.",
    rapporto_studio_vita: "Challenge-Based Learning: molto lavoro di gruppo su progetti reali con aziende.",
    approccio_didattico: "Challenge-Based Learning. Collaborazioni con industria (ASML, Philips, DAF). Ottimo per embedded e robotica.",
    borse_sussidi: "DUO loan (~1.100€/mese). Holland Scholarship per studenti eccellenti.",
    fit_score: 9,
    fit_note: "Top per te: triennale CS in inglese, challenge-based learning, collaborazione con aziende tech, ottimo per embedded/robotica. Budget stretto ma gestibile con DUO.",
    punti_forza: ["BSc CS in inglese", "Challenge-Based Learning", "Ecosistema ASML/Philips", "Ottimo per embedded/AI"],
    punti_deboli: ["2.530€/anno tasse", "Crisi alloggi", "Ranking sceso a 152° (ma ottima reputazione)"],
    url: "https://www.tue.nl/en/",
  },

  {
    id: "utwente",
    nome: "University of Twente",
    citta: "Enschede",
    paese: "Paesi Bassi",
    bandiera: "🇳🇱",
    lat: 52.2388,
    lng: 6.8566,
    qs2027: 223,
    qs2026: 210,
    punteggio_qs: 36.1,
    tasse_annue_eu: "~2.530 €/anno",
    affitto_mensile: "400–650 € (campus residenziale, più economico!)",
    costo_vita_totale: "~800–1.100 €/mese",
    budget_rating: 3,
    lingua_triennale: "Inglese (quasi tutte le triennali in inglese)",
    lingua_triennale_flag: "✅ INGLESE",
    lauree_cs: "B.Sc. Computer Science (inglese), Electrical Engineering, Creative Technology, Robotics & Mechatronics",
    altre_ingegnerie: "Meccanica, Civile, Biomedica, Industrial Engineering",
    requisiti_ammissione: "Nessun esame speciale. Invio documenti + B2 inglese. Matching day.",
    test_lingua: "IELTS 6.0 o B2 Cambridge.",
    difficolta_ammissione: 2,
    qualita_vita: "Ottima. Campus completamente chiuso (boschi, laghi, ristoranti, bar). Stile di vita unico.",
    soddisfazione_studenti: "Altissima per la vita campus. Enschede è piccola ma il campus è autosufficiente.",
    rapporto_studio_vita: "Eccellente. Campus life = vita sociale + studio. I laboratori sono aperti H24.",
    approccio_didattico: "Forte project-based learning. B.Sc. Robotics & Mechatronics è unico in Europa. Ottimo per embedded.",
    borse_sussidi: "Holland Scholarship (5.000€ una tantum). DUO loan.",
    fit_score: 9,
    fit_note: "Gemma nascosta: ha un BSc in Robotics & Mechatronics in inglese e ottima didattica pratica. Budget più gestibile (800-1.100€). Campus vita unica.",
    punti_forza: ["BSc Robotics & Mechatronics in inglese", "Budget più abbordabile", "Campus residence economica", "Project-based forte"],
    punti_deboli: ["Ranking 223°", "Enschede = città piccola", "2.530€/anno tasse"],
    url: "https://www.utwente.nl/en/",
  },

  // ─── DANIMARCA ────────────────────────────────────────────────────────────
  {
    id: "dtu",
    nome: "Technical University of Denmark (DTU)",
    citta: "Kongens Lyngby (Copenaghen)",
    paese: "Danimarca",
    bandiera: "🇩🇰",
    lat: 55.7858,
    lng: 12.5214,
    qs2027: 105,
    qs2026: 106,
    punteggio_qs: 56.5,
    tasse_annue_eu: "GRATIS (0 €) per cittadini EU",
    affitto_mensile: "550–850 DKK al mese... no, € 550–850 (student housing DTU prioritario)",
    costo_vita_totale: "~1.000–1.400 €/mese (cara, ma…)",
    budget_rating: 3,
    lingua_triennale: "Inglese (B.Eng. in General Engineering con specializzazione in Digital Tech, Cyber Systems, AI, Sustainable Energy)",
    lingua_triennale_flag: "✅ INGLESE",
    lauree_cs: "B.Eng. General Engineering → Digital Tech / AI / Cyber Systems (inglese), B.Sc. Matematica",
    altre_ingegnerie: "Sostenibile, Biotech, Chimica, Fisica, Management Engineering",
    requisiti_ammissione: "GPA superiori alto. Matematica livello A (equivalente alla tua quarta/quinta ITIS). Inglese C1 (o B2 alto). Nessun esame speciale.",
    test_lingua: "IELTS 6.5 o equivalente C1. Il tuo B2 quasi-C1 potrebbe bastare con una buona lettera.",
    difficolta_ammissione: 3,
    qualita_vita: "Eccellente. Copenaghen è la capitale più vivibile al mondo. Bici ovunque, natura, mare.",
    soddisfazione_studenti: "Straordinaria. Approccio scandinavo: nessuna gerarchia, professori chiamati per nome, ambiente collaborativo.",
    rapporto_studio_vita: "Ottimo. I danesi credono nel 'hygge' — anche a DTU si studia ma c'è equilibrio. Molta vita sociale.",
    approccio_didattico: "Project-based con forte connessione industria. DTU ha spin-off e startup dal campus.",
    borse_sussidi: "SU (Statens Uddannelsesstøtte): se lavori ≥10 ore/settimana ottieni ~800€/mese a fondo perduto dallo stato danese! Questo cambia completamente il budget.",
    fit_score: 9,
    fit_note: "Università GRATIS + sussidio statale ~800€/mese con un lavoretto part-time. Copenaghen è cara ma col SU diventa gestibile. Triennale in inglese su AI/Cyber.",
    punti_forza: ["GRATIS per EU", "SU statale ~800€/mese con lavoro PT", "Top 105 mondo", "Triennale inglese su AI/Cyber"],
    punti_deboli: ["Copenaghen carissima", "Richiede C1 o quasi (ma tu ci sei vicino)", "SU richiede lavoretto"],
    url: "https://www.dtu.dk/english",
  },

  {
    id: "aau",
    nome: "Aalborg University (AAU)",
    citta: "Aalborg",
    paese: "Danimarca",
    bandiera: "🇩🇰",
    lat: 57.0140,
    lng: 9.9858,
    qs2027: 329,
    qs2026: 352,
    punteggio_qs: 28.1,
    tasse_annue_eu: "GRATIS (0 €) per cittadini EU",
    affitto_mensile: "300–500 € (Aalborg è molto economica!)",
    costo_vita_totale: "~700–1.000 €/mese",
    budget_rating: 4,
    lingua_triennale: "Inglese (Robotics, Computer Science, Applied Industrial Electronics)",
    lingua_triennale_flag: "✅ INGLESE",
    lauree_cs: "B.Sc. Computer Science (inglese), Robotics (inglese), Software Engineering",
    altre_ingegnerie: "Elettronica Industriale, Meccatronica, Energy Engineering, Civil Engineering",
    requisiti_ammissione: "GPA buono. Inglese B2/C1. Nessun test speciale.",
    test_lingua: "IELTS 6.0 o B2. Più accessibile di DTU.",
    difficolta_ammissione: 2,
    qualita_vita: "Molto buona. Aalborg è una città vivace, universitaria, con ottima qualità della vita nordica.",
    soddisfazione_studenti: "Altissima. L'approccio PBL crea comunità di progetto molto unite.",
    rapporto_studio_vita: "Eccellente. Il semestre è diviso: metà tempo su lezioni, metà su un mega-progetto di gruppo con aziende.",
    approccio_didattico: "Il modello PBL (Problem-Based Learning) di Aalborg è famoso nel mondo. Ogni semestre: un grande progetto reale con un'azienda partner.",
    borse_sussidi: "SU statale ~800€/mese con lavoretto. Con 600€ dai genitori + SU si vive benissimo ad Aalborg!",
    fit_score: 10,
    fit_note: "FIT PERFETTO: GRATIS, PBL al 100%, BSc Robotics in inglese, Aalborg economica (700-1.000€). Con il SU danese il budget torna perfettamente. I tuoi progetti Unity ML-Agents/RoboCup sarebbero oro qui.",
    punti_forza: ["GRATIS per EU", "BSc Robotics in inglese", "Modello PBL mondiale", "Aalborg economica", "SU statale"],
    punti_deboli: ["Ranking 329° (ma reputazione didattica top)", "Aalborg = città piccola nordica"],
    url: "https://www.en.aau.dk/",
  },

  // ─── SVEZIA ───────────────────────────────────────────────────────────────
  {
    id: "kth",
    nome: "KTH Royal Institute of Technology",
    citta: "Stoccolma",
    paese: "Svezia",
    bandiera: "🇸🇪",
    lat: 59.3498,
    lng: 18.0707,
    qs2027: 82,
    qs2026: 83,
    punteggio_qs: 67.1,
    tasse_annue_eu: "GRATIS (0 €) per cittadini EU",
    affitto_mensile: "450–750 € (SSSB: iscriviti SUBITO alla lista — ci vogliono mesi!)",
    costo_vita_totale: "~900–1.300 €/mese",
    budget_rating: 3,
    lingua_triennale: "Inglese (B.Sc. Information and Communication Technology — ICT — in inglese!)",
    lingua_triennale_flag: "✅ INGLESE",
    lauree_cs: "B.Sc. ICT – Information and Communication Technology (inglese), B.Sc. in Engineering Informatics (svedese)",
    altre_ingegnerie: "Elettrica, Meccanica, Aerospaziale, Civile, Veicoli (in svedese)",
    requisiti_ammissione: "Voti superiori + valutazione del tuo B2 Cambridge (spesso accettato come English 6 svedese). Nessun test speciale.",
    test_lingua: "B2 o superiore. Il tuo B2 quasi-C1 è esattamente quello che cercano.",
    difficolta_ammissione: 3,
    qualita_vita: "Stoccolma è una delle città più belle e vivibili al mondo. Natura, cultura, design nordico.",
    soddisfazione_studenti: "Eccezionale. KTH ha una community studentesca fortissima. Capitales europee top.",
    rapporto_studio_vita: "Ottimo. Alternanza tra studio intenso e rilassamento nordico.",
    approccio_didattico: "Forte enfasi su progetti pratici fin dal primo anno. ICT copre reti, AI, sistemi embedded — calza perfettamente con il tuo background ITIS.",
    borse_sussidi: "CSN (prestito studentesco svedese ~1.400 €/mese, da restituire). Nessun sussidio automatico come in Danimarca.",
    fit_score: 9,
    fit_note: "Eccellente: GRATIS, triennale ICT in inglese che copre esattamente reti/AI/embedded come il tuo ITIS. Stoccolma richiede un po' di budget extra.",
    punti_forza: ["GRATIS per EU", "#82 mondo", "BSc ICT in inglese (reti+AI+embedded)", "Stoccolma = città meravigliosa"],
    punti_deboli: ["Stoccolma cara (900-1.300€/mese)", "Lista alloggi SSSB lunga", "Nessun sussidio automatico"],
    url: "https://www.kth.se/en",
  },

  {
    id: "chalmers",
    nome: "Chalmers University of Technology",
    citta: "Göteborg",
    paese: "Svezia",
    bandiera: "🇸🇪",
    lat: 57.6893,
    lng: 11.9792,
    qs2027: 174,
    qs2026: 167,
    punteggio_qs: 42.4,
    tasse_annue_eu: "GRATIS (0 €) per cittadini EU",
    affitto_mensile: "400–650 € (Göteborg meno cara di Stoccolma)",
    costo_vita_totale: "~800–1.200 €/mese",
    budget_rating: 3,
    lingua_triennale: "Svedese (quasi tutti i BSc). Magistrali in inglese.",
    lingua_triennale_flag: "⚠️ SVEDESE (BSc), inglese magistrali",
    lauree_cs: "Civilingenjör Datateknik (svedese), Elektroteknik (svedese). Magistrali: Computer Science & Engineering (inglese)",
    altre_ingegnerie: "Meccanica, Nave/Oceano, Chimica, Architettura, Industriale",
    requisiti_ammissione: "Voti svedesi o equivalenza. Swedish B/English 6 per svedese. IELTS per magistrali inglesi.",
    test_lingua: "Svedese B2 per triennale. English B per magistrale.",
    difficolta_ammissione: 3,
    qualita_vita: "Molto buona. Göteborg è la seconda città svedese, giovane e vivace. Prezzi più abbordabili di Stoccolma.",
    soddisfazione_studenti: "Alta. Chalmers è fortissima nell'automotive (Volvo, CEVT sono qui).",
    rapporto_studio_vita: "Buono. Göteborg è una città universitaria con buona vita sociale.",
    approccio_didattico: "Eccellente ingegneria, forte per automotive, aero, meccanica. Per CS la triennale è in svedese.",
    borse_sussidi: "CSN loan. Nessun sussidio automatico.",
    fit_score: 5,
    fit_note: "Ottima università ma la triennale in informatica è in svedese. Valida principalmente per magistrali in inglese.",
    punti_forza: ["GRATIS per EU", "Forte per engineering automotive/meccanica", "Göteborg economica"],
    punti_deboli: ["Triennale in svedese", "Servirebbe apprendere svedese"],
    url: "https://www.chalmers.se/en/",
  },

  {
    id: "linköping",
    nome: "Linköping University (LiU)",
    citta: "Linköping",
    paese: "Svezia",
    bandiera: "🇸🇪",
    lat: 58.3994,
    lng: 15.6193,
    qs2027: 308,
    qs2026: 316,
    punteggio_qs: 29.2,
    tasse_annue_eu: "GRATIS (0 €) per cittadini EU",
    affitto_mensile: "300–500 € (Linköping è molto economica!)",
    costo_vita_totale: "~700–1.000 €/mese",
    budget_rating: 4,
    lingua_triennale: "Svedese (BSc). Alcune magistrali in inglese.",
    lingua_triennale_flag: "⚠️ SVEDESE",
    lauree_cs: "Civilingenjör Datateknik (svedese), Mjukvaruteknik (Software Engineering, svedese)",
    altre_ingegnerie: "Meccanica, Aeronautica (forte: SAAB è qui!), Industriale",
    requisiti_ammissione: "Voti svedesi o conversione. Matematica 4/5.",
    test_lingua: "Svedese B2.",
    difficolta_ammissione: 2,
    qualita_vita: "Molto buona. Città universitaria svedese tranquilla, economica.",
    soddisfazione_studenti: "Alta, specialmente per ingegneria aeronautica.",
    rapporto_studio_vita: "Eccellente. Ritmi nordici, molta attenzione al benessere.",
    approccio_didattico: "Molto pratica e project-based. Vicina all'industria SAAB (aerospazio e difesa).",
    borse_sussidi: "CSN loan.",
    fit_score: 4,
    fit_note: "Buona ma triennale in svedese. Interessante per aerospazio/software. Costi ottimi per il budget.",
    punti_forza: ["GRATIS", "Costi bassi (~700-1.000€/mese)", "Vicina a SAAB (aerospazio)"],
    punti_deboli: ["Triennale in svedese", "Ranking 308°"],
    url: "https://liu.se/en",
  },

  // ─── FINLANDIA ────────────────────────────────────────────────────────────
  {
    id: "aalto",
    nome: "Aalto University",
    citta: "Espoo (Helsinki)",
    paese: "Finlandia",
    bandiera: "🇫🇮",
    lat: 60.1841,
    lng: 24.8301,
    qs2027: 126,
    qs2026: 109,
    punteggio_qs: 52.1,
    tasse_annue_eu: "GRATIS (0 €) per cittadini EU",
    affitto_mensile: "350–600 € (HOAS e AYY: student housing tra i migliori d'Europa)",
    costo_vita_totale: "~800–1.200 €/mese",
    budget_rating: 3,
    lingua_triennale: "Inglese (B.Sc. Science and Technology completamente in inglese)",
    lingua_triennale_flag: "✅ INGLESE",
    lauree_cs: "B.Sc. Computer Science (inglese), Digital Systems and Design, Data Science, Computational Engineering",
    altre_ingegnerie: "Elettrica, Meccanica, Industrial Design (famosa), Automation",
    requisiti_ammissione: "SAT o equivalente. Voti superiori. Lettera motivazione. A volte portfolio (per design).",
    test_lingua: "IELTS 6.5 o B2 Cambridge per Science & Tech.",
    difficolta_ammissione: 3,
    qualita_vita: "Ottima. Espoo/Helsinki: mare, foreste, città moderna e sicura.",
    soddisfazione_studenti: "Straordinaria. Campus enorme con Design Factory, Startup Sauna, maker spaces aperti H24.",
    rapporto_studio_vita: "Eccellente. La Finlandia valorizza il tempo libero. La Design Factory è aperta a tutti.",
    approccio_didattico: "Maker culture, project-based, startup-friendly. Ottica 'crea e sperimenta'. Simile alla cultura dei tuoi progetti Arduino/RoboCup.",
    borse_sussidi: "Opintotuki (~300€/mese dallo stato finlandese per EU, senza lavorare). Mense universitarie a 3€ a pasto!",
    fit_score: 10,
    fit_note: "FIT PERFETTO: GRATIS, BSc CS in inglese, maker culture che ama Arduino/robotica/AI, mense a 3€, sussidio ~300€/mese. Con 600-800€ dai genitori + 300€ stato + mense a 3€ si vive!",
    punti_forza: ["GRATIS per EU", "BSc CS in inglese", "Maker culture (Design Factory)", "Mense a 3€", "Sussidio ~300€/mese senza lavoro"],
    punti_deboli: ["Helsinki non economicissima (800-1.200€)", "Ammissione un po' selettiva", "Inverni bui e freddi 🌨️"],
    url: "https://www.aalto.fi/en",
  },

  {
    id: "tampere",
    nome: "Tampere University",
    citta: "Tampere",
    paese: "Finlandia",
    bandiera: "🇫🇮",
    lat: 61.4978,
    lng: 23.7610,
    qs2027: 436,
    qs2026: 401,
    punteggio_qs: 24.8,
    tasse_annue_eu: "GRATIS (0 €) per cittadini EU",
    affitto_mensile: "250–420 € (Tampere è molto economica)",
    costo_vita_totale: "~650–950 €/mese",
    budget_rating: 5,
    lingua_triennale: "Inglese (B.Sc. Computer Science in inglese!)",
    lingua_triennale_flag: "✅ INGLESE",
    lauree_cs: "B.Sc. Computer Science (inglese), Information Technology (inglese)",
    altre_ingegnerie: "Electrical Engineering, Mechanical Engineering, Civil Engineering, Medicine, Social Sciences",
    requisiti_ammissione: "Voti superiori + SAT Math o equivalente. Inglese B2.",
    test_lingua: "IELTS 6.0 o B2 Cambridge.",
    difficolta_ammissione: 2,
    qualita_vita: "Ottima. Tampere è la seconda città della Finlandia. Laghi, saune, natura. Molto universitaria.",
    soddisfazione_studenti: "Alta. Ambiente friendly, piccola comunità coesa.",
    rapporto_studio_vita: "Eccellente. Finlandia = work-life balance per definizione.",
    approccio_didattico: "Project-based, innovativo. Tampere è forte in game development, AR/VR e mobile tech.",
    borse_sussidi: "Opintotuki (~300€/mese senza lavorare). Mense universitarie a 3€.",
    fit_score: 9,
    fit_note: "Nascosta ma eccellente: GRATIS, BSc CS in inglese, forte per game development (vicina alla tua esperienza Unity!), Tampere economicissima. Il budget 600-800€ qui funziona.",
    punti_forza: ["GRATIS per EU", "BSc CS in inglese", "Forte per game dev e AI", "Economicissima (~650-950€)", "Sussidio ~300€/mese"],
    punti_deboli: ["Ranking 436°", "Tampere = città nordica piccola", "Inverni lunghi"],
    url: "https://www.tuni.fi/en",
  },

  // ─── IRLANDA ──────────────────────────────────────────────────────────────
  {
    id: "tcd",
    nome: "Trinity College Dublin (TCD)",
    citta: "Dublino",
    paese: "Irlanda",
    bandiera: "🇮🇪",
    lat: 53.3438,
    lng: -6.2546,
    qs2027: 75,
    qs2026: 78,
    punteggio_qs: 72.3,
    tasse_annue_eu: "~3.000–4.000 €/anno (per EU ma tasse più alte dell'anno precedente)",
    affitto_mensile: "700–1.200 € (Dublino ha una crisi degli affitti gravissima)",
    costo_vita_totale: "~1.200–1.800 €/mese",
    budget_rating: 1,
    lingua_triennale: "Inglese (ovviamente — è Irlanda!)",
    lingua_triennale_flag: "✅ INGLESE",
    lauree_cs: "B.Sc. Computer Science (4 anni), Integrated Computer Science, Nanoscience",
    altre_ingegnerie: "Ingegneria Civile, Elettrica, Meccanica, Manufacturing (Engineering Tripos)",
    requisiti_ammissione: "Leaving Certificate o equivalente internazionale. Nessun test speciale per EU. Motivational statement.",
    test_lingua: "Non richiesto (sei già B2/C1 e la lingua è inglese).",
    difficolta_ammissione: 3,
    qualita_vita: "Ottima. Dublino è dinamica, verde, con forte ecosistema tech (Google, Facebook/Meta, Apple, Microsoft hanno HQ europei qui).",
    soddisfazione_studenti: "Alta. TCD è una delle università più antiche e prestigiose del mondo. Campus storico bellissimo.",
    rapporto_studio_vita: "Buono. La vita universitaria irlandese è molto social (pub culture). Puoi già conosci Dublino dal tuo Erasmus!",
    approccio_didattico: "Misto teorico-pratico. Forti connessioni con l'industria tech di Dublino.",
    borse_sussidi: "SUSI Grant per studenti EU in difficoltà economica. Alcune borse TCD.",
    fit_score: 7,
    fit_note: "Tu conosci già Dublino dal tuo Erasmus! Campus bellissimo, top 75 mondo, ecosistema tech enorme. Ma Dublino è carissima (1.200-1.800€/mese) e le tasse non sono basse.",
    punti_forza: ["#75 mondo", "Conosci già Dublino!", "Ecosistema Google/Apple/Meta", "Inglese madrelingua"],
    punti_deboli: ["Carissima (1.200-1.800€/mese)", "3.000-4.000€/anno tasse", "Crisi affitti gravissima"],
    url: "https://www.tcd.ie/",
  },

  {
    id: "ucd",
    nome: "University College Dublin (UCD)",
    citta: "Dublino",
    paese: "Irlanda",
    bandiera: "🇮🇪",
    lat: 53.3070,
    lng: -6.2240,
    qs2027: 100,
    qs2026: 105,
    punteggio_qs: 59.1,
    tasse_annue_eu: "~3.000–4.000 €/anno",
    affitto_mensile: "700–1.200 € (crisi affitti)",
    costo_vita_totale: "~1.200–1.800 €/mese",
    budget_rating: 1,
    lingua_triennale: "Inglese",
    lingua_triennale_flag: "✅ INGLESE",
    lauree_cs: "B.Sc. Computer Science (4 anni), Data Science, Software Engineering",
    altre_ingegnerie: "Civile, Elettrica, Meccanica, Biomedica",
    requisiti_ammissione: "Leaving Certificate o equivalente. Motivational statement.",
    test_lingua: "Non richiesto.",
    difficolta_ammissione: 3,
    qualita_vita: "Ottima. Campus immenso (1.300 acri!). Ecosistema tech enorme.",
    soddisfazione_studenti: "Alta. Università molto internazionale.",
    rapporto_studio_vita: "Buono. Campus molto vivo con sport, clubs, eventi.",
    approccio_didattico: "Buon mix teorico-pratico. Stage con aziende tech.",
    borse_sussidi: "SUSI Grant. UCD Global Excellence Scholarships.",
    fit_score: 6,
    fit_note: "Simile a TCD ma campus più moderno. Il problema è lo stesso: Dublino è carissima per il tuo budget.",
    punti_forza: ["#100 mondo", "Ecosistema tech Dublino", "Campus immenso"],
    punti_deboli: ["Carissima", "Tasse alte per EU"],
    url: "https://www.ucd.ie/",
  },

  // ─── BELGIO ───────────────────────────────────────────────────────────────
  {
    id: "ku_leuven",
    nome: "KU Leuven",
    citta: "Leuven",
    paese: "Belgio",
    bandiera: "🇧🇪",
    lat: 50.8789,
    lng: 4.7012,
    qs2027: 59,
    qs2026: 60,
    punteggio_qs: 80.4,
    tasse_annue_eu: "~960 €/anno (tasse molto basse per EU!)",
    affitto_mensile: "400–650 € (Leuven è piccola città universitaria, abbordabile)",
    costo_vita_totale: "~800–1.200 €/mese",
    budget_rating: 3,
    lingua_triennale: "Olandese/Fiammingo (BSc). Magistrali in inglese.",
    lingua_triennale_flag: "⚠️ FIAMMINGO (BSc), inglese magistrali",
    lauree_cs: "Bachelor Informatica (fiammingo), Bachelor Ingegneria Informatica (fiammingo). Magistrali: CS/AI/Software Engineering (inglese)",
    altre_ingegnerie: "Meccanica, Civile, Elettrica, Biomedica, Architettura",
    requisiti_ammissione: "Valutazione del diploma. Nessun test speciale per EU.",
    test_lingua: "Fiammingo per BSc. IELTS 7.0 per magistrali inglesi.",
    difficolta_ammissione: 3,
    qualita_vita: "Ottima. Leuven è una delle più belle città universitarie medievali d'Europa. Birra Stella Artois è nata qui 🍺.",
    soddisfazione_studenti: "Altissima. KU Leuven è la università più ricca per ricerca in Europa.",
    rapporto_studio_vita: "Molto buono. Leuven è una città campus, vivacissima.",
    approccio_didattico: "Forte ricerca, ottimi laboratori AI e ML. Meno project-based ma eccellente qualità.",
    borse_sussidi: "Borse KU Leuven per studenti EU eccellenti. Tasse basse già di base.",
    fit_score: 6,
    fit_note: "Top per qualità di ricerca (tra le prime in Europa) ma triennale in fiammingo. Valida se studi olandese o miri alla magistrale.",
    punti_forza: ["#59 mondo", "Tasse solo 960€/anno", "Top per ricerca AI/ML", "Leuven bellissima"],
    punti_deboli: ["Triennale in fiammingo", "Servirebbe olandese per BSc"],
    url: "https://www.kuleuven.be/english",
  },

  {
    id: "vub",
    nome: "Vrije Universiteit Brussel (VUB)",
    citta: "Bruxelles",
    paese: "Belgio",
    bandiera: "🇧🇪",
    lat: 50.8199,
    lng: 4.3988,
    qs2027: 295,
    qs2026: 296,
    punteggio_qs: 30.7,
    tasse_annue_eu: "~960 €/anno",
    affitto_mensile: "450–700 € (Bruxelles è più cara di Leuven ma non come Amsterdam)",
    costo_vita_totale: "~900–1.300 €/mese",
    budget_rating: 3,
    lingua_triennale: "Olandese (quasi tutti i BSc). Alcune magistrali in inglese.",
    lingua_triennale_flag: "⚠️ FIAMMINGO",
    lauree_cs: "Bachelor Informatica (fiammingo), Computer Science Engineering (fiammingo)",
    altre_ingegnerie: "Ingegneria, Biomedica",
    requisiti_ammissione: "Diploma equivalenza. Nessun test.",
    test_lingua: "Fiammingo B2.",
    difficolta_ammissione: 2,
    qualita_vita: "Buona. Bruxelles = capitale EU, molto cosmopolita e internazionale.",
    soddisfazione_studenti: "Buona. Ambiente molto internazionale grazie alle istituzioni EU.",
    rapporto_studio_vita: "Buono. Bruxelles offre moltissimo culturalmente.",
    approccio_didattico: "Buona qualità, meno rinomata di KU Leuven ma più internazionale.",
    borse_sussidi: "Tasse basse. Alcune borse VUB.",
    fit_score: 4,
    fit_note: "Triennale in fiammingo limita l'accesso. Bruxelles è interessante ma non il top per CS.",
    punti_forza: ["Capitale EU", "Tasse basse 960€", "Ambiente internazionale"],
    punti_deboli: ["Triennale in fiammingo", "Ranking 295°"],
    url: "https://www.vub.be/en",
  },

  // ─── NORVEGIA ─────────────────────────────────────────────────────────────
  {
    id: "ntnu",
    nome: "Norwegian University of Science and Technology (NTNU)",
    citta: "Trondheim",
    paese: "Norvegia",
    bandiera: "🇳🇴",
    lat: 63.4189,
    lng: 10.4028,
    qs2027: 264,
    qs2026: 263,
    punteggio_qs: 32.6,
    tasse_annue_eu: "GRATIS (0 €) per cittadini EU — università pubblica norvegese",
    affitto_mensile: "350–600 € (Trondheim abbordabile con student housing NTNU)",
    costo_vita_totale: "~800–1.200 €/mese",
    budget_rating: 3,
    lingua_triennale: "Norvegeseo principalmente. Alcune triennali in inglese (Computer Science BSc!).",
    lingua_triennale_flag: "✅ INGLESE (alcune triennali)",
    lauree_cs: "B.Sc. Computer Science (inglese disponibile), Informatics, Electronic Systems Engineering",
    altre_ingegnerie: "Meccanica, Civile, Materiali, Marina, Ingegneria Chimica, Biomedica",
    requisiti_ammissione: "GPA superiori. Matematica avanzata. Inglese B2 per corsi in inglese.",
    test_lingua: "IELTS 6.0 o B2 per corsi inglese.",
    difficolta_ammissione: 2,
    qualita_vita: "Eccellente qualità nordica. Trondheim è splendida, con fiordi, sport invernali, natura.",
    soddisfazione_studenti: "Molto alta. NTNU è la principale università tecnica della Norvegia.",
    rapporto_studio_vita: "Ottimo. La cultura norvegese bilancia molto bene lavoro e vita.",
    approccio_didattico: "Forte per ingegneria applicata. Buoni laboratori. Cooperazione con industria norvegese (energia, petrolio, marina).",
    borse_sussidi: "LÅNEKASSEN (prestito-borsa norvegese ~1.100€/mese anche per studenti EU!). Questo rende la Norvegia un'opzione eccellente.",
    fit_score: 7,
    fit_note: "GRATIS + LÅNEKASSEN ~1.100€/mese per studenti EU! Trondheim economica. BSc CS in inglese disponibile. Ma Trondheim è molto a nord e la vita può essere isolante.",
    punti_forza: ["GRATIS per EU", "LÅNEKASSEN ~1.100€/mese", "BSc CS in inglese", "Natura straordinaria"],
    punti_deboli: ["Trondheim = molto a nord, inverni lunghi", "Ranking 264°", "Cultura molto nordica"],
    url: "https://www.ntnu.edu/",
  },

  // ─── AUSTRIA ──────────────────────────────────────────────────────────────
  {
    id: "tu_wien",
    nome: "TU Wien (Vienna University of Technology)",
    citta: "Vienna",
    paese: "Austria",
    bandiera: "🇦🇹",
    lat: 48.1984,
    lng: 16.3698,
    qs2027: 191,
    qs2026: 192,
    punteggio_qs: 40.1,
    tasse_annue_eu: "~363 €/anno (tasse minime per EU)",
    affitto_mensile: "400–700 € (Vienna più economica di Zurigo/Monaco ma in crescita)",
    costo_vita_totale: "~800–1.200 €/mese",
    budget_rating: 3,
    lingua_triennale: "Tedesco (BSc). Magistrali spesso in inglese.",
    lingua_triennale_flag: "⚠️ TEDESCO",
    lauree_cs: "B.Sc. Informatik (tedesco), Software & Information Engineering, Computer Engineering",
    altre_ingegnerie: "Meccanica, Civile, Elettrotecnica, Fisica Tecnica, Architettura",
    requisiti_ammissione: "Maturità o equivalente. Test matematico per alcuni corsi. Nessun concorso centralizzato.",
    test_lingua: "TestDaF/DSH per triennale tedesca.",
    difficolta_ammissione: 2,
    qualita_vita: "Straordinaria. Vienna è stata eletta più volte la città con la migliore qualità della vita al mondo. Musica, cultura, caffè storici.",
    soddisfazione_studenti: "Alta. Vienna è una città universitaria incredibile.",
    rapporto_studio_vita: "Ottimo. Viennese culture valorizza il Kaffeehaus e il tempo libero.",
    approccio_didattico: "Buona qualità teorica alla tedesca. Buoni laboratori. Meno project-based di DTU/Aalborg.",
    borse_sussidi: "Stipendio statale austriaco per chi ne ha diritto. Alcune borse TU Wien.",
    fit_score: 5,
    fit_note: "Vienna è magnifica e le tasse sono basse, ma la triennale di informatica è in tedesco.",
    punti_forza: ["Vienna = città migliore al mondo per qualità vita", "Tasse ~363€/anno", "Cultura straordinaria"],
    punti_deboli: ["Triennale in tedesco", "Servirebbe B1+ tedesco"],
    url: "https://www.tuwien.at/en/",
  },

  // ─── ITALIA ───────────────────────────────────────────────────────────────
  {
    id: "polimi",
    nome: "Politecnico di Milano",
    citta: "Milano",
    paese: "Italia",
    bandiera: "🇮🇹",
    lat: 45.4781,
    lng: 9.2273,
    qs2027: 87,
    qs2026: 111,
    punteggio_qs: 64.6,
    tasse_annue_eu: "Fino a ~3.900 €/anno (in base all'ISEE; chi ha ISEE basso paga poco o nulla)",
    affitto_mensile: "450–750 € (Milano è carissima per l'Italia; cercare a Sesto, Cologno, Monza)",
    costo_vita_totale: "~900–1.400 €/mese",
    budget_rating: 2,
    lingua_triennale: "Italiano (triennali). Molte magistrali in inglese.",
    lingua_triennale_flag: "🇮🇹 ITALIANO",
    lauree_cs: "L Informatica (3 anni), L Ingegneria Informatica (3 anni), Ingegneria Elettrica, Matematica",
    altre_ingegnerie: "Aerospaziale, Biomedica, Meccanica, Automazione, Ambientale, Gestionale, Architettura",
    requisiti_ammissione: "TOLC-I (test CISIA online, ~16-20€). Puoi ripeterlo più volte. Voti alti aiutano per corsi con soglia.",
    test_lingua: "Non richiesto per italiano. IELTS per alcune magistrali in inglese.",
    difficolta_ammissione: 3,
    qualita_vita: "Alta. Milano è la capitale economica e della moda d'Italia. Moltissime opportunità lavorative.",
    soddisfazione_studenti: "Alta per il prestigio e le opportunità. Carico accademico molto pesante però.",
    rapporto_studio_vita: "Molto intenso. 'Poli' è noto per essere impegnativo. Meno tempo libero rispetto al nord Europa.",
    approccio_didattico: "Forte base matematico-teorica. Laboratori buoni. Approccio pratico arriva più in magistrale.",
    borse_sussidi: "DSU (Diritto allo Studio Universitario): con ISEE basso puoi avere borsa completa + alloggio. Ottimo.",
    fit_score: 8,
    fit_note: "Top italiano salito all'87° mondiale (meglio di KTH e Aalto!). Con ISEE favorevole è quasi gratis. Vicino a casa. Ottimo per chi vuole restare in Italia o puntare magistrale estero.",
    punti_forza: ["#87 mondo (top!)", "Vicino a casa", "Borsa DSU se ISEE basso", "Ottimo per magistrale estero dopo"],
    punti_deboli: ["Milano carissima", "Molto intenso/stressante", "Approccio meno pratico del nord Europa"],
    url: "https://www.polimi.it/",
  },

  {
    id: "polito",
    nome: "Politecnico di Torino",
    citta: "Torino",
    paese: "Italia",
    bandiera: "🇮🇹",
    lat: 45.0628,
    lng: 7.6626,
    qs2027: 206,
    qs2026: 214,
    punteggio_qs: 38.8,
    tasse_annue_eu: "Fino a ~2.600 €/anno (ISEE-based; soglie più basse = quasi gratis)",
    affitto_mensile: "300–500 € (Torino economica per standard italiani)",
    costo_vita_totale: "~700–1.100 €/mese",
    budget_rating: 4,
    lingua_triennale: "Italiano / Inglese (la triennale Computer Engineering è interamente in inglese!)",
    lingua_triennale_flag: "✅ ITALIANO / INGLESE",
    lauree_cs: "L Ingegneria Informatica (italiano), BSc Computer Engineering (inglese — unico in Italia!), Ingegneria Elettronica",
    altre_ingegnerie: "Meccanica, Aerospaziale, Autoveicolo, Civile, Gestionale, Meccatronica",
    requisiti_ammissione: "TIL-I (test proprietario PoliTo). Soglia di accesso variabile per anno.",
    test_lingua: "Nessuno per italiano. Per Computer Engineering in inglese: non richiesto ma consigliato.",
    difficolta_ammissione: 3,
    qualita_vita: "Molto buona. Torino è una città universitaria per eccellenza, Alpi vicine, vivace.",
    soddisfazione_studenti: "Alta. Città economica, divertente, ottima per studenti.",
    rapporto_studio_vita: "Impegnativo ma meno di Milano. Torino è più rilassata.",
    approccio_didattico: "Più pratica del PoliMi. Collaborazioni con Stellantis, Leonardo, Alenia.",
    borse_sussidi: "DSU Piemonte: borsa e alloggio con ISEE basso.",
    fit_score: 9,
    fit_note: "La triennale Computer Engineering in inglese è unica in Italia! Economica, buona qualità, bella città. Ottima base per poi andare all'estero per la magistrale.",
    punti_forza: ["BSc Computer Engineering in INGLESE (unico in Italia!)", "Economica (700-1.100€)", "206° mondo", "Torino = bella città"],
    punti_deboli: ["Pur buona, non è top europea", "Ancora intenso accademicamente"],
    url: "https://www.polito.it/",
  },

  {
    id: "unipd",
    nome: "Università di Padova (UniPD)",
    citta: "Padova",
    paese: "Italia",
    bandiera: "🇮🇹",
    lat: 45.4064,
    lng: 11.8774,
    qs2027: 204,
    qs2026: 185,
    punteggio_qs: 39.1,
    tasse_annue_eu: "Fino a ~2.500 €/anno (ISEE-based; esenzioni abbondanti)",
    affitto_mensile: "300–500 € (Padova economica — o pendolare da Vicenza in 30 min!)",
    costo_vita_totale: "~600–900 €/mese (o pendolari da Vicenza = costo quasi zero)",
    budget_rating: 5,
    lingua_triennale: "Italiano (quasi tutte). Alcune magistrali in inglese.",
    lingua_triennale_flag: "🇮🇹 ITALIANO",
    lauree_cs: "L Informatica (italiano), L Ingegneria Informatica (italiano), Fisica, Matematica",
    altre_ingegnerie: "Ingegneria Civile, Biomedica, Industriale (Meccanica/Elettrica), Magistrale Cybersecurity (inglese)",
    requisiti_ammissione: "TOLC-I (CISIA). No sbarramento, solo orientamento.",
    test_lingua: "Nessuno.",
    difficolta_ammissione: 2,
    qualita_vita: "Eccellente. Padova è a 30 minuti da Vicenza in treno! La città è bellissima, universitaria da 800 anni, economica.",
    soddisfazione_studenti: "Alta. UniPD è una delle università più antiche del mondo (fondata 1222).",
    rapporto_studio_vita: "Buono. Padova ha una vita studentesca vivacissima.",
    approccio_didattico: "Buona qualità teorica. Meno project-based del nord Europa.",
    borse_sussidi: "DSU Veneto: borsa + alloggio con ISEE basso. Puoi anche pendolare da Vicenza risparmiando tutto l'affitto!",
    fit_score: 8,
    fit_note: "A 30 minuti da casa tua! Budget quasi zero se pendolari. Opzione di ripiego perfetta o scelta consapevole: struttura storica, buona informatica, poi magistrale all'estero.",
    punti_forza: ["A 30 min da Vicenza!", "Quasi gratis pendolando", "204° mondo", "Città meravigliosa"],
    punti_deboli: ["Triennale in italiano", "Meno internazionale del nord Europa", "Approccio meno pratico"],
    url: "https://www.unipd.it/",
  },

  {
    id: "unibo",
    nome: "Università di Bologna (UniBo)",
    citta: "Bologna",
    paese: "Italia",
    bandiera: "🇮🇹",
    lat: 44.4949,
    lng: 11.3426,
    qs2027: 123,
    qs2026: 154,
    punteggio_qs: 52.9,
    tasse_annue_eu: "Fino a ~3.000 €/anno (ISEE-based)",
    affitto_mensile: "400–600 €",
    costo_vita_totale: "~800–1.200 €/mese",
    budget_rating: 3,
    lingua_triennale: "Italiano (quasi tutti i BSc). Alcune magistrali in inglese.",
    lingua_triennale_flag: "🇮🇹 ITALIANO",
    lauree_cs: "L Informatica (italiano), L Ingegneria Informatica (italiano), Intelligenza Artificiale (magistrale, inglese!)",
    altre_ingegnerie: "Meccanica, Civile, Elettronica, Biomedica, Aerospaziale (Forlì), Gestionale",
    requisiti_ammissione: "TOLC-I. Alcune lauree con sbarramento.",
    test_lingua: "Nessuno per triennali italiane.",
    difficolta_ammissione: 2,
    qualita_vita: "Eccellente. Bologna è la capitale gastronomica d'Italia (tortellini!) e una delle città universitarie più vivaci.",
    soddisfazione_studenti: "Altissima. Vita studentesca legendaria a Bologna.",
    rapporto_studio_vita: "Ottimo equilibrio. Bologna promuove la vita sociale studentesca.",
    approccio_didattico: "Buona qualità teorica. La magistrale in Artificial Intelligence è completamente in inglese ed eccellente.",
    borse_sussidi: "ER.GO (borsa Emilia-Romagna). DSU.",
    fit_score: 7,
    fit_note: "L'università più antica del mondo (fondata 1088). Bologna è fantastica come città. Top 123° mondo, ora. Se vuoi restare in Italia, è tra le migliori.",
    punti_forza: ["#123 mondo", "Bologna = vita studentesca top", "Magistrale AI in inglese eccellente"],
    punti_deboli: ["Triennale in italiano", "Bologna non economicissima"],
    url: "https://www.unibo.it/",
  },

  {
    id: "sapienza",
    nome: "Sapienza Università di Roma",
    citta: "Roma",
    paese: "Italia",
    bandiera: "🇮🇹",
    lat: 41.9029,
    lng: 12.5138,
    qs2027: 111,
    qs2026: 171,
    punteggio_qs: 55.1,
    tasse_annue_eu: "Fino a ~2.700 €/anno (ISEE-based; molte esenzioni)",
    affitto_mensile: "550–850 € (Roma cara per gli standard italiani)",
    costo_vita_totale: "~900–1.400 €/mese",
    budget_rating: 2,
    lingua_triennale: "Italiano. Alcune magistrali in inglese.",
    lingua_triennale_flag: "🇮🇹 ITALIANO",
    lauree_cs: "L Informatica, L Ingegneria Informatica, L Ingegneria Elettronica, Cybersecurity (magistrale inglese)",
    altre_ingegnerie: "Moltissime: Aerospaziale, Meccanica, Civile, Gestionale, Biomedica...",
    requisiti_ammissione: "TOLC-I. Alcune lauree con sbarramento numeri chiusi.",
    test_lingua: "Nessuno.",
    difficolta_ammissione: 2,
    qualita_vita: "Roma è Roma. La città più bella del mondo per storia e cultura. Ma caotica e cara.",
    soddisfazione_studenti: "Alta per la città, meno per l'organizzazione universitaria.",
    rapporto_studio_vita: "Buono per la vita, ma l'università è grande e può essere dispersiva.",
    approccio_didattico: "Qualità teorica buona. Grande università con molte risorse ma meno coordinata.",
    borse_sussidi: "DiSCo (borsa Lazio). DSU.",
    fit_score: 6,
    fit_note: "Roma è meravigliosa ma cara. Sapienza è grande (140.000 studenti!) e può essere dispersiva. Il ranking è salito molto (111°).",
    punti_forza: ["#111 mondo", "Roma = cultura e bellezza infinite", "Grande campus"],
    punti_deboli: ["Roma cara (900-1.400€)", "Università molto grande e dispersiva", "Triennale in italiano"],
    url: "https://www.uniroma1.it/",
  },

  {
    id: "unitn",
    nome: "Università di Trento",
    citta: "Trento",
    paese: "Italia",
    bandiera: "🇮🇹",
    lat: 46.0648,
    lng: 11.1274,
    qs2027: 438,
    qs2026: 450,
    punteggio_qs: 24.6,
    tasse_annue_eu: "Fino a ~2.000 €/anno (ISEE-based; molto favorevole)",
    affitto_mensile: "300–450 € (Trento economica e a misura di studente)",
    costo_vita_totale: "~600–900 €/mese",
    budget_rating: 5,
    lingua_triennale: "Italiano (triennale). Alcune magistrali in inglese.",
    lingua_triennale_flag: "🇮🇹 ITALIANO",
    lauree_cs: "L Informatica (italiano), L Ingegneria dell'Informazione e Organizzazione",
    altre_ingegnerie: "Industriale, Civile, Edile-Architettura",
    requisiti_ammissione: "TOLC-I. No sbarramento duro.",
    test_lingua: "Nessuno.",
    difficolta_ammissione: 1,
    qualita_vita: "Eccellente. Trento è una delle migliori città d'Italia per qualità della vita: Alpi, natura, sicura, pulita.",
    soddisfazione_studenti: "Alta. Università piccola e curata, rapporto docenti-studenti ottimo.",
    rapporto_studio_vita: "Ottimo. Trento valorizza l'equilibrio e le attività all'aperto.",
    approccio_didattico: "Buona qualità per le dimensioni. Ottima per chi vuole un ambiente più intimo rispetto ai mega-atenei.",
    borse_sussidi: "Opera Universitaria: borsa + alloggio con ISEE basso. Molto generosi a Trento.",
    fit_score: 7,
    fit_note: "Piccola ma eccellente per informatica, economicissima, bellissima città. Ottima opzione italiana per chi vuole meno caos di Milano.",
    punti_forza: ["Economicissima (600-900€/mese)", "Trento = città fantastica (montagna)", "Università a misura d'uomo", "438° QS ma ottima reputazione locale"],
    punti_deboli: ["Ranking 438°", "Triennale in italiano", "Piccola città (non per tutti)"],
    url: "https://www.unitn.it/",
  },

  // ─── PORTOGALLO ───────────────────────────────────────────────────────────
  {
    id: "ulisboa",
    nome: "Universidade de Lisboa (ULisboa) / IST",
    citta: "Lisbona",
    paese: "Portogallo",
    bandiera: "🇵🇹",
    lat: 38.7077,
    lng: -9.1365,
    qs2027: 237,
    qs2026: 262,
    punteggio_qs: 34.7,
    tasse_annue_eu: "~700–1.000 €/anno (IST – Instituto Superior Técnico)",
    affitto_mensile: "500–900 € (Lisbona in forte crescita, sempre più cara)",
    costo_vita_totale: "~900–1.400 €/mese",
    budget_rating: 2,
    lingua_triennale: "Portoghese (BSc IST). Alcune magistrali in inglese.",
    lingua_triennale_flag: "⚠️ PORTOGHESE",
    lauree_cs: "L.Sc. Engenharia Informática e de Computadores (portoghese), Computer Science",
    altre_ingegnerie: "Elettrica, Meccanica, Civile, Aerospaziale, Biomedica",
    requisiti_ammissione: "Esame nazionale portoghese o riconoscimento diploma EU.",
    test_lingua: "Portoghese B1 per iscriversi.",
    difficolta_ammissione: 3,
    qualita_vita: "Ottima. Lisbona è diventata una delle mete più trendy d'Europa. Surf, sole, cultura.",
    soddisfazione_studenti: "Alta. IST è il miglior politecnico portoghese.",
    rapporto_studio_vita: "Buono. Stile di vita mediterraneo.",
    approccio_didattico: "Buona qualità teorica. Ecosistema startup in forte crescita a Lisbona.",
    borse_sussidi: "Borse DSAS. Portogallo ha costi di vita in aumento.",
    fit_score: 5,
    fit_note: "Lisbona è bellissima ma la triennale è in portoghese e la città è sempre più cara. Interessante soprattutto per chi vuole imparare il portoghese.",
    punti_forza: ["Lisbona = stile di vita top", "Tasse basse", "Ecosistema startup crescente"],
    punti_deboli: ["Triennale in portoghese", "Lisbona cara per i suoi standard"],
    url: "https://tecnico.ulisboa.pt/en/",
  },

];

// ================================================================
// DATI LAVORO PART-TIME PER PAESE
// Fonti: Eurostat 2024, statistiche nazionali, media esperienze studenti
// "lavorare mentre si studia" è normalissimo in nord Europa
// ================================================================
const LAVORO_PAESE = {

  "Svizzera": {
    salario_minimo_ora: "~22–28 CHF/ora (~23–30 €/ora)",
    ore_studente_tipiche: "8–12 ore/settimana",
    guadagno_mensile_stima: "~750–1.400 €/mese",
    tipi_lavoro_comuni: "Barista, cameriere, assistente lab universitario (HiWi), rider, tutoraggio, call center",
    regole_eu: "Studenti EU: nessun limite di ore per legge in Svizzera. Reddito fino a ~25.000 CHF/anno è tassato alla fonte (~15%).",
    combinazione_borse: "Nessun sussidio automatico per stranieri EU. Il lavoro è spesso l'unico integratore.",
    bilancio_mensile: "Entrate: lavoro ~1.000 € + genitori ~700 € = ~1.700 €. Uscite: ~1.800–2.400 €. Fattibile ma stretto.",
    rating_lavoro: 5, // 1-5, salario relativo alle spese
    emoji: "🇨🇭",
    note_speciali: "Salari altissimi in assoluto, ma tutto costa tantissimo. Il potere d'acquisto reale è simile alla Finlandia.",
  },

  "Germania": {
    salario_minimo_ora: "~12,41 €/ora (minimo legale 2024, spesso 14–16 € per studenti)",
    ore_studente_tipiche: "10–15 ore/settimana (max 20 ore durante semestre senza perdere status)",
    guadagno_mensile_stima: "~500–800 €/mese a 12 ore/settimana",
    tipi_lavoro_comuni: "Studentenjob in bar/ristoranti, HiWi (assistente ricerca universitaria ~15 €/ora), corriere, data entry, tutoraggio",
    regole_eu: "Studenti EU: lavoro libero. Mini-job fino a 538 €/mese: esenzione totale da tasse e contributi. Oltre: tassazione normale.",
    combinazione_borse: "BAföG (sussidio statale tedesco ~861 €/mese) tecnicamente disponibile per studenti EU ma complesso da ottenere. Il mini-job è la combo più comoda.",
    bilancio_mensile: "Lavoro mini-job ~538 € (tax-free) + genitori ~700 € = ~1.238 €. A Monaco quasi giusto, a Darmstadt/Aachen ok.",
    rating_lavoro: 4,
    emoji: "🇩🇪",
    note_speciali: "Il contratto HiWi (Hilfswissenschaftler) nelle università tedesche è molto comune: ~10 ore/settimana come assistente di ricerca, ~15 €/ora, ottimo per il CV.",
  },

  "Paesi Bassi": {
    salario_minimo_ora: "~6,70–8,50 €/ora per 18–19 anni (Minimumjeugdloon); ~13,27 €/ora per 21+ anni",
    ore_studente_tipiche: "10–16 ore/settimana",
    guadagno_mensile_stima: "~350–500 €/mese a 18–19 anni (~650–800 €/mese dai 21 anni o in TA universitario)",
    tipi_lavoro_comuni: "Supermarkt (Albert Heijn, Jumbo), horeca, bike messenger, Teaching Assistant/Tutor in uni (~12–14 €/h anche a 18 anni)",
    regole_eu: "Studenti EU: lavoro libero. In Olanda esiste il 'Minimumjeugdloon' (salario minimo ridotto per fascia 18-20 anni: 18 anni = 50%, 19 anni = 60%, 20 anni = 80%).",
    combinazione_borse: "DUO Loan: prestito studentesco olandese ~1.100 €/mese (da restituire in 35 anni a tasso ~0%). Con lavoro: DUO + lavoro + genitori = budget solido.",
    bilancio_mensile: "Lavoro (18-19 anni) ~400 € + DUO loan ~600 € + genitori ~600 € = ~1.600 €. Più che sufficiente per vita e affitto a Delft/Eindhoven.",
    rating_lavoro: 3,
    emoji: "🇳🇱",
    note_speciali: "⚠️ NOTA PER GIOVANNI (18-19 ANNI): Nei supermercati/bar olandesi a 18 anni la paga base è ~6,70€/h. TRUCCO: Punta ai ruoli universitari (Teaching Assistant / Lab Demo / Student Tutor alla TU Delft o TU/e) che pagano la tariffa piena (~12-14€/h) indipendentemente dall'età! Oppure guarda alla Danimarca/Germania dove a 18 anni si prende la paga intera adulti.",
  },

  "Danimarca": {
    salario_minimo_ora: "~150–200 DKK/ora (~20–27 €/ora!) tramite accordi collettivi",
    ore_studente_tipiche: "10–15 ore/settimana",
    guadagno_mensile_stima: "~800–1.300 €/mese (il più alto in Europa per studenti!)",
    tipi_lavoro_comuni: "Supermarked (Netto, Lidl, Rema), café, bar, student assistant universitario (~200 DKK/ora), delivery",
    regole_eu: "Studenti EU: lavoro libero. Tassazione ~38% ma le deduzioni annullano molto per redditi bassi.",
    combinazione_borse: "SU (Statens Uddannelsesstøtte): ~900–1.100 DKK/mese (~120-145 €) base, MA se lavori ≥10 ore/settimana con contratto valido ottieni ~6.200 DKK/mese (~830 €) A FONDO PERDUTO. Non è un prestito!",
    bilancio_mensile: "💰 SCENARIO OTTIMALE: Lavoro ~1.000 € + SU ~830 € + genitori ~600 € = ~2.430 €. Copenaghen costa ~1.200-1.400 €. Si vive benissimo e si risparmia!",
    rating_lavoro: 5,
    emoji: "🇩🇰",
    note_speciali: "⭐ LA MIGLIORE COMBO EUROPA: Il SU danese è un sussidio a fondo perduto dello stato. Con 10 ore di lavoro a settimana (ad es. barista) + SU + un contributo minimo dai genitori, potresti avere più soldi tu in Danimarca che in Italia senza lavorare!",
  },

  "Svezia": {
    salario_minimo_ora: "~150–180 SEK/ora (~13–17 €/ora) tramite accordi collettivi per settore",
    ore_studente_tipiche: "10–15 ore/settimana",
    guadagno_mensile_stima: "~520–900 €/mese",
    tipi_lavoro_comuni: "ICA/Coop (supermercati), café, ristoranti, amanuens (assistente ricerca KTH, ~170 SEK/ora)",
    regole_eu: "Studenti EU: lavoro libero. Tax-free fino a ~20.000 SEK/anno (~1.900 €). Sopra: aliquota ~30%.",
    combinazione_borse: "CSN: prestito studentesco svedese ~3.000 SEK/settimana durante il semestre (~1.400 €/mese, da restituire). Diversamente dal SU danese, non è un sussidio. Molti studenti preferiscono lavorare.",
    bilancio_mensile: "Lavoro ~700 € + genitori ~700 € = ~1.400 €. Stoccolma costa ~1.000-1.300 €. Fattibile senza CSN.",
    rating_lavoro: 3,
    emoji: "🇸🇪",
    note_speciali: "Il lavoro di amanuens (assistente di ricerca o didattica in università svedese) è molto accessibile e paga bene. Ottimo anche per il CV.",
  },

  "Finlandia": {
    salario_minimo_ora: "~12–15 €/ora (no minimo legale, ma accordi collettivi per settore)",
    ore_studente_tipiche: "10–15 ore/settimana",
    guadagno_mensile_stima: "~480–750 €/mese",
    tipi_lavoro_comuni: "S-market/K-market, café, IT assistant (ottimo per studenti informatica), tutoraggio",
    regole_eu: "Studenti EU: lavoro libero. Reddito sotto ~17.600 €/anno esentasse (con deduzioni).",
    combinazione_borse: "Opintotuki: ~300 €/mese (sussidio diretto, no rimborso) + Housing supplement ~200 €/mese per chi non vive in casa studenti. Puoi lavorare fino a ~12.500 €/anno senza perdere l'Opintotuki.",
    bilancio_mensile: "Lavoro ~600 € + Opintotuki ~300 € + Housing ~150 € + genitori ~400 € = ~1.450 €. Aalto/Espoo: ~900-1.100 €. SURPLUS mensile ~350-500 €!",
    rating_lavoro: 4,
    emoji: "🇫🇮",
    note_speciali: "🍽️ Le mense universitarie finlandesi (Kela-tuettu): pasto completo a 2,95 € per studenti. Se mangi lì 2 volte al giorno: ~€180/mese in cibo. Risparmio enorme. Aalto ha 5 mense nel campus.",
  },

  "Irlanda": {
    salario_minimo_ora: "~13,50 €/ora (2024, in aumento ogni anno)",
    ore_studente_tipiche: "12–20 ore/settimana",
    guadagno_mensile_stima: "~650–1.000 €/mese",
    tipi_lavoro_comuni: "Pub (bartender), retail (Dunnes, Tesco), caffetterie, call center (molti HQ europei a Dublino), tech support",
    regole_eu: "Studenti EU: lavoro libero. Nessun limite ore. Esenzione tax fino a ~20.000 €/anno.",
    combinazione_borse: "SUSI Grant: fino a ~6.000 €/anno per studenti in difficoltà economica. Non automatico.",
    bilancio_mensile: "Lavoro ~800 € + genitori ~700 € = ~1.500 €. Dublino costa ~1.200-1.800 €. Stretto.",
    rating_lavoro: 3,
    emoji: "🇮🇪",
    note_speciali: "Dublino è la capitale europea tech (Google, Meta, Apple, Microsoft). Anche con un lavoro generico in un pub vicino a un campus, fai networking con studenti che poi lavorano nelle big tech.",
  },

  "Belgio": {
    salario_minimo_ora: "~12,50 €/ora (minimo legale 2024)",
    ore_studente_tipiche: "10–15 ore/settimana",
    guadagno_mensile_stima: "~500–750 €/mese",
    tipi_lavoro_comuni: "Supermercati (Delhaize, Colruyt), horeca, studentenjob nelle università, call center",
    regole_eu: "Studenti EU: lavoro libero. 'Studentenarbeid': contratto speciale studente, contributi ridotti, max 600 ore/anno.",
    combinazione_borse: "Borse KU Leuven per studenti meritevoli. Tasse già basse (960 €/anno).",
    bilancio_mensile: "Lavoro ~600 € + genitori ~600 € = ~1.200 €. KU Leuven/Leuven: ~900-1.200 €. Giusto.",
    rating_lavoro: 3,
    emoji: "🇧🇪",
    note_speciali: "Il contratto studentesk belga (studentenarbeid) è molto flessibile e le ore non conteggiate ai fini fiscali fino a 600/anno.",
  },

  "Norvegia": {
    salario_minimo_ora: "~200–220 NOK/ora (~17–19 €/ora) — no minimo legale ma contratti collettivi elevatissimi",
    ore_studente_tipiche: "10–15 ore/settimana",
    guadagno_mensile_stima: "~680–1.100 €/mese",
    tipi_lavoro_comuni: "REMA 1000 / Kiwi (supermercati), café, studentassistent universitario (~230 NOK/ora), IT support",
    regole_eu: "Studenti EU: lavoro libero. Norvegia non è UE ma è SEE: studenti EU lavorano liberamente.",
    combinazione_borse: "LÅNEKASSEN: fino a ~1.100 €/mese (mix borsa + prestito, quota borsa non va restituita se si laurea in tempo). Questa è la cosa più interessante della Norvegia.",
    bilancio_mensile: "💰 Lavoro ~850 € + LÅNEKASSEN ~1.100 € + genitori minimo = ~1.950 €. Trondheim: ~900-1.200 €. OTTIMO surplus!",
    rating_lavoro: 5,
    emoji: "🇳🇴",
    note_speciali: "⭐ LÅNEKASSEN + lavoro = probabilmente la combo finanziariamente più favorevole in Europa. Se ti laurei nei tempi, una parte del prestito diventa sussidio (non va restituita). Trondheim è molto più economica di Oslo.",
  },

  "Austria": {
    salario_minimo_ora: "~12–14 €/ora (varia per settore, minimo legale ~12 €)",
    ore_studente_tipiche: "10–15 ore/settimana",
    guadagno_mensile_stima: "~480–700 €/mese",
    tipi_lavoro_comuni: "Supermercati (Billa, Hofer), caffè viennesi, Hiwi universitari (~15 €/ora), turismo",
    regole_eu: "Studenti EU: lavoro libero. Esenzione contributi per studenti part-time.",
    combinazione_borse: "Stipendio statale austriaco (Studienbeihilfe): fino a ~800 €/mese per studenti in difficoltà. Richiede residenza.",
    bilancio_mensile: "Lavoro ~580 € + genitori ~600 € = ~1.180 €. Vienna: ~900-1.200 €. Fattibile.",
    rating_lavoro: 3,
    emoji: "🇦🇹",
    note_speciali: "Vienna ha una forte tradizione di studenti che lavorano nei caffè storici o nei musei. Lavori culturali ben pagati e ottimi per il networking.",
  },

  "Italia": {
    salario_minimo_ora: "~7–9 €/ora (no minimo legale, molto variabile per settore)",
    ore_studente_tipiche: "8–15 ore/settimana",
    guadagno_mensile_stima: "~250–500 €/mese",
    tipi_lavoro_comuni: "Bar/caffè, ristorazione, supermarket, tutoraggio scolastico (10-15€/ora), collaborazioni 150 ore universitarie",
    regole_eu: "Studenti italiani: nessun problema. 'Collaborazioni 150 ore': contratto speciale con la propria università, ~7-8 €/ora per supporto a biblioteche, lab, amministrazione.",
    combinazione_borse: "DSU (Diritto allo Studio Universitario): borsa completa se ISEE basso (fino a ~14.000 €, include vitto+alloggio). Non compatibile con redditi elevati.",
    bilancio_mensile: "Lavoro ~350 € + DSU/borsa (se ISEE ok) ~500 € + genitori ~500 € = ~1.350 €. PoliTo: ~800-1.100 €. Funziona.",
    rating_lavoro: 2,
    emoji: "🇮🇹",
    note_speciali: "In Italia i salari part-time sono i più bassi d'Europa. Tuttavia le 'collaborazioni 150 ore' con la propria università sono una ottima opportunità: orari flessibili, vicino allo studio, riconosciute nel CV.",
  },

  "Portogallo": {
    salario_minimo_ora: "~5,80 €/ora (salario minimo portoghese 2024 ~1.020€/mese ÷ 176 ore)",
    ore_studente_tipiche: "10–15 ore/settimana",
    guadagno_mensile_stima: "~230–380 €/mese",
    tipi_lavoro_comuni: "Ristorazione, retail, turismo, call center (Lisbona ha molti HQ europei)",
    regole_eu: "Studenti EU: lavoro libero. Tassazione bassa (IRS ridotto per studenti).",
    combinazione_borse: "DSAS (borse universitarie portoghesi). Lisbona ha però un costo vita in forte aumento.",
    bilancio_mensile: "Lavoro ~300 € + genitori ~700 € = ~1.000 €. Lisbona: ~1.000-1.400 €. Difficile.",
    rating_lavoro: 1,
    emoji: "🇵🇹",
    note_speciali: "Lisbona ha call center europei (Google, Amazon, Teleperformance) che spesso cercano italofoni. Stipendi migliori del minimo locale (~1.200-1.400€/mese fisso) ma sono lavori full-time.",
  },
};

// Metadati di supporto per i filtri
const PAESI = [...new Set(UNIVERSITIES.map(u => u.paese))].sort();
const MAX_QS = Math.max(...UNIVERSITIES.map(u => u.qs2027));
const MIN_QS = Math.min(...UNIVERSITIES.map(u => u.qs2027));

