# -*- coding: utf-8 -*-
EXTRA_UNIS = [
    {
        "id": "kit",
        "nome": "Karlsruhe Institute of Technology (KIT)",
        "citta": "Karlsruhe",
        "paese": "Germania",
        "bandiera": "🇩🇪",
        "lat": 49.0069,
        "lng": 8.4037,
        "qs2027": 110,
        "qs2026": 102,
        "punteggio_qs": 61.5,
        "tasse_annue_eu": "Rette 0 € per corsi pubblici / Carl Benz School ha rette private",
        "affitto_mensile": "350–550 €/mese",
        "costo_vita_totale": "~850–1.150 €/mese",
        "budget_mensile_val": 1000,
        "budget_rating": 4,
        "ambiti": ["cs", "ce", "robotics", "embedded", "other_eng"],
        "lauree_triennali": [
            {
                "nome": "B.Sc. Mechanical Engineering / Mechatronics (Carl Benz School - 100% in Inglese)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["robotics", "embedded", "other_eng"],
                "focus": "Meccatronica, controllo dei sistemi, robotica industriale e sensoristica avanzata."
            }
        ],
        "lingua_triennale": "Inglese (Carl Benz School)",
        "has_english_bachelor": True,
        "has_italian_bachelor": False,
        "ammissione": {
            "test_richiesto": "Valutazione diploma, SAT e colloquio motivazionale",
            "soglia_indicativa": "Diploma e forte motivazione tecnica",
            "scadenze": "30 Aprile",
            "requisiti_lingua": "IELTS 6.5 o Cambridge",
            "procedura": "Domanda tramite Carl Benz School portal",
            "difficolta": 3
        },
        "approccio_didattico": "Uno dei centri di ricerca tecnologica più importanti di Germania (parte della Helmholtz Association).",
        "qualita_vita": "Città soleggiata del Baden-Württemberg, ciclabile, verde.",
        "soddisfazione_studenti": "9.0/10.",
        "rapporto_studio_vita": "Rigoroso ma ricco di soddisfazioni.",
        "borse_sussidi": "Contratti HiWi nei laboratori (~15 €/ora).",
        "fit_score": 9.1,
        "fit_note": "Ateneo leggendario (#110 al mondo) per ingegneria e informatica in Germania. Carl Benz School offre un programma in inglese in meccatronica.",
        "punti_forza": ["#110 al mondo QS", "Top per meccatronica e robotica", "Centro di ricerca Helmholtz"],
        "punti_deboli": ["Carl Benz School applica contributi extra"],
        "url": "https://www.kit.edu"
    },
    {
        "id": "constructor",
        "nome": "Constructor University (ex Jacobs University)",
        "citta": "Brema",
        "paese": "Germania",
        "bandiera": "🇩🇪",
        "lat": 53.1670,
        "lng": 8.6530,
        "qs2027": 550,
        "qs2026": 550,
        "punteggio_qs": 30.5,
        "tasse_annue_eu": "Borse di studio fino al 100% disponibili in base al merito",
        "affitto_mensile": "Incluso nei pacchetti campus residenziale all-inclusive",
        "costo_vita_totale": "~900–1.200 €/mese",
        "budget_mensile_val": 1050,
        "budget_rating": 4,
        "ambiti": ["cs", "ai", "robotics", "embedded"],
        "lauree_triennali": [
            {
                "nome": "B.Sc. Computer Science (100% IN INGLESE)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["cs", "ai"],
                "focus": "Algoritmi, intelligenza artificiale, architetture cloud e sistemi distribuiti."
            },
            {
                "nome": "B.Sc. Robotics and Intelligent Systems (100% IN INGLESE)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["robotics", "ai", "embedded"],
                "focus": "Robotica autonoma, percezione, attuatori, machine learning per sistemi fisici."
            }
        ],
        "lingua_triennale": "Inglese (100% in lingua)",
        "has_english_bachelor": True,
        "has_italian_bachelor": False,
        "ammissione": {
            "test_richiesto": "Domanda su Common App o portale ateneo con dossier e colloquio",
            "soglia_indicativa": "Diploma e lettera motivazionale",
            "scadenze": "1° Giugno",
            "requisiti_lingua": "Inglese B2/C1",
            "procedura": "Domanda online con valutazione borse di merito",
            "difficolta": 2
        },
        "approccio_didattico": "Vero campus in stile anglosassone nel nord della Germania. Oltre 110 nazionalità rappresentate.",
        "qualita_vita": "Campus residenziale autonomo a Brema.",
        "soddisfazione_studenti": "9.2/10.",
        "rapporto_studio_vita": "Comunità internazionale molto coesa.",
        "borse_sussidi": "Borse di studio di merito ampie per studenti europei meritevoli.",
        "fit_score": 9.2,
        "fit_note": "Unico vero campus internazionale in lingua inglese in Germania con un corso specifico in 'Robotics and Intelligent Systems'.",
        "punti_forza": ["BSc in Robotics and Intelligent Systems 100% in inglese", "Vero campus residenziale internazionale", "Borse di merito disponibili"],
        "punti_deboli": ["Tariffe private se non si ottiene la borsa"],
        "url": "https://constructor.university"
    },
    {
        "id": "fau",
        "nome": "FAU Erlangen-Nürnberg",
        "citta": "Erlangen",
        "paese": "Germania",
        "bandiera": "🇩🇪",
        "lat": 49.5978,
        "lng": 11.0038,
        "qs2027": 229,
        "qs2026": 229,
        "punteggio_qs": 42.5,
        "tasse_annue_eu": "~140 €/semestre (Rette universitarie 0 €)",
        "affitto_mensile": "350–520 €/mese",
        "costo_vita_totale": "~800–1.050 €/mese",
        "budget_mensile_val": 900,
        "budget_rating": 4,
        "ambiti": ["ai", "cs", "embedded", "other_eng"],
        "lauree_triennali": [
            {
                "nome": "B.Sc. Autonomy Technologies (100% IN INGLESE)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["ai", "embedded", "robotics"],
                "focus": "Guida autonoma, robotica, machine learning per sistemi embedded, sensori LiDAR e computer vision."
            },
            {
                "nome": "B.Sc. Clean Energy Processes (100% in Inglese)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["other_eng"],
                "focus": "Ingegneria dei processi energetici sostenibili e idrogeno."
            }
        ],
        "lingua_triennale": "Inglese (Autonomy Technologies)",
        "has_english_bachelor": True,
        "has_italian_bachelor": False,
        "ammissione": {
            "test_richiesto": "Valutazione diploma e requisiti matematici",
            "soglia_indicativa": "Diploma di maturità tecnica",
            "scadenze": "15 Luglio",
            "requisiti_lingua": "Inglese B2",
            "procedura": "Domanda su Campo portal FAU",
            "difficolta": 2
        },
        "approccio_didattico": "FAU è al 2° posto in Germania per innovazione. Sede del Fraunhofer IIS (dove è stato inventato l'MP3) e partner di Siemens.",
        "qualita_vita": "Erlangen è la capitale tedesca della bicicletta, sede centrale globale di Siemens e polo medico-tecnologico.",
        "soddisfazione_studenti": "9.1/10.",
        "rapporto_studio_vita": "Città tranquilla, sicura e piena di parchi.",
        "borse_sussidi": "Rette 0 € per cittadini UE.",
        "fit_score": 9.5,
        "fit_note": "⭐ CORSO 'AUTONOMY TECHNOLOGIES' IN INGLESE: focalizzato su veicoli autonomi, computer vision e sistemi intelligenti. Vicina a Norimberga, rette 0€ e costi abbordabili!",
        "punti_forza": ["B.Sc. Autonomy Technologies 100% in inglese", "Rette universitarie 0 €", "Quartier generale Siemens a Erlangen", "A sole 5 ore di treno da Vicenza"],
        "punti_deboli": ["Scadenza il 15 Luglio"],
        "url": "https://www.fau.eu"
    },
    {
        "id": "tu_wien",
        "nome": "TU Wien (Vienna University of Technology)",
        "citta": "Vienna",
        "paese": "Austria",
        "bandiera": "🇦🇹",
        "lat": 48.1989,
        "lng": 16.3699,
        "qs2027": 190,
        "qs2026": 190,
        "punteggio_qs": 47.8,
        "tasse_annue_eu": "0 € tasse (~22 €/semestre quota studenti ÖH per cittadini UE)",
        "affitto_mensile": "380–580 €/mese (Vienna ha il miglior sistema di edilizia residenziale al mondo!)",
        "costo_vita_totale": "~850–1.150 €/mese",
        "budget_mensile_val": 1000,
        "budget_rating": 4,
        "ambiti": ["cs", "ce", "robotics", "embedded", "other_eng"],
        "lauree_triennali": [
            {
                "nome": "B.Sc. Technische Informatik / Computer Engineering (moduli bilingue)",
                "lingua": "🇬🇧 Inglese / Tedesco",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["ce", "embedded", "cs"],
                "focus": "Architetture hardware, sistemi embedded, calcolo ad alte prestazioni, robotica."
            },
            {
                "nome": "B.Sc. Maschinenbau / Elektrotechnik",
                "lingua": "🇬🇧 Inglese / Tedesco",
                "lingua_code": "it",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["other_eng", "robotics"],
                "focus": "Ingegneria meccanica ed elettrotecnica nel cuore dell'Austria."
            }
        ],
        "lingua_triennale": "Inglese / Tedesco (molti corsi magistrali 100% in inglese)",
        "has_english_bachelor": True,
        "has_italian_bachelor": False,
        "ammissione": {
            "test_richiesto": "Reihungstest per Informatik (test attitudinale online)",
            "soglia_indicativa": "Superamento del test attitudinale",
            "scadenze": "Luglio / Agosto",
            "requisiti_lingua": "Inglese B2 / Tedesco A2-B1",
            "procedura": "Registrazione online su TISS TU Wien",
            "difficolta": 2
        },
        "approccio_didattico": "Il più grande polo tecnologico dell'Austria. Rigore matematico e laboratori di microelettronica avanzati.",
        "qualita_vita": "Vienna è eletta da anni la città con la migliore qualità della vita al mondo (The Economist Global Liveability Index). Trasporti a 1 €/giorno.",
        "soddisfazione_studenti": "9.3/10.",
        "rapporto_studio_vita": "Insuperabile: musei, caffè storici, concerti e parchi infiniti.",
        "borse_sussidi": "Rette universitarie 0 € per studenti UE.",
        "fit_score": 9.1,
        "fit_note": "A poche ore di treno o Nightjet notturno diretto da Vicenza/Venezia. Vienna è la città più vivibile del mondo e le rette sono gratuite.",
        "punti_forza": ["Città con la migliore qualità della vita al mondo", "Rette universitarie = 0 €", "Treno Nightjet notturno diretto da Vicenza/Venezia a Vienna", "#190 al mondo QS"],
        "punti_deboli": ["Triennale con moduli tedeschi"],
        "url": "https://www.tuwien.at/en"
    },
    {
        "id": "ucd",
        "nome": "University College Dublin (UCD)",
        "citta": "Dublino",
        "paese": "Irlanda",
        "bandiera": "🇮🇪",
        "lat": 53.3068,
        "lng": -6.2206,
        "qs2027": 100,
        "qs2026": 126,
        "punteggio_qs": 64.0,
        "tasse_annue_eu": "~3.000 €/anno (contributo studentesco EU)",
        "affitto_mensile": "750–1.100 €/mese",
        "costo_vita_totale": "~1.300–1.750 €/mese",
        "budget_mensile_val": 1450,
        "budget_rating": 1,
        "ambiti": ["cs", "ai", "other_eng"],
        "lauree_triennali": [
            {
                "nome": "B.Sc. Computer Science (100% IN INGLESE - Belfield Campus)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "4 anni (BSc Honours)",
                "ambiti": ["cs", "ai"],
                "focus": "Grande campus a Belfield. Data science, software engineering, intelligenza artificiale e reti."
            }
        ],
        "lingua_triennale": "Inglese",
        "has_english_bachelor": True,
        "has_italian_bachelor": False,
        "ammissione": {
            "test_richiesto": "CAO.ie",
            "soglia_indicativa": "Punteggio CAO elevato",
            "scadenze": "1° Febbraio",
            "requisiti_lingua": "IELTS 6.5 o Cambridge",
            "procedura": "Domanda su cao.ie",
            "difficolta": 3
        },
        "approccio_didattico": "Il più grande campus universitario d'Irlanda, moderno, immerso nel verde.",
        "qualita_vita": "Dublino (ambiente giovanile e internazionale).",
        "soddisfazione_studenti": "9.0/10.",
        "rapporto_studio_vita": "Molto piacevole.",
        "borse_sussidi": "Part-time retribuito.",
        "fit_score": 8.1,
        "fit_note": "Ateneo top 100 mondiale con un campus moderno a Belfield. Ottima didattica, ma costo degli alloggi a Dublino elevato.",
        "punti_forza": ["Top 100 al mondo QS", "Grande campus moderno a Belfield", "Ecosistema tech irlandese"],
        "punti_deboli": ["Costi abitativi a Dublino", "Percorso di 4 anni"],
        "url": "https://www.ucd.ie"
    },
    {
        "id": "dcu",
        "nome": "Dublin City University (DCU)",
        "citta": "Dublino",
        "paese": "Irlanda",
        "bandiera": "🇮🇪",
        "lat": 53.3858,
        "lng": -6.2573,
        "qs2027": 436,
        "qs2026": 436,
        "punteggio_qs": 31.9,
        "tasse_annue_eu": "~3.000 €/anno",
        "affitto_mensile": "650–950 €/mese (campus a Glasnevin nel nord di Dublino, un po' meno caro del centro)",
        "costo_vita_totale": "~1.150–1.550 €/mese",
        "budget_mensile_val": 1300,
        "budget_rating": 2,
        "ambiti": ["cs", "ai", "ce", "embedded"],
        "lauree_triennali": [
            {
                "nome": "B.Sc. Computer Applications (100% IN INGLESE)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "4 anni (include 6 mesi di tirocinio INTRA retribuito in azienda!)",
                "ambiti": ["cs", "ai"],
                "focus": "Uno dei corsi di software più apprezzati dai datori di lavoro d'Irlanda. Tirocinio aziendale retribuito obbligatorio (INTRA)."
            },
            {
                "nome": "B.Sc. Electronic and Computer Engineering",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "4 anni",
                "ambiti": ["ce", "embedded"],
                "focus": "Sistemi embedded, IoT, telecomunicazioni e architettura hardware."
            }
        ],
        "lingua_triennale": "Inglese",
        "has_english_bachelor": True,
        "has_italian_bachelor": False,
        "ammissione": {
            "test_richiesto": "CAO.ie",
            "soglia_indicativa": "Punti CAO",
            "scadenze": "1° Febbraio",
            "requisiti_lingua": "Inglese B2/C1",
            "procedura": "Domanda su cao.ie",
            "difficolta": 2
        },
        "approccio_didattico": "L'ateneo dell'innovazione in Irlanda: pioniere dei tirocini curriculari retribuiti (programma INTRA).",
        "qualita_vita": "Campus a Glasnevin, vicino all'aeroporto di Dublino.",
        "soddisfazione_studenti": "9.1/10 per l'occupabilità.",
        "rapporto_studio_vita": "Pratico ed orientato all'inserimento lavorativo.",
        "borse_sussidi": "Tirocinio INTRA retribuito.",
        "fit_score": 8.4,
        "fit_note": "Ateneo tecnologico moderno a Dublino con un semestre di tirocinio aziendale retribuito (INTRA) garantito durante il corso.",
        "punti_forza": ["Tirocinio retribuito obbligatorio INTRA", "Orientata alla pratica del software e dell'embedded", "Tasso di occupazione altissimo"],
        "punti_deboli": ["Costi di Dublino"],
        "url": "https://www.dcu.ie"
    },
    {
        "id": "vut_brno",
        "nome": "Brno University of Technology (VUT)",
        "citta": "Brno",
        "paese": "Repubblica Ceca",
        "bandiera": "🇨🇿",
        "lat": 49.2238,
        "lng": 16.5744,
        "qs2027": 590,
        "qs2026": 610,
        "punteggio_qs": 29.2,
        "tasse_annue_eu": "~2.000–2.500 €/anno per i corsi in inglese",
        "affitto_mensile": "130–220 €/mese (dormitori studenteschi Pod Palackého vrchem tra i più grandi d'Europa!)",
        "costo_vita_totale": "~500–700 €/mese TUTTO INCLUSO",
        "budget_mensile_val": 600,
        "budget_rating": 5,
        "ambiti": ["cs", "ce", "embedded", "robotics", "cyber"],
        "lauree_triennali": [
            {
                "nome": "B.Sc. Information Technology (100% IN INGLESE - Faculty of IT FIT)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["cs", "ce", "cyber", "embedded"],
                "focus": "Facoltà FIT (Faculty of Information Technology) a Božetěchova: situata in un ex monastero con laboratori ultramoderni di supercomputing, cybersecurity, robotica e sistemi embedded."
            }
        ],
        "lingua_triennale": "Inglese",
        "has_english_bachelor": True,
        "has_italian_bachelor": False,
        "ammissione": {
            "test_richiesto": "Test online di matematica o valutazione voti diploma",
            "soglia_indicativa": "Diploma tecnico",
            "scadenze": "31 Marzo",
            "requisiti_lingua": "Inglese B2",
            "procedura": "Domanda su vut.cz/en",
            "difficolta": 2
        },
        "approccio_didattico": "Brno è definita la 'Silicon Valley della Repubblica Ceca': vi hanno sede centri di ricerca di Red Hat, IBM, Honeywell, F-Secure. Didattica con laboratori hardware e software avanzati.",
        "qualita_vita": "Città studentesca per eccellenza: 1 abitante su 5 è studente universitario. Costo della vita bassissimo.",
        "soddisfazione_studenti": "9.4/10. Atmosfera giovanile ovunque.",
        "rapporto_studio_vita": "Eccezionale: dormitori a 140€/mese con birra a 1,50€ e cene complete a 5€.",
        "borse_sussidi": "Alloggi universitari quasi gratuiti.",
        "fit_score": 9.5,
        "fit_note": "Brno è il cuore tech della Repubblica Ceca (sede di Red Hat e centri di cybersecurity). Bachelor in IT 100% in inglese, dormitori a 140€/mese e vita da re con il tuo budget genitori di 600-800€!",
        "punti_forza": ["Silicon Valley ceca (Red Hat, Honeywell, IBM)", "B.Sc. Information Technology 100% in inglese", "Dormitori a 130-180€/mese", "Budget 600-800€ copre ogni singola spesa"],
        "punti_deboli": ["Brno non ha voli diretti da Venezia (si atterra a Vienna e si prendono 1h30 di treno o bus)"],
        "url": "https://www.vut.cz/en"
    },
    {
        "id": "pwr_wroclaw",
        "nome": "Wrocław University of Science and Technology (Politechnika Wrocławska)",
        "citta": "Breslavia (Wrocław)",
        "paese": "Polonia",
        "bandiera": "🇵🇱",
        "lat": 51.1079,
        "lng": 17.0617,
        "qs2027": 650,
        "qs2026": 650,
        "punteggio_qs": 28.5,
        "tasse_annue_eu": "~2.500 €/anno",
        "affitto_mensile": "130–250 €/mese",
        "costo_vita_totale": "~500–700 €/mese",
        "budget_mensile_val": 600,
        "budget_rating": 5,
        "ambiti": ["cs", "ai", "cyber", "ce"],
        "lauree_triennali": [
            {
                "nome": "B.Sc. Applied Computer Science (100% IN INGLESE)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3.5 anni (210 ECTS)",
                "ambiti": ["cs", "ai", "cyber"],
                "focus": "Intelligenza artificiale, sicurezza dei sistemi software, reti di telecomunicazioni, sviluppo cloud."
            }
        ],
        "lingua_triennale": "Inglese",
        "has_english_bachelor": True,
        "has_italian_bachelor": False,
        "ammissione": {
            "test_richiesto": "Valutazione voti diploma",
            "soglia_indicativa": "Diploma tecnico",
            "scadenze": "Maggio / Giugno",
            "requisiti_lingua": "Inglese B2",
            "procedura": "Domanda su admission.pwr.edu.pl",
            "difficolta": 2
        },
        "approccio_didattico": "Politecnico eccellente con forti team studenteschi nei rover marziani e satelliti.",
        "qualita_vita": "Breslavia è considerata la città più bella e vivace della Polonia, con centinaia di canali e ponti.",
        "soddisfazione_studenti": "9.3/10.",
        "rapporto_studio_vita": "Basso costo, alta qualità.",
        "borse_sussidi": "Tassazione 0% under 26 in Polonia.",
        "fit_score": 9.1,
        "fit_note": "Ateneo tecnologico solido in una città stupenda. B.Sc. in Applied Computer Science in inglese, dormitori a 140€ e budget 600-800€ ampiamente coprente.",
        "punti_forza": ["Città splendida e giovanissima", "B.Sc. Applied CS 100% in inglese", "Costi irrisori (dormitori a 130-200€)"],
        "punti_deboli": ["Corso da 3.5 anni"],
        "url": "https://pwr.edu.pl/en"
    }
]
