# -*- coding: utf-8 -*-
ITALIAN_UNIS = [
    {
        "id": "unipd",
        "nome": "Università di Padova (UniPD)",
        "citta": "Padova",
        "paese": "Italia",
        "bandiera": "🇮🇹",
        "lat": 45.4064,
        "lng": 11.8768,
        "qs2027": 219,
        "qs2026": 219,
        "punteggio_qs": 43.1,
        "tasse_annue_eu": "Fino a ~2.600 € (No-tax area totale sotto 24.000 € ISEE)",
        "affitto_mensile": "350–500 € (singola) / 0 € se vivi a Vicenza con i tuoi",
        "costo_vita_totale": "~500–750 €/mese (o ~100–150 € per treno se pendolare)",
        "budget_mensile_val": 650,
        "budget_rating": 5,
        "ambiti": ["cs", "ce", "ai", "embedded", "other_eng"],
        "lauree_triennali": [
            {
                "nome": "B.Sc. Information Engineering",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 CFU)",
                "ambiti": ["ce", "embedded", "cs"],
                "focus": "Interamente in inglese. Copre computer engineering, telecomunicazioni, elettronica e sistemi software."
            },
            {
                "nome": "Laurea in Informatica",
                "lingua": "🇮🇹 Italiano",
                "lingua_code": "it",
                "durata": "3 anni (180 CFU)",
                "ambiti": ["cs", "ai"],
                "focus": "Dipartimento di Matematica. Solida base algoritmica, programmazione funzionale e ad oggetti, basi di machine learning."
            },
            {
                "nome": "Laurea in Ingegneria Informatica",
                "lingua": "🇮🇹 Italiano",
                "lingua_code": "it",
                "durata": "3 anni (180 CFU)",
                "ambiti": ["ce", "embedded", "robotics"],
                "focus": "Sistemi operativi, architettura elaboratori, controlli automatici e automazione industriale."
            },
            {
                "nome": "Laurea in Ingegneria Elettronica / Meccanica / Biomedica / Aerospaziale",
                "lingua": "🇮🇹 Italiano",
                "lingua_code": "it",
                "durata": "3 anni (180 CFU)",
                "ambiti": ["other_eng"],
                "focus": "Perfetto per i tuoi amici dell'ITIS Rossi che vogliono fare altri rami dell'ingegneria nello stesso polo."
            }
        ],
        "lingua_triennale": "Inglese (Information Engineering) + Italiano (Informatica, Ing. Informatica)",
        "has_english_bachelor": True,
        "has_italian_bachelor": True,
        "ammissione": {
            "test_richiesto": "TOLC-I (erogato da CISIA) per Ingegneria; TOLC-S per Scienze Informatiche",
            "soglia_indicativa": "Punteggio TOLC consigliato ≥ 22-26/50 per rientrare nella prima graduatoria",
            "scadenze": "1ª finestra anticipata: Febbraio–Aprile; 2ª finestra estiva: Giugno–Luglio",
            "requisiti_lingua": "Inglese B2 certificato (il tuo Cambridge First B2/C1 ti esonera direttamente dal CLA)",
            "procedura": "1. Sostieni il TOLC-I o TOLC@CASA su cisiaonline.it\n2. Iscriviti alla selezione su Uniweb allegando il punteggio TOLC\n3. Controlla la graduatoria e perfeziona l'immatricolazione online con SPID",
            "difficolta": 2
        },
        "approccio_didattico": "Tradizione teorica rigorosa italiana, ottimi laboratori al DEI (Dipartimento di Ingegneria dell'Informazione).",
        "qualita_vita": "Padova è una città a misura di studente, con vivace vita universitaria (Portello, piazze) e piste ciclabili ovunque.",
        "soddisfazione_studenti": "8.8/10. Elevata reputazione accademica e forte radicamento industriale nel Nord-Est.",
        "rapporto_studio_vita": "Ottimo: la vicinanza estrema a Vicenza elimina lo stress dei lunghi viaggi.",
        "borse_sussidi": "Borse regionali ESU Veneto per merito/reddito (fino a 6.000 €/anno + mensa e alloggio gratis per idonei). No-tax area fino a 24k ISEE.",
        "fit_score": 9.4,
        "fit_note": "Scelta strategicamente imbattibile: a 30 km da casa, ha la triennale in inglese (Information Engineering), il tuo B2/C1 è subito valido e con 600-800€/mese ti avanza quasi tutto il budget se fai il pendolare!",
        "punti_forza": ["A soli 30 km da Vicenza (20 min di treno)", "Triennale in inglese 'Information Engineering'", "Spesa alloggio 0 € se pendolare", "Ampia gamma di ingegnerie per gli amici"],
        "punti_deboli": ["Meno orientata al project-based learning rispetto agli atenei nordeuropei", "Classi del primo anno numerose"],
        "url": "https://www.unipd.it"
    },
    {
        "id": "univr",
        "nome": "Università di Verona (UniVr)",
        "citta": "Verona",
        "paese": "Italia",
        "bandiera": "🇮🇹",
        "lat": 45.4384,
        "lng": 10.9916,
        "qs2027": 680,
        "qs2026": 700,
        "punteggio_qs": 28.5,
        "tasse_annue_eu": "Fino a ~2.300 € (No-tax area ISEE fino a 24.000 €)",
        "affitto_mensile": "350–480 € (o 0 € pendolare da Vicenza)",
        "costo_vita_totale": "~450–700 €/mese (o ~110 € treno pendolare)",
        "budget_mensile_val": 600,
        "budget_rating": 5,
        "ambiti": ["cs", "ai", "embedded", "other_eng"],
        "lauree_triennali": [
            {
                "nome": "Laurea in Informatica",
                "lingua": "🇮🇹 Italiano",
                "lingua_code": "it",
                "durata": "3 anni (180 CFU)",
                "ambiti": ["cs", "ai", "embedded"],
                "focus": "Dipartimento di informatica a Ca' Vignal (Borgo Roma). Forte su sistemi embedded, algoritmi e intelligenza artificiale."
            },
            {
                "nome": "Laurea in Bioinformatica",
                "lingua": "🇮🇹 Italiano / Moduli Inglese",
                "lingua_code": "it",
                "durata": "3 anni (180 CFU)",
                "ambiti": ["cs", "ai"],
                "focus": "Intersezione tra machine learning, data science e genetica/scienze biologiche."
            },
            {
                "nome": "Laurea in Ingegneria dei Sistemi Medicali",
                "lingua": "🇮🇹 Italiano",
                "lingua_code": "it",
                "durata": "3 anni (180 CFU)",
                "ambiti": ["other_eng", "embedded"],
                "focus": "Corso ingegneristico per dispositivi hardware/software sanitari."
            }
        ],
        "lingua_triennale": "Italiano (Informatica, Bioinformatica)",
        "has_english_bachelor": False,
        "has_italian_bachelor": True,
        "ammissione": {
            "test_richiesto": "TOLC-S per Informatica",
            "soglia_indicativa": "Punteggio TOLC ≥ 18-20/50",
            "scadenze": "Sessioni primaverili ed estive TOLC",
            "requisiti_lingua": "Italiano",
            "procedura": "Sostieni il TOLC-S, registrati su ESSE3 UniVr e inserisciti in graduatoria.",
            "difficolta": 1
        },
        "approccio_didattico": "Dipartimento compatto, ottimo rapporto studenti-docenti.",
        "qualita_vita": "Verona è bella, sicura, ordinata e comodissima da raggiungere da Vicenza.",
        "soddisfazione_studenti": "8.5/10. Docenti molto accessibili nei laboratori.",
        "rapporto_studio_vita": "Eccellente: 35 minuti di treno da Vicenza a Verona Porta Vescovo (vicina al campus).",
        "borse_sussidi": "Borse ESU Verona.",
        "fit_score": 8.7,
        "fit_note": "A 45 km da Vicenza. Polo di Borgo Roma vicinissimo alla stazione Porta Vescovo: perfetto se vuoi fare il pendolare con spesa minima.",
        "punti_forza": ["A 45 km da Vicenza (35 min di treno)", "Dipartimento informatica molto quotato", "Costi quasi zero da pendolare", "Rapporto stretto coi docenti"],
        "punti_deboli": ["Non ha triennale 100% in inglese"],
        "url": "https://www.univr.it"
    },
    {
        "id": "unive",
        "nome": "Università Ca' Foscari Venezia",
        "citta": "Venezia",
        "paese": "Italia",
        "bandiera": "🇮🇹",
        "lat": 45.4344,
        "lng": 12.3267,
        "qs2027": 630,
        "qs2026": 650,
        "punteggio_qs": 30.2,
        "tasse_annue_eu": "Fino a ~2.400 € (No-tax area ISEE)",
        "affitto_mensile": "400–600 € (o 0 € pendolare per campus Mestre)",
        "costo_vita_totale": "~500–750 €/mese (o ~110 € treno)",
        "budget_mensile_val": 650,
        "budget_rating": 5,
        "ambiti": ["cs", "ai", "cyber"],
        "lauree_triennali": [
            {
                "nome": "B.Sc. Digital Management (con H-FARM)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 CFU)",
                "ambiti": ["cs", "ai"],
                "focus": "100% in inglese presso il campus H-FARM. Combina computer science, AI, business digitale e innovazione."
            },
            {
                "nome": "Laurea in Informatica (Campus di Mestre)",
                "lingua": "🇮🇹 Italiano",
                "lingua_code": "it",
                "durata": "3 anni (180 CFU)",
                "ambiti": ["cs", "ai", "cyber"],
                "focus": "Campus Scientifico di Via Torino a Mestre. Specializzazioni in cybersecurity e data science."
            }
        ],
        "lingua_triennale": "Inglese (Digital Management) + Italiano (Informatica)",
        "has_english_bachelor": True,
        "has_italian_bachelor": True,
        "ammissione": {
            "test_richiesto": "TOLC-I o TOLC-S per Informatica; TOLC-E / SAT per Digital Management",
            "soglia_indicativa": "Punteggio TOLC ≥ 20/50",
            "scadenze": "Finestra primaverile ed estiva",
            "requisiti_lingua": "B2 inglese per Digital Management",
            "procedura": "Iscrizione online su Ca' Foscari con esito TOLC.",
            "difficolta": 2
        },
        "approccio_didattico": "Moderno polo a Mestre; campus stile Silicon Valley a H-FARM.",
        "qualita_vita": "Facile da raggiungere via treno (fermata Venezia Mestre).",
        "soddisfazione_studenti": "8.4/10.",
        "rapporto_studio_vita": "Molto buono se fai il pendolare sulla linea ferroviaria Vicenza-Mestre (~40-50 min).",
        "borse_sussidi": "ESU Venezia.",
        "fit_score": 8.5,
        "fit_note": "A 60 km da Vicenza. Startup e innovazione a H-FARM in inglese, oppure Informatica e Cybersecurity al Campus di Mestre.",
        "punti_forza": ["A 60 km da Vicenza", "Digital Management 100% in inglese a H-FARM", "Campus scientifico moderno a Mestre"],
        "punti_deboli": ["H-FARM ha rette extra rispetto alla pubblica pura", "Meno orientato all'hardware"],
        "url": "https://www.unive.it"
    },
    {
        "id": "polimi",
        "nome": "Politecnico di Milano (PoliMi)",
        "citta": "Milano",
        "paese": "Italia",
        "bandiera": "🇮🇹",
        "lat": 45.4781,
        "lng": 9.2273,
        "qs2027": 87,
        "qs2026": 111,
        "punteggio_qs": 68.4,
        "tasse_annue_eu": "Fino a ~3.900 €/anno (fasce ISEE, no-tax area)",
        "affitto_mensile": "500–800 € (singola)",
        "costo_vita_totale": "~900–1.300 €/mese",
        "budget_mensile_val": 1100,
        "budget_rating": 3,
        "ambiti": ["cs", "ce", "ai", "robotics", "embedded", "other_eng"],
        "lauree_triennali": [
            {
                "nome": "Laurea in Ingegneria Informatica",
                "lingua": "🇮🇹 Italiano",
                "lingua_code": "it",
                "durata": "3 anni (180 CFU)",
                "ambiti": ["ce", "cs", "ai", "embedded"],
                "focus": "Il corso di riferimento per l'ingegneria informatica in Italia. Rigore matematico e ingegneristico di prim'ordine."
            },
            {
                "nome": "Laurea in Ingegneria dell'Automazione (Automation & Control)",
                "lingua": "🇮🇹 Italiano",
                "lingua_code": "it",
                "durata": "3 anni (180 CFU)",
                "ambiti": ["robotics", "embedded"],
                "focus": "Robotica, controlli automatici, automazione industriale e meccatronica. Perfetto per il tuo background RoboCup."
            },
            {
                "nome": "Laurea in Ingegneria Elettronica / Meccanica / Aerospaziale / Biomedica",
                "lingua": "🇮🇹 Italiano",
                "lingua_code": "it",
                "durata": "3 anni (180 CFU)",
                "ambiti": ["other_eng"],
                "focus": "I migliori corsi d'ingegneria in Italia per i tuoi compagni di scuola dell'ITIS Rossi."
            }
        ],
        "lingua_triennale": "Italiano (Triennali) — Magistrali 100% in inglese",
        "has_english_bachelor": False,
        "has_italian_bachelor": True,
        "ammissione": {
            "test_richiesto": "TOL (Test On Line del Politecnico di Milano)",
            "soglia_indicativa": "Punteggio TOL ≥ 60/100 (in 4ª superiore garantisce immatricolazione anticipata!)",
            "scadenze": "Sessioni da Febbraio a Luglio",
            "requisiti_lingua": "Inglese B2 (il tuo Cambridge First ti esonera dal test TELA)",
            "procedura": "1. Registrati su polimi.it\n2. Sostieni il TOL\n3. Con ≥ 60 ti immatricoli direttamente nella sessione anticipata!",
            "difficolta": 3
        },
        "approccio_didattico": "Forte rigore teorico, Analisi e Fisica molto selettive. Team studenteschi top (Formula Student, Polimi Robotics).",
        "qualita_vita": "Milano offre opportunità professionali ed eventi tech ineguagliabili in Italia.",
        "soddisfazione_studenti": "8.9/10. Marchio PoliMi ricercatissimo in tutta Europa.",
        "rapporto_studio_vita": "Intenso: carico di studio alto, ma collegamenti ferroviari con Vicenza facilissimi (1h45 Frecciarossa).",
        "borse_sussidi": "DSU PoliMi (alloggio + borsa fino a 7.000 €).",
        "fit_score": 9.0,
        "fit_note": "Il top assoluto in Italia (#87 al mondo). A 1h45 di Frecciarossa da Vicenza. Se passi il TOL con ≥60 sei dentro subito. Solo la triennale è in italiano (magistrali in inglese).",
        "punti_forza": ["#87 al mondo (Top 1 in Italia)", "TOL superabile in anticipo", "Networking eccezionale con aziende IT e robotica", "A 1h45 di treno AV da Vicenza"],
        "punti_deboli": ["Affitti molto cari a Milano (550-800€/stanza)", "Triennale in italiano"],
        "url": "https://www.polimi.it"
    },
    {
        "id": "polito",
        "nome": "Politecnico di Torino (PoliTo)",
        "citta": "Torino",
        "paese": "Italia",
        "bandiera": "🇮🇹",
        "lat": 45.0628,
        "lng": 7.6626,
        "qs2027": 241,
        "qs2026": 252,
        "punteggio_qs": 41.2,
        "tasse_annue_eu": "Fino a ~2.600 € (fasce ISEE, no-tax area)",
        "affitto_mensile": "300–450 € (singola molto più economica di Milano)",
        "costo_vita_totale": "~650–850 €/mese",
        "budget_mensile_val": 750,
        "budget_rating": 4,
        "ambiti": ["cs", "ce", "ai", "robotics", "embedded", "other_eng"],
        "lauree_triennali": [
            {
                "nome": "B.Sc. Computer Engineering (100% IN INGLESE)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 CFU)",
                "ambiti": ["ce", "cs", "ai", "embedded"],
                "focus": "Uno dei pochissimi corsi di Ingegneria Informatica in Italia interamente erogato in lingua inglese fin dal 1° anno!"
            },
            {
                "nome": "Laurea in Ingegneria Informatica (in Italiano)",
                "lingua": "🇮🇹 Italiano",
                "lingua_code": "it",
                "durata": "3 anni (180 CFU)",
                "ambiti": ["ce", "cs", "embedded"],
                "focus": "Curriculum classico, solido su architetture calcolatori, sistemi operativi e reti di telecomunicazione."
            },
            {
                "nome": "Laurea in Ingegneria Meccatronica / Elettronica / Aerospaziale / Autoveicolo",
                "lingua": "🇮🇹 Italiano / Moduli Inglese",
                "lingua_code": "it",
                "durata": "3 anni (180 CFU)",
                "ambiti": ["robotics", "other_eng", "embedded"],
                "focus": "Torino capitale dell'automotive e della meccatronica. Perfetto per il tuo background embedded/robotico e per gli amici."
            }
        ],
        "lingua_triennale": "Inglese (Computer Engineering) + Italiano (altre ingegnerie)",
        "has_english_bachelor": True,
        "has_italian_bachelor": True,
        "ammissione": {
            "test_richiesto": "TIL-I (Test d'Ingresso On-line PoliTo)",
            "soglia_indicativa": "Punteggio TIL-I ≥ 60/100 = ammissione garantita senza passare da graduatoria!",
            "scadenze": "Sessioni da Febbraio a Luglio",
            "requisiti_lingua": "B2 inglese (il tuo Cambridge First ti esonera dall'IELTS)",
            "procedura": "1. Account su Apply@polito\n2. Prenota il TIL-I\n3. Con ≥ 60 immatricolazione immediata!",
            "difficolta": 2
        },
        "approccio_didattico": "Metodo politecnico solido, team studenteschi eccellenti (Team Meccatronica, Squadra Corse).",
        "qualita_vita": "Miglior rapporto qualità/prezzo in Italia: affitti abbordabili, città ciclabile e verde.",
        "soddisfazione_studenti": "8.8/10. Ambiente accogliente e vivace.",
        "rapporto_studio_vita": "Equilibrato: ritmo impegnativo ma vita studentesca molto piacevole con costi contenuti.",
        "borse_sussidi": "EDISU Piemonte (fino a 6.500 € + mensa e residenza).",
        "fit_score": 9.5,
        "fit_note": "⭐ OPZIONE ITALIANA TOP: ha la triennale in Computer Engineering 100% IN INGLESE, costa molto meno di Milano (350-400€/stanza), budget familiare di 600-800€ perfetto e con TIL-I ≥60 sei dentro!",
        "punti_forza": ["Triennale Computer Engineering 100% in inglese", "Costi affitto bassi (300-450€)", "Budget 600-800€/mese ideale", "Ammissione automatica con TIL ≥ 60"],
        "punti_deboli": ["A ~3h di treno da Vicenza"],
        "url": "https://www.polito.it"
    },
    {
        "id": "unitn",
        "nome": "Università di Trento (UniTn)",
        "citta": "Trento",
        "paese": "Italia",
        "bandiera": "🇮🇹",
        "lat": 46.0697,
        "lng": 11.1211,
        "qs2027": 429,
        "qs2026": 435,
        "punteggio_qs": 31.8,
        "tasse_annue_eu": "Fino a ~3.000 € (No-tax area e welfare provinciale)",
        "affitto_mensile": "300–450 € (singola / Opera Universitaria)",
        "costo_vita_totale": "~650–850 €/mese",
        "budget_mensile_val": 750,
        "budget_rating": 4,
        "ambiti": ["cs", "ce", "ai", "embedded", "other_eng"],
        "lauree_triennali": [
            {
                "nome": "Laurea in Ingegneria Informatica, Comunicazioni ed Elettronica (ICE)",
                "lingua": "🇮🇹 Italiano",
                "lingua_code": "it",
                "durata": "3 anni (180 CFU)",
                "ambiti": ["ce", "embedded", "cs"],
                "focus": "Polo tecnologico DISI a Povo. Fortissima integrazione hardware/software e telecomunicazioni."
            },
            {
                "nome": "Laurea in Informatica",
                "lingua": "🇮🇹 Italiano",
                "lingua_code": "it",
                "durata": "3 anni (180 CFU)",
                "ambiti": ["cs", "ai"],
                "focus": "Focalizzato su intelligenza artificiale, algoritmi avanzati e ingegneria software con la Fondazione Bruno Kessler (FBK)."
            },
            {
                "nome": "Laurea in Ingegneria Industriale / Meccatronica (Rovereto/Trento)",
                "lingua": "🇮🇹 Italiano",
                "lingua_code": "it",
                "durata": "3 anni (180 CFU)",
                "ambiti": ["other_eng", "robotics"],
                "focus": "Ottimo per compagni interessati a meccatronica e materiali."
            }
        ],
        "lingua_triennale": "Italiano (triennali) — Magistrali in inglese (DISI)",
        "has_english_bachelor": False,
        "has_italian_bachelor": True,
        "ammissione": {
            "test_richiesto": "TOLC-I (CISIA)",
            "soglia_indicativa": "Punteggio TOLC ≥ 22-24/50",
            "scadenze": "Bandi primaverili (Marzo-Maggio) ed estivi (Luglio)",
            "requisiti_lingua": "Italiano",
            "procedura": "Sostieni il TOLC-I e iscriviti al bando UniTn.",
            "difficolta": 2
        },
        "approccio_didattico": "Polo tecnologico di Povo eccezionale: aule moderne, laboratori ricchi, rapporto diretto con i docenti.",
        "qualita_vita": "Trento è ai vertici nazionali per vivibilità, sicurezza, verde e piste ciclabili.",
        "soddisfazione_studenti": "9.1/10 (tra le più alte d'Italia).",
        "rapporto_studio_vita": "Perfetto: a solo 1h30 di auto o treno da Vicenza (Valsugana).",
        "borse_sussidi": "Opera Universitaria di Trento: tra le migliori in Italia per alloggi e borse.",
        "fit_score": 9.2,
        "fit_note": "A 90 km da Vicenza. Il DISI di Trento è un'eccellenza per informatica e AI. Città splendida, welfare provinciale al top e rientro a casa facilissimo.",
        "punti_forza": ["A 90 km da Vicenza (1h30 auto/Valsugana)", "Dipartimento DISI al vertice", "Alloggi Opera Universitaria economici", "Qualità vita altissima"],
        "punti_deboli": ["Triennale in italiano", "Città tranquilla per chi ama grandi metropoli"],
        "url": "https://www.unitn.it"
    },
    {
        "id": "unibo",
        "nome": "Università di Bologna (UniBo)",
        "citta": "Bologna",
        "paese": "Italia",
        "bandiera": "🇮🇹",
        "lat": 44.4949,
        "lng": 11.3426,
        "qs2027": 123,
        "qs2026": 154,
        "punteggio_qs": 58.7,
        "tasse_annue_eu": "Fino a ~3.000 € (No-tax area fino a 24k ISEE)",
        "affitto_mensile": "400–650 € (forte crisi alloggi)",
        "costo_vita_totale": "~800–1.100 €/mese",
        "budget_mensile_val": 950,
        "budget_rating": 3,
        "ambiti": ["cs", "ce", "ai", "robotics", "other_eng"],
        "lauree_triennali": [
            {
                "nome": "Laurea in Ingegneria Informatica",
                "lingua": "🇮🇹 Italiano",
                "lingua_code": "it",
                "durata": "3 anni (180 CFU)",
                "ambiti": ["ce", "cs", "embedded"],
                "focus": "Scuola di Ingegneria. Collegamenti con la Motor Valley e l'industria emiliana."
            },
            {
                "nome": "Laurea in Ingegneria dell'Automazione (Automation Engineering)",
                "lingua": "🇮🇹 Italiano",
                "lingua_code": "it",
                "durata": "3 anni (180 CFU)",
                "ambiti": ["robotics", "embedded"],
                "focus": "Tradizione fortissima nei controlli automatici e robotica industriale."
            },
            {
                "nome": "Laurea in Scienze Informatiche",
                "lingua": "🇮🇹 Italiano",
                "lingua_code": "it",
                "durata": "3 anni (180 CFU)",
                "ambiti": ["cs", "ai"],
                "focus": "Dipartimento DISI. Basi solide di algoritmi, programmazione e cloud computing."
            }
        ],
        "lingua_triennale": "Italiano (triennali)",
        "has_english_bachelor": False,
        "has_italian_bachelor": True,
        "ammissione": {
            "test_richiesto": "TOLC-I o TOLC-S",
            "soglia_indicativa": "Punteggio TOLC ≥ 25/50",
            "scadenze": "Selezioni primaverili ed estive",
            "requisiti_lingua": "Italiano",
            "procedura": "Sostieni il TOLC e partecipa alla selezione su Studenti Online.",
            "difficolta": 2
        },
        "approccio_didattico": "Ateneo storico e prestigioso, formazione accademica rigorosa.",
        "qualita_vita": "Bologna è la capitale della vita studentesca italiana: cultura, musica, piazze sempre piene.",
        "soddisfazione_studenti": "9.0/10.",
        "rapporto_studio_vita": "Stimolante ma trovare casa a Bologna è attualmente molto complesso.",
        "borse_sussidi": "ER.GO Emilia-Romagna.",
        "fit_score": 8.6,
        "fit_note": "A 1h20 di treno AV da Vicenza. Vita studentesca favolosa, ma alloggi difficili e triennale in italiano.",
        "punti_forza": ["A 1h20 di treno da Vicenza", "Vita studentesca leggendaria", "Polo automazione forte"],
        "punti_deboli": ["Difficoltà estrema alloggi", "Triennale in italiano"],
        "url": "https://www.unibo.it"
    },
    {
        "id": "sapienza",
        "nome": "Sapienza Università di Roma",
        "citta": "Roma",
        "paese": "Italia",
        "bandiera": "🇮🇹",
        "lat": 41.9028,
        "lng": 12.4964,
        "qs2027": 111,
        "qs2026": 134,
        "punteggio_qs": 61.3,
        "tasse_annue_eu": "Fino a ~2.900 € (No-tax area ISEE)",
        "affitto_mensile": "400–650 €",
        "costo_vita_totale": "~800–1.150 €/mese",
        "budget_mensile_val": 950,
        "budget_rating": 3,
        "ambiti": ["cs", "ce", "ai", "robotics", "other_eng"],
        "lauree_triennali": [
            {
                "nome": "B.Sc. Applied Computer Science and Artificial Intelligence (ACSAI)",
                "lingua": "🇬🇧 Inglese (100% in lingua)",
                "lingua_code": "en",
                "durata": "3 anni (180 CFU)",
                "ambiti": ["ai", "cs", "robotics"],
                "focus": "Uno dei più celebri Bachelor in AI d'Europa erogati in inglese! Machine learning, computer vision, elaborazione linguaggio naturale e robotica."
            },
            {
                "nome": "Laurea in Ingegneria Informatica e Automatica",
                "lingua": "🇮🇹 Italiano",
                "lingua_code": "it",
                "durata": "3 anni (180 CFU)",
                "ambiti": ["ce", "robotics", "embedded"],
                "focus": "Dipartimento DIAG. Grande tradizione nella robotica mobile e percezione autonoma."
            }
        ],
        "lingua_triennale": "Inglese (ACSAI) + Italiano (altri corsi)",
        "has_english_bachelor": True,
        "has_italian_bachelor": True,
        "ammissione": {
            "test_richiesto": "TOLC-I o SAT per il corso ACSAI in inglese",
            "soglia_indicativa": "Punteggio TOLC consigliato ≥ 30/50 o SAT ≥ 1200",
            "scadenze": "Bando aperto fino a Maggio/Giugno con graduatoria a Luglio",
            "requisiti_lingua": "Inglese B2 (il tuo Cambridge First ti qualifica direttamente)",
            "procedura": "1. Sostieni il TOLC-I\n2. Iscriviti al bando ACSAI su Infostud Sapienza\n3. Verifica la graduatoria",
            "difficolta": 3
        },
        "approccio_didattico": "DIAG Sapienza è un'autorità mondiale nella ricerca AI e robotica (RoboCup, lab ALCOR).",
        "qualita_vita": "Roma offre infinite attrazioni, metropoli vivace.",
        "soddisfazione_studenti": "8.5/10 (molto alta per la classe internazionale di ACSAI).",
        "rapporto_studio_vita": "Molto stimolante accademicamente, logistica cittadina impegnativa.",
        "borse_sussidi": "DiSCo Lazio.",
        "fit_score": 8.9,
        "fit_note": "Il corso 'ACSAI' (Applied Computer Science & AI) in inglese alla Sapienza è uno dei migliori d'Europa sui tuoi temi. Distante da Vicenza (~3h30 Frecciarossa), ma prestigioso.",
        "punti_forza": ["BSc in AI 100% in inglese (ACSAI)", "Reputazione mondiale DIAG nella RoboCup e AI", "#111 al mondo QS"],
        "punti_deboli": ["Roma caotica e distante da Vicenza", "Selezione ACSAI molto competitiva"],
        "url": "https://www.uniroma1.it"
    },
    {
        "id": "unipi",
        "nome": "Università di Pisa (UniPi)",
        "citta": "Pisa",
        "paese": "Italia",
        "bandiera": "🇮🇹",
        "lat": 43.7167,
        "lng": 10.4000,
        "qs2027": 349,
        "qs2026": 389,
        "punteggio_qs": 35.8,
        "tasse_annue_eu": "Fino a ~2.400 € (No-tax area ISEE)",
        "affitto_mensile": "300–450 €",
        "costo_vita_totale": "~650–850 €/mese",
        "budget_mensile_val": 750,
        "budget_rating": 4,
        "ambiti": ["cs", "ce", "ai", "robotics", "other_eng"],
        "lauree_triennali": [
            {
                "nome": "Laurea in Informatica",
                "lingua": "🇮🇹 Italiano",
                "lingua_code": "it",
                "durata": "3 anni (180 CFU)",
                "ambiti": ["cs", "ai"],
                "focus": "Qui è nato il primo corso di Informatica in Italia. Tradizione teorica e algoritmica leggendaria."
            },
            {
                "nome": "Laurea in Ingegneria Informatica / Robotica",
                "lingua": "🇮🇹 Italiano",
                "lingua_code": "it",
                "durata": "3 anni (180 CFU)",
                "ambiti": ["ce", "robotics", "embedded"],
                "focus": "Polo d'eccellenza per la robotica (connesso all'Istituto di Biorobotica e Sant'Anna)."
            }
        ],
        "lingua_triennale": "Italiano (triennali)",
        "has_english_bachelor": False,
        "has_italian_bachelor": True,
        "ammissione": {
            "test_richiesto": "TOLC-I o TOLC-S",
            "soglia_indicativa": "Punteggio TOLC ≥ 18/50",
            "scadenze": "Finestre da Primavera a Settembre",
            "requisiti_lingua": "Italiano",
            "procedura": "Iscrizione con TOLC su Alice UniPi.",
            "difficolta": 2
        },
        "approccio_didattico": "Rigore teorico elevatissimo, polo di ricerca storico.",
        "qualita_vita": "Pisa è una città universitaria al 100%, ci si muove in bici ovunque.",
        "soddisfazione_studenti": "8.6/10.",
        "rapporto_studio_vita": "Tranquillo, vita a misura d'uomo.",
        "borse_sussidi": "DSU Toscana.",
        "fit_score": 8.4,
        "fit_note": "La culla dell'informatica italiana, vicinissima alla Scuola Sant'Anna per la robotica. Budget 600-800€ qui basta perfettamente.",
        "punti_forza": ["Culla dell'informatica italiana", "Costi contenuti per stanza e vita", "Città a misura di studente"],
        "punti_deboli": ["Triennale in italiano", "A ~3h da Vicenza in treno"],
        "url": "https://www.unipi.it"
    },
    {
        "id": "unimi",
        "nome": "Università degli Studi di Milano (Statale)",
        "citta": "Milano",
        "paese": "Italia",
        "bandiera": "🇮🇹",
        "lat": 45.4600,
        "lng": 9.1944,
        "qs2027": 285,
        "qs2026": 276,
        "punteggio_qs": 38.9,
        "tasse_annue_eu": "Fino a ~2.700 € (No-tax area fino a 24k ISEE)",
        "affitto_mensile": "500–750 €",
        "costo_vita_totale": "~900–1.250 €/mese",
        "budget_mensile_val": 1050,
        "budget_rating": 3,
        "ambiti": ["cs", "ai"],
        "lauree_triennali": [
            {
                "nome": "B.Sc. Artificial Intelligence (Interateneo Milano-Pavia-Bicocca)",
                "lingua": "🇬🇧 Inglese (100% in lingua)",
                "lingua_code": "en",
                "durata": "3 anni (180 CFU)",
                "ambiti": ["ai", "cs"],
                "focus": "Corso congiunto in inglese tra UniMi, UniPv e Bicocca. Matematica, computer science, neuroscienze ed etica dell'AI."
            },
            {
                "nome": "Laurea in Informatica",
                "lingua": "🇮🇹 Italiano",
                "lingua_code": "it",
                "durata": "3 anni (180 CFU)",
                "ambiti": ["cs"],
                "focus": "Dipartimento di Informatica in via Celoria a Città Studi. Storica preparazione informatica milanese."
            }
        ],
        "lingua_triennale": "Inglese (BSc Artificial Intelligence) + Italiano (Informatica)",
        "has_english_bachelor": True,
        "has_italian_bachelor": True,
        "ammissione": {
            "test_richiesto": "TOLC-I o test dedicato per il corso di Artificial Intelligence",
            "soglia_indicativa": "Punteggio TOLC ≥ 28/50 per AI (numero chiuso)",
            "scadenze": "Domande aperte in primavera con graduatoria a Giugno/Luglio",
            "requisiti_lingua": "Inglese B2",
            "procedura": "Bando interateneo con iscrizione su UniMi allegando TOLC.",
            "difficolta": 3
        },
        "approccio_didattico": "Innovativo grazie alla combinazione dei docenti di 3 atenei lombardi.",
        "qualita_vita": "Città Studi a Milano: quartiere vivace e ben servito da metro e bus.",
        "soddisfazione_studenti": "8.7/10 per AI.",
        "rapporto_studio_vita": "Stimolante ma Milano richiede buona gestione del budget.",
        "borse_sussidi": "DSU Lombardia.",
        "fit_score": 8.8,
        "fit_note": "Il Bachelor in Artificial Intelligence in inglese interateneo è un'altra perla formativa per te, a 1h45 di treno AV da Vicenza.",
        "punti_forza": ["Bachelor in Artificial Intelligence 100% in inglese", "Network di tre grandi atenei", "A 1h45 di treno da Vicenza"],
        "punti_deboli": ["Costi abitativi alti a Milano", "Solo 180 posti disponibili per AI"],
        "url": "https://www.unimi.it"
    },
    {
        "id": "unipv",
        "nome": "Università di Pavia (UniPv)",
        "citta": "Pavia",
        "paese": "Italia",
        "bandiera": "🇮🇹",
        "lat": 45.1866,
        "lng": 9.1554,
        "qs2027": 440,
        "qs2026": 460,
        "punteggio_qs": 31.0,
        "tasse_annue_eu": "Fino a ~2.400 € (No-tax area ISEE)",
        "affitto_mensile": "350–500 € (Collegi universitari storici molto convenienti)",
        "costo_vita_totale": "~650–850 €/mese",
        "budget_mensile_val": 750,
        "budget_rating": 4,
        "ambiti": ["cs", "ce", "ai", "embedded", "other_eng"],
        "lauree_triennali": [
            {
                "nome": "B.Sc. Artificial Intelligence (sede congiunta con Milano)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 CFU)",
                "ambiti": ["ai", "cs"],
                "focus": "Sede di lezioni e laboratori anche presso il polo Cravino di Pavia."
            },
            {
                "nome": "Laurea in Ingegneria Elettronica e Informatica",
                "lingua": "🇮🇹 Italiano",
                "lingua_code": "it",
                "durata": "3 anni (180 CFU)",
                "ambiti": ["ce", "embedded", "cs"],
                "focus": "Grande tradizione nella microelettronica, chip design e sistemi embedded."
            },
            {
                "nome": "Laurea in Bioingegneria / Ingegneria Industriale",
                "lingua": "🇮🇹 Italiano",
                "lingua_code": "it",
                "durata": "3 anni (180 CFU)",
                "ambiti": ["other_eng"],
                "focus": "Ottima per amici orientati verso biomedicale e meccanica."
            }
        ],
        "lingua_triennale": "Inglese (Artificial Intelligence) + Italiano (altre ingegnerie)",
        "has_english_bachelor": True,
        "has_italian_bachelor": True,
        "ammissione": {
            "test_richiesto": "TOLC-I",
            "soglia_indicativa": "Punteggio TOLC ≥ 20/50",
            "scadenze": "Primavera - Estate",
            "requisiti_lingua": "Inglese B2 per corso AI",
            "procedura": "Iscrizione tramite portale Esse3 Pavia allegando TOLC.",
            "difficolta": 2
        },
        "approccio_didattico": "Famoso per il sistema dei collegi storici di merito (Borromeo, Ghislieri, EDiSU).",
        "qualita_vita": "Città universitaria tranquilla, verde, a 25 min di treno da Milano ma a costi molto più bassi.",
        "soddisfazione_studenti": "8.8/10.",
        "rapporto_studio_vita": "Eccellente: vita di collegio comunitaria e costi contenuti.",
        "borse_sussidi": "EDiSU Pavia.",
        "fit_score": 8.7,
        "fit_note": "Pavia ha un sistema di collegi universitari unico in Italia che abbatte i costi d'alloggio, e partecipa al Bachelor in Artificial Intelligence in inglese.",
        "punti_forza": ["Sistema collegiale storico a costi ridotti", "BSc in Artificial Intelligence in inglese", "Costi molto inferiori a Milano pur essendo a 25 min"],
        "punti_deboli": ["Città più piccola"],
        "url": "https://www.unipv.it"
    },
    {
        "id": "unina",
        "nome": "Università di Napoli Federico II",
        "citta": "Napoli",
        "paese": "Italia",
        "bandiera": "🇮🇹",
        "lat": 40.8497,
        "lng": 14.2562,
        "qs2027": 300,
        "qs2026": 335,
        "punteggio_qs": 37.8,
        "tasse_annue_eu": "Fino a ~2.300 € (No-tax area ISEE)",
        "affitto_mensile": "280–400 € (singola molto economica)",
        "costo_vita_totale": "~550–750 €/mese",
        "budget_mensile_val": 650,
        "budget_rating": 5,
        "ambiti": ["cs", "ce", "ai", "robotics", "embedded", "other_eng"],
        "lauree_triennali": [
            {
                "nome": "Laurea in Ingegneria Informatica (Polo di San Giovanni a Teduccio)",
                "lingua": "🇮🇹 Italiano",
                "lingua_code": "it",
                "durata": "3 anni (180 CFU)",
                "ambiti": ["ce", "cs", "ai"],
                "focus": "Campus di San Giovanni a Teduccio, sede dell'Apple Developer Academy e della Cisco Academy."
            },
            {
                "nome": "Laurea in Ingegneria dell'Automazione e Robotica",
                "lingua": "🇮🇹 Italiano",
                "lingua_code": "it",
                "durata": "3 anni (180 CFU)",
                "ambiti": ["robotics", "embedded"],
                "focus": "Scuola di eccellenza nel controllo dei robot manipolatori e veicoli autonomi (PRISMA Lab di Bruno Siciliano)."
            },
            {
                "nome": "Laurea in Ingegneria Aerospaziale / Meccanica",
                "lingua": "🇮🇹 Italiano",
                "lingua_code": "it",
                "durata": "3 anni (180 CFU)",
                "ambiti": ["other_eng"],
                "focus": "Tra le migliori scuole d'Italia per l'aerospazio."
            }
        ],
        "lingua_triennale": "Italiano (triennali) — Academy internazionali in inglese",
        "has_english_bachelor": False,
        "has_italian_bachelor": True,
        "ammissione": {
            "test_richiesto": "TOLC-I",
            "soglia_indicativa": "Punteggio TOLC ≥ 18/50",
            "scadenze": "Primavera ed estate",
            "requisiti_lingua": "Italiano",
            "procedura": "Iscrizione tramite Segrepass Federico II.",
            "difficolta": 2
        },
        "approccio_didattico": "Polo di San Giovanni a Teduccio modernissimo; laboratori PRISMA di livello mondiale nella robotica.",
        "qualita_vita": "Città ricca di energia, cultura, cibo straordinario a costi irrisori.",
        "soddisfazione_studenti": "8.5/10.",
        "rapporto_studio_vita": "Costi bassissimi, budget 600-800€ ti garantisce una vita agiatissima.",
        "borse_sussidi": "ADISURC Campania.",
        "fit_score": 8.3,
        "fit_note": "Il PRISMA Lab di robotica di Bruno Siciliano è una leggenda mondiale, e San Giovanni ospita l'Apple Developer Academy e la Cisco Academy. Lontana da Vicenza, ma costo vita super contenuto.",
        "punti_forza": ["PRISMA Lab tra i numeri 1 al mondo nella robotica", "Apple Developer Academy & Cisco Academy a San Giovanni", "Costi di vita ed affitti bassissimi"],
        "punti_deboli": ["Lontana da Vicenza (~5h treno AV)", "Triennale in italiano"],
        "url": "https://www.unina.it"
    },
    {
        "id": "unimore",
        "nome": "Università di Modena e Reggio Emilia (UNIMORE)",
        "citta": "Modena",
        "paese": "Italia",
        "bandiera": "🇮🇹",
        "lat": 44.6471,
        "lng": 10.9252,
        "qs2027": 690,
        "qs2026": 710,
        "punteggio_qs": 27.9,
        "tasse_annue_eu": "Fino a ~2.400 € (No-tax area ISEE)",
        "affitto_mensile": "350–500 €",
        "costo_vita_totale": "~650–850 €/mese",
        "budget_mensile_val": 750,
        "budget_rating": 4,
        "ambiti": ["cs", "ce", "ai", "robotics", "embedded", "other_eng"],
        "lauree_triennali": [
            {
                "nome": "Laurea in Ingegneria Informatica (Polo di Ingegneria Enzo Ferrari)",
                "lingua": "🇮🇹 Italiano",
                "lingua_code": "it",
                "durata": "3 anni (180 CFU)",
                "ambiti": ["ce", "ai", "embedded"],
                "focus": "Dipartimento DIEF. Fortissima su sistemi embedded per veicoli autonomi e AI applicata alla guida autonoma (AImark Lab)."
            },
            {
                "nome": "Laurea in Ingegneria Meccanica / Veicolo",
                "lingua": "🇮🇹 Italiano",
                "lingua_code": "it",
                "durata": "3 anni (180 CFU)",
                "ambiti": ["other_eng", "robotics"],
                "focus": "Cuore della Motor Valley (Ferrari, Maserati, Ducati, Dallara). Perfetto per amici appassionati di automotive."
            }
        ],
        "lingua_triennale": "Italiano (triennali) — Magistrali MUNER in inglese",
        "has_english_bachelor": False,
        "has_italian_bachelor": True,
        "ammissione": {
            "test_richiesto": "TOLC-I",
            "soglia_indicativa": "Punteggio TOLC ≥ 20/50",
            "scadenze": "Finestre primaverili ed estive",
            "requisiti_lingua": "Italiano",
            "procedura": "Iscrizione tramite Esse3 UNIMORE allegando TOLC.",
            "difficolta": 2
        },
        "approccio_didattico": "Forte orientamento ai progetti pratici e connessione diretta con i team corse e la Motor Valley.",
        "qualita_vita": "Modena è pulita, ricca, ciclabile e a misura d'uomo.",
        "soddisfazione_studenti": "8.7/10.",
        "rapporto_studio_vita": "Ottimo: a 1h30 da Vicenza (linea ferroviaria Verona-Modena o Bologna).",
        "borse_sussidi": "ER.GO Emilia-Romagna.",
        "fit_score": 8.5,
        "fit_note": "A 1h30 da Vicenza. Se ti piacciono veicoli autonomi, simulazioni fisiche e automotive (come nel tuo progetto Unity ML-Agents su guida autonoma!), UNIMORE e la Motor Valley sono perfette.",
        "punti_forza": ["Capitale mondiale della Motor Valley", "Laboratorio AI per veicoli autonomi all'avanguardia", "A 1h30 da Vicenza", "Perfetto per chi ama automotive e simulazioni"],
        "punti_deboli": ["Triennale in italiano"],
        "url": "https://www.unimore.it"
    }
]
