# -*- coding: utf-8 -*-
DUTCH_UNIS = [
    {
        "id": "tudelft",
        "nome": "TU Delft (Delft University of Technology)",
        "citta": "Delft",
        "paese": "Paesi Bassi",
        "bandiera": "🇳🇱",
        "lat": 52.0016,
        "lng": 4.3718,
        "qs2027": 48,
        "qs2026": 49,
        "punteggio_qs": 84.7,
        "tasse_annue_eu": "~2.601 €/anno (tariffa legale statale olandese per studenti UE)",
        "affitto_mensile": "500–850 €/mese (alloggi molto richiesti, cercare presto)",
        "costo_vita_totale": "~1.050–1.450 €/mese",
        "budget_mensile_val": 1250,
        "budget_rating": 2,
        "ambiti": ["cs", "ce", "ai", "robotics", "embedded", "other_eng"],
        "lauree_triennali": [
            {
                "nome": "B.Sc. Computer Science and Engineering (100% IN INGLESE)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["cs", "ce", "ai", "embedded"],
                "focus": "Uno dei migliori corsi al mondo: algoritmi, software engineering, sistemi distribuiti, intelligenza artificiale, architetture hardware."
            },
            {
                "nome": "B.Sc. Aerospace / Electrical / Mechanical Engineering",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["other_eng", "robotics"],
                "focus": "Aerospace Engineering e Electrical Engineering interamente in inglese. Top mondiale per gli amici appassionati di aerospazio e meccanica."
            }
        ],
        "lingua_triennale": "Inglese (BSc Computer Science & Engineering e Aerospace)",
        "has_english_bachelor": True,
        "has_italian_bachelor": False,
        "ammissione": {
            "test_richiesto": "Numerus Fixus Selection: test di matematica (CST), logica algoritmica e dossier motivazionale",
            "soglia_indicativa": "Ammessi i primi 550 nella graduatoria di selezione",
            "scadenze": "CRUCIALE: domanda su Studielink entro e non oltre il 15 GENNAIO! Test di selezione a Febbraio/Marzo",
            "requisiti_lingua": "Cambridge English C1 Advanced o IELTS ≥ 6.5 (min. 6.0 nei singoli componenti)",
            "procedura": "1. Registrazione su Studielink.nl entro il 15 gennaio\n2. Caricamento pagelle di 3ª e 4ª superiore su Osiaan (portale TU Delft)\n3. Partecipazione al test online di selezione (Matematica, Logica)\n4. Assegnazione del Ranking Number il 15 aprile",
            "difficolta": 4
        },
        "approccio_didattico": "Forte 'Project-Based Learning' e lavoro in team. Trimestri serrati, laboratori meccatronici spettacolari, D:Dream Hall (hangar di prototipi studenteschi).",
        "qualita_vita": "Cittadina storica meravigliosa attraversata da canali, interamente a misura di bicicletta.",
        "soddisfazione_studenti": "9.2/10. Ambiente internazionale stimolante.",
        "rapporto_studio_vita": "Ritmo intenso, esami frequenti, ma il campus è un'esperienza entusiasmante.",
        "borse_sussidi": "DUO Student Finance (lavorando 32h/mese sblocchi ~440 € di borsa base + abbonamento treni/bus gratuito in tutta l'Olanda).",
        "fit_score": 9.1,
        "fit_note": "Il sogno europeo per l'ingegneria (#48 al mondo, Top 1 in Olanda). Triennale in inglese di fama planetaria. Con 32h/mese di part-time sblocchi l'aiuto DUO (+440€) che rende la spesa sostenibile.",
        "punti_forza": ["#48 al mondo QS", "Triennale 100% in inglese tra le migliori al mondo", "D:Dream Hall per progetti pratici e robotica", "Aiuti DUO per studenti UE lavoratori"],
        "punti_deboli": ["Scadenza anticipata al 15 GENNAIO (Numerus Fixus)", "Crisi alloggi nei Paesi Bassi"],
        "url": "https://www.tudelft.nl"
    },
    {
        "id": "tue",
        "nome": "Eindhoven University of Technology (TU/e)",
        "citta": "Eindhoven",
        "paese": "Paesi Bassi",
        "bandiera": "🇳🇱",
        "lat": 51.4486,
        "lng": 5.4907,
        "qs2027": 124,
        "qs2026": 125,
        "punteggio_qs": 58.5,
        "tasse_annue_eu": "~2.601 €/anno (tariffa statale UE)",
        "affitto_mensile": "450–750 €/mese",
        "costo_vita_totale": "~950–1.350 €/mese",
        "budget_mensile_val": 1150,
        "budget_rating": 3,
        "ambiti": ["cs", "ce", "ai", "robotics", "embedded", "other_eng"],
        "lauree_triennali": [
            {
                "nome": "B.Sc. Computer Science and Engineering (100% IN INGLESE)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["cs", "ce", "embedded"],
                "focus": "Orientato all'ingegneria del software, sistemi operativi, sicurezza e programmazione concorrente."
            },
            {
                "nome": "B.Sc. Data Science (congiunto con Tilburg University)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["ai", "cs"],
                "focus": "Machine learning, statistica avanzata, big data ed estrazione della conoscenza."
            },
            {
                "nome": "B.Sc. Electrical Engineering / Mechanical Engineering (100% Inglese)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["embedded", "robotics", "other_eng"],
                "focus": "Interamente in inglese: chip design, sensori, robotica e sistemi di controllo."
            }
        ],
        "lingua_triennale": "Inglese (tutti i corsi sopra sono 100% in inglese)",
        "has_english_bachelor": True,
        "has_italian_bachelor": False,
        "ammissione": {
            "test_richiesto": "Numerus Fixus per Computer Science: test online di matematica e pensiero logico",
            "soglia_indicativa": "Selezione competitiva con circa 325 posti disponibili",
            "scadenze": "15 GENNAIO per Computer Science (Numerus Fixus); 1 Maggio per altri corsi",
            "requisiti_lingua": "Cambridge First B2 (con score alto) o C1 Advanced / IELTS 6.5",
            "procedura": "Domanda su Studielink.nl -> invio transcript voti superiori -> svolgimento test di selezione",
            "difficolta": 3
        },
        "approccio_didattico": "Forte enfasi sulla didattica 'Challenge-Based Learning' in collaborazione con le aziende del Brainport Eindhoven.",
        "qualita_vita": "Eindhoven è la Silicon Valley d'Europa (sede di ASML, Philips, NXP Semiconductors, VDL). Piena occupazione per laureati tech.",
        "soddisfazione_studenti": "9.0/10. Campus iper-moderno e collaborativo.",
        "rapporto_studio_vita": "Molto stimolante: la vicinanza a colossi come ASML apre opportunità di stage retribuiti già durante la triennale.",
        "borse_sussidi": "DUO olandese (viaggi gratuiti + borsa se si lavorano 32h/mese).",
        "fit_score": 9.4,
        "fit_note": "⭐ PARADISO PER HARDWARE, EMBEDDED E AI: Eindhoven è la capitale mondiale dei semiconduttori (ASML produce qui i macchinari per tutti i microchip del pianeta). Triennali 100% in inglese e sbocchi lavorativi immediati!",
        "punti_forza": ["Capitale europea dei chip e tech (ASML, Philips, NXP)", "Triennali 100% in inglese", "Didattica orientata alle sfide pratiche (CBL)", "DUO finance accessibile con lavoro part-time"],
        "punti_deboli": ["Scadenza 15 Gennaio per CS", "Ricerca alloggi impegnativa"],
        "url": "https://www.tue.nl"
    },
    {
        "id": "utwente",
        "nome": "University of Twente",
        "citta": "Enschede",
        "paese": "Paesi Bassi",
        "bandiera": "🇳🇱",
        "lat": 52.2415,
        "lng": 6.8528,
        "qs2027": 210,
        "qs2026": 210,
        "punteggio_qs": 44.5,
        "tasse_annue_eu": "~2.601 €/anno (tariffa UE)",
        "affitto_mensile": "350–550 €/mese (l'unica uni olandese con VERO CAMPUS all'americana e alloggi garantiti/accessibili!)",
        "costo_vita_totale": "~850–1.150 €/mese",
        "budget_mensile_val": 1000,
        "budget_rating": 4,
        "ambiti": ["cs", "ce", "ai", "robotics", "embedded", "gamedev", "other_eng"],
        "lauree_triennali": [
            {
                "nome": "B.Sc. Technical Computer Science (100% IN INGLESE)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["cs", "ce", "cyber", "embedded"],
                "focus": "Sistemi distribuiti, sicurezza informatica, algoritmi, reti e architetture hardware."
            },
            {
                "nome": "B.Sc. Creative Technology (CreaTe)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["gamedev", "embedded", "robotics"],
                "focus": "Focalizzato su interazione uomo-macchina, realtà virtuale, sensoristica interattiva, Unity e prototipazione hardware/software."
            },
            {
                "nome": "B.Sc. Electrical Engineering / Mechanical Engineering",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["embedded", "robotics", "other_eng"],
                "focus": "Robotica avanzata, meccatronica, droni autonomi e circuiti integrati."
            }
        ],
        "lingua_triennale": "Inglese (tutti i corsi sopra sono 100% in inglese)",
        "has_english_bachelor": True,
        "has_italian_bachelor": False,
        "ammissione": {
            "test_richiesto": "Numerus Fixus per Technical Computer Science (test online di matematica e pensiero logico)",
            "soglia_indicativa": "Posti disponibili circa 400",
            "scadenze": "15 GENNAIO per TCS; 1 Maggio per Creative Technology",
            "requisiti_lingua": "Cambridge First B2 (con score solido) o C1 / IELTS 6.5",
            "procedura": "Domanda su Studielink -> test online da casa -> ranking number",
            "difficolta": 2
        },
        "approccio_didattico": "Modello didattico TEM (Twente Educational Model): ogni trimestre è incentrato su un grande progetto pratico di gruppo che integra le materie teoriche.",
        "qualita_vita": "Unico vero campus all'americana dei Paesi Bassi: boschi, laghetti, impianti sportivi, laboratori aperti 24/7 e camere per studenti all'interno del campus!",
        "soddisfazione_studenti": "9.3/10. Spirito di comunità studentesca eccezionale.",
        "rapporto_studio_vita": "Il migliore dei Paesi Bassi: zero stress da pendolare, costi degli affitti molto più bassi di Amsterdam/Delft.",
        "borse_sussidi": "DUO finance olandese.",
        "fit_score": 9.5,
        "fit_note": "⭐ LA SCELTA PIÙ INTELLIGENTE IN OLANDA: ha il vero campus con stanze all'interno a prezzi accessibili (350-450€), progetti pratici continui ('Creative Technology' e 'Technical Computer Science' in inglese), e laboratori di robotica pazzeschi!",
        "punti_forza": ["Unico vero campus residenziale olandese", "Affitti molto più bassi del resto d'Olanda (350-500€)", "Corso unico 'Creative Technology' (VR, Unity, sensori)", "Approccio basato su progetti trimestrali"],
        "punti_deboli": ["Enschede è a est vicino al confine tedesco, a 2h da Amsterdam Schiphol"],
        "url": "https://www.utwente.nl"
    },
    {
        "id": "groningen",
        "nome": "University of Groningen",
        "citta": "Groninga",
        "paese": "Paesi Bassi",
        "bandiera": "🇳🇱",
        "lat": 53.2194,
        "lng": 6.5665,
        "qs2027": 139,
        "qs2026": 139,
        "punteggio_qs": 55.4,
        "tasse_annue_eu": "~2.601 €/anno (tariffa UE)",
        "affitto_mensile": "400–650 €/mese",
        "costo_vita_totale": "~900–1.250 €/mese",
        "budget_mensile_val": 1050,
        "budget_rating": 3,
        "ambiti": ["cs", "ai", "other_eng"],
        "lauree_triennali": [
            {
                "nome": "B.Sc. Artificial Intelligence (100% IN INGLESE)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["ai", "robotics", "cs"],
                "focus": "Uno dei più antichi e celebri corsi di AI d'Europa: machine learning, robotica autonoma, percezione e modelli cognitivi."
            },
            {
                "nome": "B.Sc. Computing Science (100% IN INGLESE)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["cs", "ce"],
                "focus": "Algoritmi, architettura del software, sicurezza e calcolo scientifico ad alte prestazioni."
            }
        ],
        "lingua_triennale": "Inglese (Artificial Intelligence e Computing Science)",
        "has_english_bachelor": True,
        "has_italian_bachelor": False,
        "ammissione": {
            "test_richiesto": "Numerus Fixus per Artificial Intelligence e Computing Science",
            "soglia_indicativa": "Test di matematica e logica online",
            "scadenze": "15 GENNAIO su Studielink!",
            "requisiti_lingua": "Cambridge Advanced C1 o First B2 (con score ≥ 175) / IELTS 6.5",
            "procedura": "Domanda Studielink -> test online",
            "difficolta": 3
        },
        "approccio_didattico": "Forte combinazione tra teoria rigorosa e progetti pratici di laboratorio AI.",
        "qualita_vita": "Groninga è la città più giovane d'Olanda: 1 abitante su 4 è studente, vita notturna senza orario di chiusura, città ciclabile per eccellenza.",
        "soddisfazione_studenti": "9.1/10.",
        "rapporto_studio_vita": "Vivacissimo: atmosfera universitaria totale.",
        "borse_sussidi": "DUO finance olandese.",
        "fit_score": 9.2,
        "fit_note": "Groninga ha una delle lauree triennali in Artificial Intelligence più famose al mondo, 100% in inglese. Città giovanissima e divertente.",
        "punti_forza": ["Triennale pionieristica in Artificial Intelligence", "Città con la più alta percentuale di studenti in Olanda", "Top 140 mondiale QS"],
        "punti_deboli": ["Scadenza 15 Gennaio per l'iscrizione", "Città situata nel nord dei Paesi Bassi"],
        "url": "https://www.rug.nl"
    },
    {
        "id": "vu_amsterdam",
        "nome": "Vrije Universiteit Amsterdam (VU)",
        "citta": "Amsterdam",
        "paese": "Paesi Bassi",
        "bandiera": "🇳🇱",
        "lat": 52.3339,
        "lng": 4.8656,
        "qs2027": 220,
        "qs2026": 207,
        "punteggio_qs": 43.8,
        "tasse_annue_eu": "~2.601 €/anno (tariffa UE)",
        "affitto_mensile": "550–900 €/mese (Amsterdam molto cara)",
        "costo_vita_totale": "~1.100–1.550 €/mese",
        "budget_mensile_val": 1300,
        "budget_rating": 2,
        "ambiti": ["cs", "ai", "cyber"],
        "lauree_triennali": [
            {
                "nome": "B.Sc. Computer Science (100% IN INGLESE)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["cs", "cyber"],
                "focus": "Sviluppato congiuntamente con University of Amsterdam (UvA): sicurezza reti, sistemi distribuiti, algoritmi."
            },
            {
                "nome": "B.Sc. Artificial Intelligence (100% IN INGLESE)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["ai", "cs"],
                "focus": "Focus su agenti intelligenti, machine learning, robotica cognitiva e web semantico."
            }
        ],
        "lingua_triennale": "Inglese",
        "has_english_bachelor": True,
        "has_italian_bachelor": False,
        "ammissione": {
            "test_richiesto": "Numerus Fixus: test di matematica e logica",
            "soglia_indicativa": "Graduatoria di merito",
            "scadenze": "15 GENNAIO su Studielink",
            "requisiti_lingua": "IELTS 6.5 o Cambridge First/Advanced",
            "procedura": "Studielink -> matching test",
            "difficolta": 3
        },
        "approccio_didattico": "Innovativo, campus concentrato a Zuidas (distretto finanziario e tecnologico di Amsterdam).",
        "qualita_vita": "Amsterdam è una capitale mondiale di cultura e tolleranza.",
        "soddisfazione_studenti": "8.8/10.",
        "rapporto_studio_vita": "Affascinante, ma gli affitti ad Amsterdam richiedono forte attenzione al budget.",
        "borse_sussidi": "DUO finance.",
        "fit_score": 8.7,
        "fit_note": "Qualità dei corsi in CS e AI eccellente. Il limite principale è il costo della vita e degli affitti ad Amsterdam.",
        "punti_forza": ["Corsi in CS e AI di grande prestigio", "Amsterdam hub internazionale", "Connessioni con grandi aziende tech"],
        "punti_deboli": ["Amsterdam molto costosa", "Alloggi introvabili se non prenotati con grande anticipo"],
        "url": "https://vu.nl"
    },
    {
        "id": "radboud",
        "nome": "Radboud University",
        "citta": "Nimega (Nijmegen)",
        "paese": "Paesi Bassi",
        "bandiera": "🇳🇱",
        "lat": 51.8211,
        "lng": 5.8628,
        "qs2027": 246,
        "qs2026": 246,
        "punteggio_qs": 41.5,
        "tasse_annue_eu": "~2.601 €/anno (tariffa UE)",
        "affitto_mensile": "400–600 €/mese (SSH& garantisce alloggio agli studenti internazionali del primo anno!)",
        "costo_vita_totale": "~850–1.200 €/mese",
        "budget_mensile_val": 1000,
        "budget_rating": 4,
        "ambiti": ["cs", "ai", "cyber"],
        "lauree_triennali": [
            {
                "nome": "B.Sc. Computing Science (specializzazione in Cyber Security!)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["cs", "cyber"],
                "focus": "Uno dei centri di ricerca sulla Cybersecurity e crittografia più rinomati al mondo (Digital Security Group)."
            },
            {
                "nome": "B.Sc. Artificial Intelligence (100% IN INGLESE)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["ai", "robotics"],
                "focus": "Neuroinformatica, interfacce cervello-computer (BCI), reti neurali e robotica cognitiva."
            }
        ],
        "lingua_triennale": "Inglese",
        "has_english_bachelor": True,
        "has_italian_bachelor": False,
        "ammissione": {
            "test_richiesto": "Numerus Fixus per AI e Computing Science",
            "soglia_indicativa": "Test di matematica e selezione su dossier",
            "scadenze": "15 GENNAIO",
            "requisiti_lingua": "Inglese B2/C1 (Cambridge First accettato con punteggio alto)",
            "procedura": "Studielink -> portale Radboud -> ranking number",
            "difficolta": 3
        },
        "approccio_didattico": "Campus verde splendido, laboratori di crittografia e neuroscienze avanzatissimi.",
        "qualita_vita": "Nijmegen è la città più antica d'Olanda, molto accogliente e rilassata, piena di natura.",
        "soddisfazione_studenti": "9.2/10 (spesso votata come la migliore università generalista d'Olanda dagli studenti).",
        "rapporto_studio_vita": "Ottimo: l'università offre assistenza reale per trovare casa!",
        "borse_sussidi": "DUO finance olandese.",
        "fit_score": 9.3,
        "fit_note": "⭐ ECCELLENZA PER CYBERSECURITY E AI: Radboud è famosissima per la sicurezza informatica (Digital Security Group) e per l'AI. Inoltre offre un programma di garanzia alloggio per gli internazionali!",
        "punti_forza": ["Centro di ricerca leader mondiale in Cybersecurity", "BSc in AI di altissimo profilo", "Garanzia di alloggio per internazionali al 1° anno", "Città universitaria vivibile"],
        "punti_deboli": ["Scadenza 15 Gennaio per Numerus Fixus"],
        "url": "https://www.ru.nl"
    },
    {
        "id": "maastricht",
        "nome": "Maastricht University",
        "citta": "Maastricht",
        "paese": "Paesi Bassi",
        "bandiera": "🇳🇱",
        "lat": 50.8497,
        "lng": 5.6889,
        "qs2027": 256,
        "qs2026": 256,
        "punteggio_qs": 40.5,
        "tasse_annue_eu": "~2.601 €/anno (tariffa UE)",
        "affitto_mensile": "400–650 €/mese",
        "costo_vita_totale": "~900–1.250 €/mese",
        "budget_mensile_val": 1050,
        "budget_rating": 3,
        "ambiti": ["ai", "cs", "robotics"],
        "lauree_triennali": [
            {
                "nome": "B.Sc. Data Science and Artificial Intelligence (100% IN INGLESE)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["ai", "cs", "robotics"],
                "focus": "Interamente basato sul metodo 'Project-Centred Learning': ogni semestre sviluppi un progetto software/AI concreto in team."
            },
            {
                "nome": "B.Sc. Computer Science",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["cs", "ce"],
                "focus": "Sistemi distribuiti, ingegneria del software, algoritmi applicati."
            }
        ],
        "lingua_triennale": "Inglese",
        "has_english_bachelor": True,
        "has_italian_bachelor": False,
        "ammissione": {
            "test_richiesto": "Matching procedure e valutazione requisiti matematici",
            "soglia_indicativa": "Matematica a livello avanzato (voto superiore ≥ 7.5 o test OMPT-F)",
            "scadenze": "1 Maggio (Non ha Numerus Fixus rigido al 15 gennaio!)",
            "requisiti_lingua": "IELTS 6.0 / Cambridge B2 First o C1",
            "procedura": "Studielink -> caricamento voti e colloquio motivazionale online",
            "difficolta": 2
        },
        "approccio_didattico": "Pionieri del Problem-Based Learning (PBL) in Europa: niente lezioni frontali noiose, solo gruppi di discussione da 12-14 studenti guidati da tutor.",
        "qualita_vita": "Maastricht è splendida, al confine tra Belgio e Germania (a 30 min da Aquisgrana e Liegi).",
        "soddisfazione_studenti": "9.0/10.",
        "rapporto_studio_vita": "Didattica interattiva, città vivibile e multiculturale.",
        "borse_sussidi": "DUO finance olandese.",
        "fit_score": 9.2,
        "fit_note": "Grande vantaggio: il Bachelor in Data Science and AI NON ha il vincolo rigido del 15 gennaio, si applica con più calma (fino a maggio) e la didattica è tutta a progetti pratici (PCL)!",
        "punti_forza": ["Metodo Project-Centred Learning (tanta pratica)", "Nessun Numerus Fixus limitante (scadenza a Maggio)", "Posizione transfrontaliera (Olanda, Belgio, Germania)", "Città bellissima"],
        "punti_deboli": ["Costi di vita comunque olandesi"],
        "url": "https://www.maastrichtuniversity.nl"
    }
]
