# -*- coding: utf-8 -*-
NORDIC_UNIS = [
    # ─── DANIMARCA ──────────────────────────────────────────────────────────
    {
        "id": "aau",
        "nome": "Aalborg University (AAU)",
        "citta": "Aalborg",
        "paese": "Danimarca",
        "bandiera": "🇩🇰",
        "lat": 57.0122,
        "lng": 9.9723,
        "qs2027": 336,
        "qs2026": 341,
        "punteggio_qs": 36.2,
        "tasse_annue_eu": "0 € / ANNO (GRATIS al 100% per cittadini dell'Unione Europea)",
        "affitto_mensile": "300–450 €/mese (Aalborg è la città universitaria più economica di Danimarca, alloggi garantiti tramite AKU-Aalborg!)",
        "costo_vita_totale": "~800–1.000 €/mese totali",
        "budget_mensile_val": 900,
        "budget_rating": 5,
        "ambiti": ["cs", "ce", "ai", "robotics", "embedded", "other_eng"],
        "lauree_triennali": [
            {
                "nome": "B.Sc. Electronic and Electrical Engineering (100% IN INGLESE)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["embedded", "robotics", "ce"],
                "focus": "Fortissimo su sistemi embedded, microcontrollori, elaborazione segnali e sensoristica avanzata."
            },
            {
                "nome": "B.Sc. Robotics and Automation Engineering (English track)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["robotics", "ai", "embedded"],
                "focus": "Robotica autonoma, cinematica, visione artificiale (OpenCV), controllo motori e sistemi real-time. Perfetto per la RoboCup!"
            },
            {
                "nome": "B.Sc. Chemical / Mechanical / Sustainable Engineering",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["other_eng"],
                "focus": "Corsi in inglese per amici interessati a meccanica e nuove energie."
            }
        ],
        "lingua_triennale": "Inglese (tutti i corsi sopra sono 100% in inglese)",
        "has_english_bachelor": True,
        "has_italian_bachelor": False,
        "ammissione": {
            "test_richiesto": "Ammissione 'Quota 2' basata su dossier motivazionale, curriculum tecnico (ITIS + RoboCup!), e voto di matematica",
            "soglia_indicativa": "Diploma di maturità con almeno 7/10 in Matematica (Livello A/B danese)",
            "scadenze": "15 MARZO (ore 12:00) tramite il portale nazionale danese Optagelse.dk!",
            "requisiti_lingua": "English B (IELTS ≥ 6.5 o Cambridge First con grado B/A o C1 Advanced)",
            "procedura": "1. Candidatura su optagelse.dk entro il 15 marzo (Quota 2)\n2. Allega diploma/transcript ITIS Rossi, certificato Cambridge, lettera motivazionale e progetti RoboCup/GitHub\n3. Esito comunicato il 28 luglio",
            "difficolta": 2
        },
        "approccio_didattico": "L'inventore dell'Aalborg PBL Model (Problem-Based Learning): il 50% di ogni semestre è dedicato a un progetto reale commissionato dall'industria svolto in gruppo di 4-6 persone con stanza/ufficio assegnata al team!",
        "qualita_vita": "Città giovane, vivibilissima, sicura, piena di canali e parchi. Tutti parlano inglese fluidamente.",
        "soddisfazione_studenti": "9.5/10. Il modello PBL elimina l'ansia da esame individuale e prepara direttamente al lavoro in team.",
        "rapporto_studio_vita": "Spettacolare: il lavoro di gruppo si fa di giorno, lasciando le serate libere.",
        "borse_sussidi": "⭐ SUSSIDIO STATALE DANESE (SU): se lavori almeno 10-12 ore/settimana, lo stato danese ti paga ~850 €/mese netti di borsa a fondo perduto!",
        "fit_score": 9.8,
        "fit_note": "🎯 FIT PERFETTO (#1 IN EUROPA PER GIOVANNI): Rette 0 €, alloggi a 350€, didattica 100% basata su progetti pratici in team (PBL), corso ideale in Robotics/Embedded e con 10h di lavoro part-time sblocchi la borsa SU da ~850€/mese!",
        "punti_forza": ["Università GRATUITA (0 € tasse)", "Borsa statale danese SU (~850 €/mese) se lavori 10-12h/sett.", "Metodo didattico pratico PBL (50% progetti di laboratorio)", "Affitti bassi con alloggio garantito (AKU-Aalborg)", "Valore enorme per il tuo background RoboCup"],
        "punti_deboli": ["Clima invernale nordico (buio e vento)", "Città non gigante (120k abitanti)"],
        "url": "https://www.en.aau.dk"
    },
    {
        "id": "sdu",
        "nome": "University of Southern Denmark (SDU)",
        "citta": "Odense",
        "paese": "Danimarca",
        "bandiera": "🇩🇰",
        "lat": 55.3686,
        "lng": 10.4285,
        "qs2027": 350,
        "qs2026": 361,
        "punteggio_qs": 35.4,
        "tasse_annue_eu": "0 € / ANNO (GRATIS per cittadini UE)",
        "affitto_mensile": "320–480 €/mese (alloggi universitari disponibili)",
        "costo_vita_totale": "~850–1.050 €/mese",
        "budget_mensile_val": 950,
        "budget_rating": 5,
        "ambiti": ["robotics", "embedded", "ai", "ce", "other_eng"],
        "lauree_triennali": [
            {
                "nome": "B.Eng. Robot Systems (100% IN INGLESE - Odense)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3.5 anni (210 ECTS, include semestre di tirocinio retribuito)",
                "ambiti": ["robotics", "embedded", "ai"],
                "focus": "Odense è la capitale europea dei cobot (Universal Robots, MiR)! Il corso copre cinematica, ROS (Robot Operating System), computer vision, driver embedded e droni autonomi."
            },
            {
                "nome": "B.Eng. Mechatronics (Sønderborg Campus)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3.5 anni (210 ECTS)",
                "ambiti": ["robotics", "embedded", "other_eng"],
                "focus": "Sistemi meccatronici avanzati, nanotecnologie, azionamenti elettrici ed elettronica di potenza."
            },
            {
                "nome": "B.Sc. Software Engineering",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["cs", "ce"],
                "focus": "Architetture software complesse per sistemi industriali e cloud."
            }
        ],
        "lingua_triennale": "Inglese (tutti i corsi sopra sono 100% in inglese)",
        "has_english_bachelor": True,
        "has_italian_bachelor": False,
        "ammissione": {
            "test_richiesto": "Ammissione Quota 2 con colloquio online e portfolio tecnico (ideale per la tua RoboCup)",
            "soglia_indicativa": "Diploma tecnico ITIS, matematica livello intermedio/avanzato",
            "scadenze": "15 MARZO (Optagelse.dk)",
            "requisiti_lingua": "Cambridge First B2 / C1 o IELTS 6.5",
            "procedura": "Domanda su optagelse.dk entro il 15 marzo; test logico/matematico online di ateneo",
            "difficolta": 2
        },
        "approccio_didattico": "SDU Odense collabora a stretto contatto con l'Odense Robotics Cluster (oltre 130 aziende di robotica nate intorno all'università). Moltissima pratica di laboratorio.",
        "qualita_vita": "Odense è una città storica deliziosa (città natale di Hans Christian Andersen), verde, piste ciclabili spettacolari e collegamenti veloci con Copenaghen.",
        "soddisfazione_studenti": "9.4/10. Sbocchi di lavoro in robotica immediati.",
        "rapporto_studio_vita": "Eccellente: unisce vita rilassata a un ecosistema industriale di robotica unico.",
        "borse_sussidi": "Sussidio danese SU (~850 €/mese lavorando 10-12h/sett.) + tirocini aziendali retribuiti.",
        "fit_score": 9.9,
        "fit_note": "🎯 LA MECCA MONDIALE DELLA ROBOTICA: Odense è la capitale europea dei robot collaborativi. Il corso 'Robot Systems' in inglese sembra fatto su misura per te e la tua passione per la RoboCup. Tasse 0€ e borsa SU danese inclusa!",
        "punti_forza": ["Capitale europea della robotica (hub di Universal Robots e MiR)", "B.Eng. Robot Systems 100% in inglese", "Università 100% GRATUITA (0 € tasse)", "Borsa SU danese da ~850 €/mese accessibile", "Semestre di tirocinio retribuito integrato"],
        "punti_deboli": ["Scadenza il 15 Marzo"],
        "url": "https://www.sdu.dk"
    },
    {
        "id": "dtu",
        "nome": "Technical University of Denmark (DTU)",
        "citta": "Lyngby (Copenaghen)",
        "paese": "Danimarca",
        "bandiera": "🇩🇰",
        "lat": 55.7860,
        "lng": 12.5230,
        "qs2027": 105,
        "qs2026": 107,
        "punteggio_qs": 62.8,
        "tasse_annue_eu": "0 € / ANNO (GRATIS per studenti UE)",
        "affitto_mensile": "450–700 €/mese (area metropolitana di Copenaghen)",
        "costo_vita_totale": "~1.000–1.350 €/mese",
        "budget_mensile_val": 1150,
        "budget_rating": 3,
        "ambiti": ["ce", "cs", "embedded", "robotics", "other_eng"],
        "lauree_triennali": [
            {
                "nome": "B.Sc. General Engineering (100% IN INGLESE)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["ce", "embedded", "cs", "other_eng"],
                "focus": "Ha 4 indirizzi tematici di specializzazione, tra cui 'Cyber Systems' (informatica, reti, algoritmi, AI) e 'Future Energy'."
            }
        ],
        "lingua_triennale": "Inglese (General Engineering)",
        "has_english_bachelor": True,
        "has_italian_bachelor": False,
        "ammissione": {
            "test_richiesto": "Quota 2 su Optagelse.dk: valutazione voti di matematica, fisica e chimica",
            "soglia_indicativa": "Requisiti di matematica e fisica ad alto livello",
            "scadenze": "15 MARZO (ore 12:00)",
            "requisiti_lingua": "IELTS 6.5 o Cambridge First/Advanced",
            "procedura": "Domanda nazionale danese tramite optagelse.dk",
            "difficolta": 3
        },
        "approccio_didattico": "Politecnico nordeuropeo di punta. Grandi laboratori, fablab, incubatore studentesco DTU Skylab (tra i migliori incubatori universitari d'Europa).",
        "qualita_vita": "Campus a Lyngby (a 20 min di treno dal centro di Copenaghen). Città ciclabile, cosmopolita e innovativa.",
        "soddisfazione_studenti": "9.1/10.",
        "rapporto_studio_vita": "Molto stimolante, ambiente internazionale vivace.",
        "borse_sussidi": "Borsa statale danese SU (~850 €/mese lavorando 10-12h/sett.). Rette = 0 €.",
        "fit_score": 9.2,
        "fit_note": "Il politecnico più prestigioso di Danimarca (#105 al mondo). Il corso General Engineering con indirizzo Cyber Systems è un'eccellenza assoluta a costo zero di retta.",
        "punti_forza": ["#105 al mondo QS", "Rette 0 € per cittadini UE", "DTU Skylab per startup e hardware", "Borsa SU danese disponibile"],
        "punti_deboli": ["Costo alloggio a Copenaghen più alto di Aalborg e Odense", "Scadenza il 15 Marzo"],
        "url": "https://www.dtu.dk"
    },
    {
        "id": "aarhus",
        "nome": "Aarhus University",
        "citta": "Aarhus",
        "paese": "Danimarca",
        "bandiera": "🇩🇰",
        "lat": 56.1682,
        "lng": 10.2032,
        "qs2027": 143,
        "qs2026": 143,
        "punteggio_qs": 54.8,
        "tasse_annue_eu": "0 € / ANNO (GRATIS)",
        "affitto_mensile": "350–550 €/mese",
        "costo_vita_totale": "~900–1.200 €/mese",
        "budget_mensile_val": 1000,
        "budget_rating": 4,
        "ambiti": ["cs", "ce", "other_eng"],
        "lauree_triennali": [
            {
                "nome": "B.Sc. Cognitive Science (100% IN INGLESE)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["ai", "cs"],
                "focus": "Intersezione tra modelli computazionali di intelligenza artificiale, neuroscienze e linguistica computazionale."
            }
        ],
        "lingua_triennale": "Inglese (Cognitive Science)",
        "has_english_bachelor": True,
        "has_italian_bachelor": False,
        "ammissione": {
            "test_richiesto": "Quota 2 Optagelse.dk",
            "soglia_indicativa": "Buona media e motivazione",
            "scadenze": "15 MARZO",
            "requisiti_lingua": "Inglese B2/C1",
            "procedura": "Domanda su optagelse.dk",
            "difficolta": 2
        },
        "approccio_didattico": "Campus integrato in un bellissimo parco collinare (UniParken).",
        "qualita_vita": "Aarhus è la seconda città danese, giovane e vivace (Capitale europea della cultura).",
        "soddisfazione_studenti": "9.0/10.",
        "rapporto_studio_vita": "Equilibrato e sereno.",
        "borse_sussidi": "Borsa SU danese (~850 €/mese con lavoro 10-12h).",
        "fit_score": 8.8,
        "fit_note": "Ateneo top 150 mondiale, rette gratuite e ottima qualità della vita.",
        "punti_forza": ["Top 150 al mondo", "Università gratuita", "Borsa SU danese", "Città bellissima"],
        "punti_deboli": ["Offerta triennale in inglese focalizzata su Cognitive Science"],
        "url": "https://international.au.dk"
    },

    # ─── SVEZIA ─────────────────────────────────────────────────────────────
    {
        "id": "kth",
        "nome": "KTH Royal Institute of Technology",
        "citta": "Stoccolma",
        "paese": "Svezia",
        "bandiera": "🇸🇪",
        "lat": 59.3498,
        "lng": 18.0707,
        "qs2027": 82,
        "qs2026": 73,
        "punteggio_qs": 69.8,
        "tasse_annue_eu": "0 € / ANNO (GRATIS per cittadini UE)",
        "affitto_mensile": "450–750 €/mese (campus Kista/Valhallavägen)",
        "costo_vita_totale": "~950–1.350 €/mese",
        "budget_mensile_val": 1150,
        "budget_rating": 3,
        "ambiti": ["cs", "ce", "embedded", "cyber", "other_eng"],
        "lauree_triennali": [
            {
                "nome": "B.Sc. Information and Communication Technology (100% IN INGLESE)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["cs", "ce", "embedded", "cyber"],
                "focus": "Sede al KTH Campus Kista (il più grande polo ICT del Nord Europa, sede di Ericsson). Copre software, sistemi embedded, protocolli internet, sicurezza e architetture cloud."
            }
        ],
        "lingua_triennale": "Inglese (BSc ICT)",
        "has_english_bachelor": True,
        "has_italian_bachelor": False,
        "ammissione": {
            "test_richiesto": "Ammissione centralizzata svedese su Universityadmissions.se (valutazione voti diploma e matematica avanzata)",
            "soglia_indicativa": "Media voti diploma ITIS ≥ 8/10 e Matematica livello 4 svedese",
            "scadenze": "15 GENNAIO per il round internazionale di Universityadmissions.se!",
            "requisiti_lingua": "English 6 (IELTS ≥ 6.5 o Cambridge Advanced C1 / First con punteggio alto)",
            "procedura": "1. Candidatura su universityadmissions.se entro il 15 gennaio\n2. Caricamento documenti e transcript voti entro il 1° febbraio\n3. Risultati ad aprile",
            "difficolta": 3
        },
        "approccio_didattico": "Didattica tecnologica all'avanguardia con fortissima collaborazione con l'industria svedese (Ericsson, Spotify, Scania, ABB).",
        "qualita_vita": "Stoccolma è una delle capitali più vivibili e verdi al mondo, pulita, sicura e cosmopolita.",
        "soddisfazione_studenti": "9.1/10. Reputazione accademica altissima in tutta la Scandinavia.",
        "rapporto_studio_vita": "Molto stimolante, campus ben organizzato.",
        "borse_sussidi": "Rette 0 € per cittadini UE. Lavoro part-time consentito senza limiti.",
        "fit_score": 9.3,
        "fit_note": "Il politecnico più prestigioso di Svezia (#82 al mondo). Il Bachelor in Information & Communication Technology a Kista è 100% in inglese e non paghi un solo euro di tasse universitarie!",
        "punti_forza": ["#82 al mondo QS", "Rette universitarie = 0 €", "Campus Kista nel cuore dell'ecosistema tech svedese", "Triennale 100% in inglese"],
        "punti_deboli": ["Scadenza il 15 Gennaio su universityadmissions.se", "Costo della vita a Stoccolma medio-alto"],
        "url": "https://www.kth.se/en"
    },
    {
        "id": "chalmers",
        "nome": "Chalmers University of Technology",
        "citta": "Göteborg",
        "paese": "Svezia",
        "bandiera": "🇸🇪",
        "lat": 57.6888,
        "lng": 11.9782,
        "qs2027": 137,
        "qs2026": 129,
        "punteggio_qs": 55.8,
        "tasse_annue_eu": "0 € / ANNO (GRATIS per cittadini UE)",
        "affitto_mensile": "400–650 €/mese",
        "costo_vita_totale": "~900–1.250 €/mese",
        "budget_mensile_val": 1050,
        "budget_rating": 3,
        "ambiti": ["cs", "ce", "embedded", "robotics", "other_eng"],
        "lauree_triennali": [
            {
                "nome": "B.Sc. Software Engineering and Management (congiunto con Uni Gothenburg)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["cs", "ce"],
                "focus": "Ingegneria del software orientata a progetti industriali, metodologie agili (SCRUM), architetture distribuite."
            }
        ],
        "lingua_triennale": "Inglese",
        "has_english_bachelor": True,
        "has_italian_bachelor": False,
        "ammissione": {
            "test_richiesto": "Universityadmissions.se",
            "soglia_indicativa": "Diploma e matematica avanzata",
            "scadenze": "15 GENNAIO",
            "requisiti_lingua": "IELTS 6.5 o Cambridge C1/B2 alto",
            "procedura": "Candidatura centralizzata svedese online",
            "difficolta": 3
        },
        "approccio_didattico": "Forte legame con Volvo, Polestar ed Ericsson. Laboratori robotici e automobilistici eccezionali.",
        "qualita_vita": "Göteborg è la città più accogliente di Svezia, marittima, piena di caffè e cultura giovanile.",
        "soddisfazione_studenti": "9.2/10.",
        "rapporto_studio_vita": "Ottimo: atmosfera meno formale e più calorosa rispetto alla capitale.",
        "borse_sussidi": "Rette 0 € UE.",
        "fit_score": 9.1,
        "fit_note": "Ateneo tecnologico svedese di vertice. Göteborg è un polo fantastico per veicoli autonomi e software. Zero tasse universitarie.",
        "punti_forza": ["Zero tasse universitarie", "Polo automotive e veicoli autonomi (Volvo/Polestar)", "Città marittima stupenda"],
        "punti_deboli": ["Scadenza il 15 Gennaio"],
        "url": "https://www.chalmers.se/en"
    },
    {
        "id": "linkoping",
        "nome": "Linköping University (LiU)",
        "citta": "Linköping",
        "paese": "Svezia",
        "bandiera": "🇸🇪",
        "lat": 58.4019,
        "lng": 15.5780,
        "qs2027": 304,
        "qs2026": 304,
        "punteggio_qs": 37.5,
        "tasse_annue_eu": "0 € / ANNO (GRATIS per cittadini UE)",
        "affitto_mensile": "320–500 €/mese (alloggi studenteschi garantiti a Ryd!)",
        "costo_vita_totale": "~800–1.050 €/mese",
        "budget_mensile_val": 950,
        "budget_rating": 4,
        "ambiti": ["cs", "ai", "other_eng"],
        "lauree_triennali": [
            {
                "nome": "B.Sc. in Experimental and Industrial Technologies / IT tracks",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["cs", "other_eng"],
                "focus": "Polo pionieristico per l'informatica e l'AI in Svezia (sede del supercomputer Berzelius per il deep learning)."
            }
        ],
        "lingua_triennale": "Inglese",
        "has_english_bachelor": True,
        "has_italian_bachelor": False,
        "ammissione": {
            "test_richiesto": "Universityadmissions.se",
            "soglia_indicativa": "Diploma e matematica",
            "scadenze": "15 GENNAIO",
            "requisiti_lingua": "Inglese B2/C1",
            "procedura": "Domanda online centralizzata svedese",
            "difficolta": 2
        },
        "approccio_didattico": "Famosa per la didattica interdisciplinare e per ospitare il centro di ricerca WASP (Wallenberg AI, Autonomous Systems and Software Program).",
        "qualita_vita": "Linköping è la città universitaria svedese per eccellenza: il quartiere di Ryd è abitato quasi esclusivamente da studenti in bicicletta.",
        "soddisfazione_studenti": "9.3/10. Vita comunitaria imbattibile.",
        "rapporto_studio_vita": "Tranquillo, sano e accogliente.",
        "borse_sussidi": "Rette 0 €.",
        "fit_score": 9.0,
        "fit_note": "Sede del più potente supercomputer AI della Svezia e del programma WASP per i sistemi autonomi. Affitti bassissimi e zero tasse.",
        "punti_forza": ["Zero tasse universitarie", "Centro nevralgico della ricerca AI svedese (WASP)", "Costi bassi per gli alloggi (quartiere Ryd)", "Vera città-campus"],
        "punti_deboli": ["Scadenza il 15 Gennaio"],
        "url": "https://liu.se/en"
    },
    {
        "id": "malmo",
        "nome": "Malmö University",
        "citta": "Malmö",
        "paese": "Svezia",
        "bandiera": "🇸🇪",
        "lat": 55.6111,
        "lng": 12.9944,
        "qs2027": 650,
        "qs2026": 680,
        "punteggio_qs": 29.0,
        "tasse_annue_eu": "0 € / ANNO (GRATIS)",
        "affitto_mensile": "380–580 €/mese",
        "costo_vita_totale": "~850–1.150 €/mese",
        "budget_mensile_val": 1000,
        "budget_rating": 4,
        "ambiti": ["cs", "ai", "gamedev"],
        "lauree_triennali": [
            {
                "nome": "B.Sc. Computer Science: Applied Data Science (100% IN INGLESE)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["cs", "ai"],
                "focus": "Machine learning, analisi di grandi volumi di dati, programmazione Python/C++, sviluppo software moderno."
            },
            {
                "nome": "B.Sc. Interaction Design / Game Media",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["gamedev", "cs"],
                "focus": "Interazione uomo-macchina, interfacce utente, prototipazione rapida per videogiochi e app interattive."
            }
        ],
        "lingua_triennale": "Inglese (tutti i corsi sopra sono 100% in inglese)",
        "has_english_bachelor": True,
        "has_italian_bachelor": False,
        "ammissione": {
            "test_richiesto": "Universityadmissions.se",
            "soglia_indicativa": "Diploma e matematica",
            "scadenze": "15 GENNAIO",
            "requisiti_lingua": "IELTS 6.5 o Cambridge",
            "procedura": "Domanda su universityadmissions.se",
            "difficolta": 2
        },
        "approccio_didattico": "Moderno, urbano, inclusivo, con forte collegamento al Game Habitat della regione Öresund.",
        "qualita_vita": "Malmö è collegata a Copenaghen dal famoso ponte Öresund (35 min di treno per la capitale danese!).",
        "soddisfazione_studenti": "8.8/10.",
        "rapporto_studio_vita": "Città cosmopolita con un costo della vita molto più basso di Copenaghen pur essendole attaccata.",
        "borse_sussidi": "Rette 0 €.",
        "fit_score": 8.9,
        "fit_note": "A 35 minuti di treno da Copenaghen ma con affitti svedesi più bassi e rette 0€. Il Bachelor in Applied Data Science in inglese è molto pratico.",
        "punti_forza": ["Rette 0 €", "A 35 min di treno da Copenaghen attraverso il ponte Öresund", "Polo del game development nordico"],
        "punti_deboli": ["Scadenza il 15 Gennaio"],
        "url": "https://mau.se/en"
    },

    # ─── FINLANDIA ──────────────────────────────────────────────────────────
    {
        "id": "aalto",
        "nome": "Aalto University",
        "citta": "Espoo (Helsinki)",
        "paese": "Finlandia",
        "bandiera": "🇫🇮",
        "lat": 60.1870,
        "lng": 24.8307,
        "qs2027": 113,
        "qs2026": 109,
        "punteggio_qs": 60.5,
        "tasse_annue_eu": "0 € / ANNO (GRATIS per tutti i cittadini dell'Unione Europea)",
        "affitto_mensile": "350–550 €/mese (alloggi convenzionati HOAS e AYY per studenti proprio sul campus di Otaniemi!)",
        "costo_vita_totale": "~850–1.150 €/mese",
        "budget_mensile_val": 1000,
        "budget_rating": 4,
        "ambiti": ["cs", "ce", "ai", "robotics", "embedded", "other_eng"],
        "lauree_triennali": [
            {
                "nome": "B.Sc. Computational Engineering (100% IN INGLESE)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["cs", "ai", "ce"],
                "focus": "Simulazione computazionale, algoritmi numerici, intelligenza artificiale applicata all'ingegneria, machine learning."
            },
            {
                "nome": "B.Sc. Data Science (100% IN INGLESE)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["ai", "cs"],
                "focus": "Machine learning, statistica avanzata, visualizzazione dati, deep learning e big data engineering."
            },
            {
                "nome": "B.Sc. Digital Systems and Design (100% IN INGLESE)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["embedded", "ce", "robotics"],
                "focus": "Sistemi embedded, microelettronica, automazione e design di sistemi autonomi. Tagliato su misura per chi ama l'hardware!"
            },
            {
                "nome": "B.Sc. Quantum Technology (100% IN INGLESE)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["cs", "other_eng"],
                "focus": "Quantum computing, fisica computazionale e nanoelettronica (Aalto ospita il computer quantistico finlandese Helmi)."
            }
        ],
        "lingua_triennale": "Inglese (tutti i 4 Bachelor tecnologici sono 100% in inglese)",
        "has_english_bachelor": True,
        "has_italian_bachelor": False,
        "ammissione": {
            "test_richiesto": "Ammissione basata sui punteggi del SAT (Sezione Matematica ≥ 650-700/800) OPPURE selezione su diploma e pagelle",
            "soglia_indicativa": "Un buon punteggio nel SAT Math garantisce l'ammissione!",
            "scadenze": "CRUCIALE: 2ª settimana di GENNAIO sul portale nazionale finlandese Opintopolku.fi (Studyinfo.fi)!",
            "requisiti_lingua": "IELTS 6.5 / Cambridge C1 Advanced o First con grado elevato / SAT",
            "procedura": "1. Domanda su Studyinfo.fi a inizio gennaio\n2. Invio punteggi SAT o transcript scolastico\n3. Esiti pubblicati in primavera",
            "difficolta": 3
        },
        "approccio_didattico": "Campus di Otaniemi: una meraviglia progettata da Alvar Aalto. Aalto Design Factory, laboratori aperti 24/7, Aalto Startup Center (dove è nata Slush, il più grande evento startup tech d'Europa!).",
        "qualita_vita": "La Finlandia è il Paese più felice del mondo per 7 anni consecutivi: sicurezza assoluta, natura incontaminata, metro diretta per Helsinki.",
        "soddisfazione_studenti": "9.6/10. Clima studentesco caloroso e collaborativo, saune studentesche gratuite nel campus.",
        "rapporto_studio_vita": "Straordinario: pranzare nei campus costa solo 2,95 € grazie al sussidio KELA!",
        "borse_sussidi": "Rette universitarie 0 € per cittadini UE. Pasti KELA a 2,95 € in tutto il campus.",
        "fit_score": 9.7,
        "fit_note": "⭐ GIOIELLO NORDICO PER HARDWARE, AI E STARTUP: 4 triennali 100% in inglese (tra cui Digital Systems and Design e Data Science), tasse 0€, campus di Otaniemi con fablab aperti 24/7 e mensa a 2,95€!",
        "punti_forza": ["Rette universitarie = 0 €", "4 triennali tecnologiche 100% in inglese", "Campus Otaniemi culla dell'innovazione europea", "Pasti completi al campus a 2,95 € (sussidio KELA)", "Qualità della vita finlandese al vertice mondiale"],
        "punti_deboli": ["Scadenza anticipata a Gennaio su Studyinfo", "Inverni freddi e bui"],
        "url": "https://www.aalto.fi/en"
    },
    {
        "id": "tampere",
        "nome": "Tampere University",
        "citta": "Tampere",
        "paese": "Finlandia",
        "bandiera": "🇫🇮",
        "lat": 61.4981,
        "lng": 23.7717,
        "qs2027": 436,
        "qs2026": 436,
        "punteggio_qs": 31.5,
        "tasse_annue_eu": "0 € / ANNO (GRATIS)",
        "affitto_mensile": "280–450 €/mese (alloggi TOAS ultra-economici e moderni!)",
        "costo_vita_totale": "~750–950 €/mese",
        "budget_mensile_val": 850,
        "budget_rating": 5,
        "ambiti": ["cs", "ce", "embedded", "robotics", "gamedev", "other_eng"],
        "lauree_triennali": [
            {
                "nome": "B.Sc. Computing and Electrical Engineering (100% IN INGLESE)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["cs", "ce", "embedded", "robotics"],
                "focus": "Sistemi embedded, software engineering, elaborazione segnali, robotica e IoT."
            },
            {
                "nome": "B.Sc. Game Studies and Digital Culture / Software",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["gamedev", "cs"],
                "focus": "Tampere è la capitale finlandese dei videogiochi (Nokia, Remedy, Colossal Order - Cities: Skylines). Ecosistema gaming fortissimo."
            }
        ],
        "lingua_triennale": "Inglese",
        "has_english_bachelor": True,
        "has_italian_bachelor": False,
        "ammissione": {
            "test_richiesto": "Ammissione con punteggi SAT o selezione congiunta finlandese su Studyinfo.fi",
            "soglia_indicativa": "Punteggio SAT Math ≥ 620-650",
            "scadenze": "Metà GENNAIO su Studyinfo.fi",
            "requisiti_lingua": "Inglese B2/C1",
            "procedura": "Domanda online centralizzata a gennaio",
            "difficolta": 2
        },
        "approccio_didattico": "Forte orientamento pratico ingegneristico e polo di eccellenza per il Game Development europeo.",
        "qualita_vita": "Città incastonata tra due laghi, vivibilissima, giovane, capitale mondiale della sauna.",
        "soddisfazione_studenti": "9.4/10. Costo della vita sensibilmente più basso di Helsinki.",
        "rapporto_studio_vita": "Ottimo: alloggi TOAS garantiti e molto economici (280-350€ tutto compreso!).",
        "borse_sussidi": "Rette 0 € per studenti UE + mensa a 2,95 €.",
        "fit_score": 9.4,
        "fit_note": "Ateneo favoloso per game development (Unity/simulazioni) e sistemi embedded. Affitti TOAS a meno di 300€/mese e rette 0€. Con il budget genitori di 600-800€ qui ci vivi benissimo senza pensieri!",
        "punti_forza": ["Rette universitarie 0 €", "Alloggi TOAS modernissimi a 280-350€/mese", "Polo n.1 in Finlandia per Game Dev e software", "Budget 600-800€/mese ampiamente sufficiente"],
        "punti_deboli": ["Scadenza a inizio Gennaio"],
        "url": "https://www.tuni.fi/en"
    },
    {
        "id": "lut",
        "nome": "LUT University (Lappeenranta-Lahti)",
        "citta": "Lappeenranta",
        "paese": "Finlandia",
        "bandiera": "🇫🇮",
        "lat": 61.0500,
        "lng": 28.0900,
        "qs2027": 336,
        "qs2026": 336,
        "punteggio_qs": 36.0,
        "tasse_annue_eu": "0 € / ANNO (GRATIS)",
        "affitto_mensile": "250–400 €/mese (tra i più economici d'Europa)",
        "costo_vita_totale": "~700–900 €/mese",
        "budget_mensile_val": 800,
        "budget_rating": 5,
        "ambiti": ["cs", "ce", "other_eng"],
        "lauree_triennali": [
            {
                "nome": "B.Sc. Software and Systems Engineering (100% IN INGLESE)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["cs", "ce"],
                "focus": "Ingegneria del software moderna, cloud computing, architetture scalabili, sicurezza."
            },
            {
                "nome": "B.Sc. Technology and Engineering Science",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["other_eng", "embedded"],
                "focus": "Ingegneria meccanica, sostenibilità, circuiti e sensoristica."
            }
        ],
        "lingua_triennale": "Inglese",
        "has_english_bachelor": True,
        "has_italian_bachelor": False,
        "ammissione": {
            "test_richiesto": "Selezione tramite SAT o valutazione voti diploma",
            "soglia_indicativa": "Punteggio SAT Math o voto diploma buono",
            "scadenze": "Metà GENNAIO su Studyinfo.fi",
            "requisiti_lingua": "Inglese B2/C1",
            "procedura": "Studyinfo.fi",
            "difficolta": 2
        },
        "approccio_didattico": "Focalizzato su sostenibilità, clean tech e software engineering.",
        "qualita_vita": "Campus affacciato sul lago Saimaa, natura incontaminata, tranquillità totale.",
        "soddisfazione_studenti": "9.1/10.",
        "rapporto_studio_vita": "Costi irrisori: una camera singola in studentato costa 250-320€ tutto incluso.",
        "borse_sussidi": "Rette 0 €.",
        "fit_score": 9.1,
        "fit_note": "Rapporto costi/benefici stellare: Software Engineering 100% in inglese, università gratis e vita da 700€/mese. Il tuo budget familiare basta al 100% anche senza lavorare.",
        "punti_forza": ["Rette 0 €", "Alloggi a 250-320€/mese", "Triennale Software Engineering in inglese", "Copertura completa con 600-800€/mese"],
        "punti_deboli": ["Cittadina piccola nel sud-est della Finlandia"],
        "url": "https://www.lut.fi/en"
    },

    # ─── NORVEGIA ───────────────────────────────────────────────────────────
    {
        "id": "ntnu",
        "nome": "NTNU (Norwegian University of Science and Technology)",
        "citta": "Trondheim",
        "paese": "Norvegia",
        "bandiera": "🇳🇴",
        "lat": 63.4195,
        "lng": 10.4024,
        "qs2027": 292,
        "qs2026": 264,
        "punteggio_qs": 39.1,
        "tasse_annue_eu": "0 € / ANNO (GRATIS per cittadini UE/SEE nelle università pubbliche norvegesi)",
        "affitto_mensile": "450–650 €/mese (studentati SiT convenzionati a Trondheim)",
        "costo_vita_totale": "~950–1.250 €/mese",
        "budget_mensile_val": 1100,
        "budget_rating": 3,
        "ambiti": ["cs", "ce", "robotics", "embedded", "other_eng"],
        "lauree_triennali": [
            {
                "nome": "B.Sc. / Nordic Engineering Tracks (Informatics & Cybernetics)",
                "lingua": "🇬🇧 Inglese / Moduli scandinavi",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["robotics", "ce", "embedded"],
                "focus": "Polo leggendario per la cibernetica ingegneristica (Department of Engineering Cybernetics), droni marini, robotica autonoma e navigazione."
            }
        ],
        "lingua_triennale": "Inglese (moduli e corsi internazionali)",
        "has_english_bachelor": True,
        "has_italian_bachelor": False,
        "ammissione": {
            "test_richiesto": "Samordna opptak (ammissione centralizzata norvegese) basata su diploma e matematica R2",
            "soglia_indicativa": "Diploma di maturità con ottimi voti in scienze e matematica",
            "scadenze": "15 MARZO (per candidati con titolo straniero)",
            "requisiti_lingua": "Inglese B2/C1",
            "procedura": "Domanda su samordnaopptak.no allegando transcript",
            "difficolta": 3
        },
        "approccio_didattico": "L'ateneo tecnologico più importante della Norvegia. Grandi laboratori di robotica marina, robotica medica e intelligenza artificiale.",
        "qualita_vita": "Trondheim è una vera città universitaria (Samfundet, il più grande club studentesco del mondo gestito al 100% da studenti).",
        "soddisfazione_studenti": "9.5/10. Spirito di appartenenza leggendario.",
        "rapporto_studio_vita": "Molto stimolante; i salari per i lavori part-time sono i più alti d'Europa (~18-20€/h).",
        "borse_sussidi": "Rette 0 € per studenti SEE. Accesso ai prestiti/borse Lånekassen lavorando part-time.",
        "fit_score": 9.0,
        "fit_note": "La cibernetica e la robotica a NTNU sono di caratura mondiale. Nessuna retta universitaria e paghe orarie da ~19€/ora che rendono facilissimo mantenersi con poche ore settimanali.",
        "punti_forza": ["Rette 0 € per cittadini UE", "Dipartimento di Cibernetica e Robotica famoso nel mondo", "Paghe part-time altissime (18-20€/h)", "Città studentesca fantastica"],
        "punti_deboli": ["Alcuni corsi triennali richiedono integrazione linguistica norvegese"],
        "url": "https://www.ntnu.edu"
    }
]
