# -*- coding: utf-8 -*-
DE_AT_BE_IE_UNIS = [
    # ─── GERMANIA ───────────────────────────────────────────────────────────
    {
        "id": "saarland",
        "nome": "Saarland University (UdS)",
        "citta": "Saarbrücken",
        "paese": "Germania",
        "bandiera": "🇩🇪",
        "lat": 49.2564,
        "lng": 7.0425,
        "qs2027": 450,
        "qs2026": 450,
        "punteggio_qs": 32.5,
        "tasse_annue_eu": "~300 €/semestre (~600 €/anno, include il Semesterticket per viaggiare gratis su tutti i treni e bus!)",
        "affitto_mensile": "280–420 €/mese (Saarbrücken è una delle città universitarie più economiche di Germania!)",
        "costo_vita_totale": "~750–950 €/mese",
        "budget_mensile_val": 850,
        "budget_rating": 5,
        "ambiti": ["cs", "ai", "cyber", "ce"],
        "lauree_triennali": [
            {
                "nome": "B.Sc. Computer Science (100% IN INGLESE)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["cs", "ai", "cyber"],
                "focus": "Uno dei centri di Computer Science e Intelligenza Artificiale più potenti al mondo: Max Planck Institute for Informatics, Max Planck for Software Systems, CISPA Helmholtz Center for Information Security e DFKI (German Research Center for Artificial Intelligence) tutti sul campus!"
            },
            {
                "nome": "B.Sc. Cybersecurity (English modules)",
                "lingua": "🇬🇧 Inglese / Tedesco",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["cyber", "cs"],
                "focus": "Legato al CISPA (uno dei centri europei d'eccellenza per la sicurezza cibernetica)."
            }
        ],
        "lingua_triennale": "Inglese (BSc Computer Science 100% in inglese)",
        "has_english_bachelor": True,
        "has_italian_bachelor": False,
        "ammissione": {
            "test_richiesto": "Ammissione diretta basata sui voti del diploma di maturità e matematica",
            "soglia_indicativa": "Diploma di scuola superiore (Abitur equivalency) con buone valutazioni matematiche",
            "scadenze": "15 LUGLIO (molto tempo a disposizione rispetto a Olanda e Danimarca!)",
            "requisiti_lingua": "Inglese B2/C1 (Cambridge First accettato, o IELTS 6.0/6.5)",
            "procedura": "1. Domanda su Uni-Assist o direttamente sul portale SIM della Saarland University\n2. Caricamento diploma e certificato di lingua\n3. Ammissione comunicata in estate",
            "difficolta": 2
        },
        "approccio_didattico": "Densità di ricercatori in Computer Science impareggiabile in Europa continentale. Opportunità di fare contratti HiWi (assistente retribuito nei laboratori Max Planck a 14-16€/h) fin dal primo anno.",
        "qualita_vita": "Città tranquilla al confine con la Francia, verde, rilassata, con un costo della vita bassissimo.",
        "soddisfazione_studenti": "9.3/10 per gli studenti di Computer Science.",
        "rapporto_studio_vita": "Ideale: il Semesterticket incluso nella tassa ti permette di viaggiare gratis su tutti i treni regionali in Germania!",
        "borse_sussidi": "Rette 0 € (solo quota semestrale con trasporti inclusi). Minijob e contratti HiWi nei centri di ricerca (~538–800 €/mese).",
        "fit_score": 9.7,
        "fit_note": "⭐ LA GEMMA SEGRETA DELLA GERMANIA: Bachelor in Computer Science 100% IN INGLESE, sul campus hanno i Max Planck Institutes, DFKI per l'AI e CISPA per la cybersecurity. Costo della vita bassissimo (280-350€/camera), trasporti gratis e scadenza comoda a Luglio!",
        "punti_forza": ["B.Sc. Computer Science 100% in inglese", "Hub europeo dell'AI e Cybersecurity (Max Planck, DFKI, CISPA)", "Affitti tra i più bassi di Germania (280-400€)", "Semesterticket: treni gratis in tutta la Germania!", "Scadenza al 15 LUGLIO (nessun anticipo a gennaio)"],
        "punti_deboli": ["Città tranquilla per chi cerca metropoli rumorose"],
        "url": "https://www.uni-saarland.de/en"
    },
    {
        "id": "tum",
        "nome": "Technical University of Munich (TUM)",
        "citta": "Monaco di Baviera / Heilbronn",
        "paese": "Germania",
        "bandiera": "🇩🇪",
        "lat": 48.1497,
        "lng": 11.5679,
        "qs2027": 25,
        "qs2026": 28,
        "punteggio_qs": 91.8,
        "tasse_annue_eu": "~144 €/semestre (Rette universitarie 0 € per cittadini UE)",
        "affitto_mensile": "550–850 €/mese (Monaco molto cara, Heilbronn più accessibile)",
        "costo_vita_totale": "~1.050–1.450 €/mese",
        "budget_mensile_val": 1250,
        "budget_rating": 2,
        "ambiti": ["cs", "ce", "ai", "robotics", "embedded", "other_eng"],
        "lauree_triennali": [
            {
                "nome": "B.Sc. Information Engineering (100% IN INGLESE - Campus Heilbronn)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["cs", "ce", "ai", "embedded"],
                "focus": "Corso di punta erogato in inglese al campus di Heilbronn: data engineering, cybersecurity, software architecture, intelligenza artificiale."
            },
            {
                "nome": "B.Sc. Aerospace (100% IN INGLESE - Garching)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["other_eng", "robotics"],
                "focus": "Aeronautica, spazio, veicoli autonomi e sistemi di propulsione in lingua inglese."
            }
        ],
        "lingua_triennale": "Inglese (BSc Information Engineering e BSc Aerospace)",
        "has_english_bachelor": True,
        "has_italian_bachelor": False,
        "ammissione": {
            "test_richiesto": "Aptitude Assessment (Eignungsfeststellungsverfahren): valutazione voti diploma e colloquio/test online",
            "soglia_indicativa": "Voto diploma alto in matematica e fisica",
            "scadenze": "15 LUGLIO tramite TUMonline e Uni-Assist",
            "requisiti_lingua": "IELTS 6.5 o Cambridge Advanced/First",
            "procedura": "Registrazione su TUMonline, invio VPD da Uni-Assist, test di idoneità",
            "difficolta": 3
        },
        "approccio_didattico": "L'università #1 della Germania (#25 al mondo). Partner tecnologico di BMW, Siemens, Allianz, Google Munich.",
        "qualita_vita": "Baviera prospera, sicura, ordinata; a 4h di auto o treno diretto da Vicenza (Brennero).",
        "soddisfazione_studenti": "9.4/10. Titolo TUM dal valore immenso sul CV.",
        "rapporto_studio_vita": "Ritmo molto rigoroso, città ricca di opportunità.",
        "borse_sussidi": "Rette 0 € per cittadini UE. Minijob e contratti Werkstudent ben pagati (~16-20€/h).",
        "fit_score": 9.3,
        "fit_note": "#25 al mondo (top in Germania). A sole 4 ore di treno/auto da Vicenza! Il corso Information Engineering in inglese a Heilbronn ha costi di vita più accessibili rispetto al centro di Monaco.",
        "punti_forza": ["#25 al mondo (Top università tedesca)", "Rette 0 € per studenti UE", "A sole 4h di treno da Vicenza", "Reputazione globale indiscussa"],
        "punti_deboli": ["Monaco città molto cara per gli affitti", "Esami del primo anno molto selettivi"],
        "url": "https://www.tum.de"
    },
    {
        "id": "th_deggendorf",
        "nome": "Deggendorf Institute of Technology (DIT)",
        "citta": "Deggendorf",
        "paese": "Germania",
        "bandiera": "🇩🇪",
        "lat": 48.8297,
        "lng": 12.9554,
        "qs2027": 650,
        "qs2026": 650,
        "punteggio_qs": 28.0,
        "tasse_annue_eu": "0 € tasse (solo ~72 €/semestre di contributo amministrativo)",
        "affitto_mensile": "260–380 €/mese (economicità bavarese eccezionale)",
        "costo_vita_totale": "~650–850 €/mese",
        "budget_mensile_val": 750,
        "budget_rating": 5,
        "ambiti": ["ai", "cs", "robotics", "embedded", "other_eng"],
        "lauree_triennali": [
            {
                "nome": "B.Sc. Artificial Intelligence (100% IN INGLESE)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3.5 anni (210 ECTS, include semestre di stage aziendale)",
                "ambiti": ["ai", "robotics", "cs"],
                "focus": "Uno dei rari corsi di laurea applicata in Artificial Intelligence in lingua inglese in Germania. Machine learning, computer vision, data science e robotica autonoma."
            },
            {
                "nome": "B.Eng. Mechatronics / Applied Computer Science",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3.5 anni (210 ECTS)",
                "ambiti": ["embedded", "robotics", "other_eng"],
                "focus": "Sistemi embedded, microcontrollori, azionamenti meccatronici, IoT."
            }
        ],
        "lingua_triennale": "Inglese (tutti i corsi sopra sono 100% in inglese)",
        "has_english_bachelor": True,
        "has_italian_bachelor": False,
        "ammissione": {
            "test_richiesto": "Valutazione diploma e colloquio online motivazionale",
            "soglia_indicativa": "Diploma tecnico ITIS Rossi pienamente riconosciuto per le Fachhochschulen tedesche",
            "scadenze": "15 LUGLIO",
            "requisiti_lingua": "Inglese B2 certificato (il tuo Cambridge First è perfetto)",
            "procedura": "Domanda su Primuss portal / Uni-Assist",
            "difficolta": 2
        },
        "approccio_didattico": "Didattica orientata alla pratica (University of Applied Sciences / Hochschule). Molti laboratori, stage aziendale di 6 mesi pagato obbligatorio.",
        "qualita_vita": "Cittadina sul Danubio nella bassa Baviera, tranquilla, sicura, a costi bassissimi.",
        "soddisfazione_studenti": "9.1/10. Ambiente internazionale con oltre il 40% di studenti esteri.",
        "rapporto_studio_vita": "Rilassato: con 600-800€ al mese vivi da signore senza alcun debito.",
        "borse_sussidi": "Rette 0 €.",
        "fit_score": 9.4,
        "fit_note": "Perfetto per chi vuole concretezza: B.Sc. in Artificial Intelligence 100% in inglese, università applicata (moltissimi laboratori), stanze a 280-320€/mese e tirocini retribuiti nell'industria bavarese.",
        "punti_forza": ["BSc Artificial Intelligence 100% in inglese", "Costi bassissimi (affitti a 260-350€)", "Didattica estremamente pratica (laboratori e stage)", "Budget 600-800€/mese copre tutto comodamente"],
        "punti_deboli": ["Ateneo applicato meno teorico dei grandi politecnici"],
        "url": "https://www.th-deg.de/en"
    },

    # ─── AUSTRIA ────────────────────────────────────────────────────────────
    {
        "id": "jku_linz",
        "nome": "Johannes Kepler University Linz (JKU)",
        "citta": "Linz",
        "paese": "Austria",
        "bandiera": "🇦🇹",
        "lat": 48.3370,
        "lng": 14.3180,
        "qs2027": 450,
        "qs2026": 446,
        "punteggio_qs": 32.0,
        "tasse_annue_eu": "0 € tasse (solo ~22 €/semestre di contributo studenti ÖH per cittadini UE!)",
        "affitto_mensile": "300–450 €/mese (campus residenziale con alloggi studenteschi moderni a prezzi calmierati!)",
        "costo_vita_totale": "~750–950 €/mese",
        "budget_mensile_val": 850,
        "budget_rating": 5,
        "ambiti": ["ai", "cs", "robotics", "embedded", "other_eng"],
        "lauree_triennali": [
            {
                "nome": "B.Sc. Artificial Intelligence (100% IN INGLESE)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["ai", "robotics", "cs"],
                "focus": "Uno dei primi Bachelor in AI del mondo! Guidato dal prestigioso Institute for Machine Learning fondato da Sepp Hochreiter (l'inventore delle reti neurali LSTM, pietra miliare del Deep Learning)."
            },
            {
                "nome": "B.Sc. Mechatronics (English modules)",
                "lingua": "🇬🇧 Inglese / Tedesco",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["robotics", "embedded", "other_eng"],
                "focus": "Linz è la culla accademica della meccatronica in Europa. Integrazione perfetta tra meccanica, elettronica e controlli."
            }
        ],
        "lingua_triennale": "Inglese (BSc Artificial Intelligence 100% in lingua inglese)",
        "has_english_bachelor": True,
        "has_italian_bachelor": False,
        "ammissione": {
            "test_richiesto": "Ammissione aperta con verifica del diploma di scuola superiore e delle competenze matematiche",
            "soglia_indicativa": "Diploma ITIS Rossi con buon voto in matematica",
            "scadenze": "Settembre per il semestre invernale (scadenze austriache molto flessibili!)",
            "requisiti_lingua": "Inglese B2 certificato (il tuo First B2/C1 Cambridge è pienamente riconosciuto)",
            "procedura": "1. Registrazione online sul portale JKU Kusss\n2. Invio copia diploma con dichiarazione di valore o legalizzazione\n3. Immatricolazione diretta senza graduatorie numerus fixus stressanti!",
            "difficolta": 1
        },
        "approccio_didattico": "Prestigio scientifico assoluto nel deep learning (la cattedra di Hochreiter attrae partnership con Audi, Apple, Google). Campus integrato con laghetto e dormitori.",
        "qualita_vita": "Linz è una città verde, affacciata sul Danubio, a sole 4 ore e mezza di auto da Vicenza (raggiungibile anche in treno via Tarvisio/Salisburgo).",
        "soddisfazione_studenti": "9.4/10. Campus universitario vivibile e moderno.",
        "rapporto_studio_vita": "Magnifico: vicinanza all'Italia e costi bassi.",
        "borse_sussidi": "Rette universitarie 0 € per studenti UE. Minijob austriaci esentasse fino a ~518 €/mese.",
        "fit_score": 9.8,
        "fit_note": "🎯 FIT CLAMOROSO: Bachelor in Artificial Intelligence 100% IN INGLESE presso l'ateneo di Sepp Hochreiter (padre delle reti LSTM!). Rette pari a ZERO, alloggio economico sul campus, ammissione agevole e vicinissima a Vicenza (4h30 di macchina o treno)!",
        "punti_forza": ["B.Sc. Artificial Intelligence 100% in inglese", "Istituto fondato da Sepp Hochreiter (inventore LSTM e pioniere AI)", "Rette universitarie = 0 €", "Vicinanza all'Italia (4h30 da Vicenza)", "Ammissione diretta senza graduatorie rigide"],
        "punti_deboli": ["Città industriale elegante ma non metropoli globale"],
        "url": "https://www.jku.at/en"
    },

    # ─── BELGIO ─────────────────────────────────────────────────────────────
    {
        "id": "ku_leuven",
        "nome": "KU Leuven",
        "citta": "Lovanio (Leuven)",
        "paese": "Belgio",
        "bandiera": "🇧🇪",
        "lat": 50.8798,
        "lng": 4.7005,
        "qs2027": 59,
        "qs2026": 63,
        "punteggio_qs": 78.4,
        "tasse_annue_eu": "~1.116 €/anno (tariffa calmierata per studenti UE)",
        "affitto_mensile": "380–580 €/mese (residenze KU Leuven 'Kot')",
        "costo_vita_totale": "~850–1.200 €/mese",
        "budget_mensile_val": 1000,
        "budget_rating": 4,
        "ambiti": ["cs", "ce", "embedded", "robotics", "other_eng"],
        "lauree_triennali": [
            {
                "nome": "B.Sc. Engineering Technology (100% IN INGLESE - Campus Group T)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["cs", "ce", "embedded", "robotics", "other_eng"],
                "focus": "Uno dei rari corsi di ingegneria in inglese in Belgio. Indirizzi in: ICT (software, reti, embedded), Elettronica, Meccatronica, Chimica. Fortissima impronta pratica con gli 'Engineering Experiences' e team solari."
            }
        ],
        "lingua_triennale": "Inglese (BSc Engineering Technology al Campus Group T)",
        "has_english_bachelor": True,
        "has_italian_bachelor": False,
        "ammissione": {
            "test_richiesto": "Valutazione del diploma di maturità tecnica + test di posizionamento matematico (Ijkingstoets, non ostativo)",
            "soglia_indicativa": "Diploma ITIS Rossi con almeno 7/10 in Matematica",
            "scadenze": "1° MARZO (per studenti internazionali) o fino a Giugno per cittadini UE",
            "requisiti_lingua": "IELTS 6.5 o Cambridge First/Advanced",
            "procedura": "Domanda sul portale KU Leuven Admissions",
            "difficolta": 2
        },
        "approccio_didattico": "KU Leuven è stabilmente al 1° posto in Europa per tasso di innovazione secondo Reuters. Campus Group T orientato a progetti e prototipi pratici.",
        "qualita_vita": "Leuven è una perla medievale a 20 minuti di treno da Bruxelles: una delle città universitarie più storiche del mondo.",
        "soddisfazione_studenti": "9.3/10. Il tipico alloggio belga ('Kot') crea forte socialità.",
        "rapporto_studio_vita": "Molto piacevole e vivace.",
        "borse_sussidi": "Contratto studenti belga (Studentenarbeid): 600 ore all'anno esenti da imposte.",
        "fit_score": 9.4,
        "fit_note": "#59 al mondo QS (Top 10 in Europa). Il Bachelor in Engineering Technology in inglese al Campus Group T unisce la teoria alla costruzione di prototipi (team studenteschi pluripremiati). Tasse basse (1.116€/anno).",
        "punti_forza": ["#59 al mondo QS", "Triennale Engineering Technology 100% in inglese", "Tasse basse (~1.116 €/anno)", "A 20 minuti di treno da Bruxelles", "Regime di lavoro studentesco esentasse"],
        "punti_deboli": ["Scadenza consigliata entro Marzo"],
        "url": "https://www.kuleuven.be/english"
    },
    {
        "id": "howest",
        "nome": "Howest University of Applied Sciences",
        "citta": "Kortrijk",
        "paese": "Belgio",
        "bandiera": "🇧🇪",
        "lat": 50.8280,
        "lng": 3.2649,
        "qs2027": 700,
        "qs2026": 700,
        "punteggio_qs": 26.0,
        "tasse_annue_eu": "~1.116 €/anno",
        "affitto_mensile": "320–480 €/mese",
        "costo_vita_totale": "~750–950 €/mese",
        "budget_mensile_val": 850,
        "budget_rating": 5,
        "ambiti": ["gamedev", "cs", "cyber"],
        "lauree_triennali": [
            {
                "nome": "B.Sc. Digital Arts and Entertainment (DAE) - (100% IN INGLESE)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["gamedev", "cs"],
                "focus": "Votata per 3 volte MIGLIORE SCUOLA DI VIDEOGIOCHI DEL MONDO (Rookies Awards)! Specializzazioni in Game Development (C++, motori grafici, fisica, Unity/Unreal Engine) e Game Graphics 3D."
            },
            {
                "nome": "B.Sc. Applied Computer Science: Cyber Security Professional",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "3 anni (180 ECTS)",
                "ambiti": ["cyber", "cs"],
                "focus": "Penetration testing, reverse engineering, sicurezza delle reti e malware analysis."
            }
        ],
        "lingua_triennale": "Inglese (tutti i corsi sopra sono 100% in inglese)",
        "has_english_bachelor": True,
        "has_italian_bachelor": False,
        "ammissione": {
            "test_richiesto": "Valutazione diploma e test di attitudine alla programmazione/matematica",
            "soglia_indicativa": "Forte passione e basi matematiche",
            "scadenze": "15 Giugno",
            "requisiti_lingua": "Inglese B2",
            "procedura": "Domanda online sul portale Howest DAE",
            "difficolta": 2
        },
        "approccio_didattico": "Il tempio mondiale per programmatori di videogiochi e computer graphics: 100% pratico, hardware con GPU top di gamma, docenti dall'industria tripla-A (Ubisoft, EA, Guerrilla).",
        "qualita_vita": "Cittadina fiamminga moderna e tranquilla, a costi molto contenuti.",
        "soddisfazione_studenti": "9.5/10. I laureati DAE lavorano nei principali studi di sviluppo del mondo.",
        "rapporto_studio_vita": "Impegnativo ma appassionante se adori Unity, C++ e computer graphics.",
        "borse_sussidi": "Tasse calmierate a ~1.116 €/anno.",
        "fit_score": 9.5,
        "fit_note": "Se vuoi fare Game Development, motori grafici o simulazioni avanzate (come il tuo simulatore Unity per la RoboCup), DAE Howest è considerata letteralmente la n.1 al mondo per distacco, con tasse a soli 1.116€/anno!",
        "punti_forza": ["Scuola n.1 al mondo per Game Development (Rookies Award)", "Insegnamento avanzatissimo di C++, shader, motori grafici e simulazione", "Tasse belghe basse (~1.116 €/anno)", "Assunzione diretta in studi di sviluppo tripla-A"],
        "punti_deboli": ["Carico di lavoro nei progetti molto intenso"],
        "url": "https://www.digitalartsandentertainment.be"
    },

    # ─── IRLANDA ────────────────────────────────────────────────────────────
    {
        "id": "tcd",
        "nome": "Trinity College Dublin",
        "citta": "Dublino",
        "paese": "Irlanda",
        "bandiera": "🇮🇪",
        "lat": 53.3438,
        "lng": -6.2546,
        "qs2027": 75,
        "qs2026": 81,
        "punteggio_qs": 71.5,
        "tasse_annue_eu": "~3.000 €/anno (contributo studentesco EU sotto Free Fees Initiative)",
        "affitto_mensile": "750–1.150 €/mese (Dublino ha una crisi abitativa seria)",
        "costo_vita_totale": "~1.350–1.850 €/mese",
        "budget_mensile_val": 1500,
        "budget_rating": 1,
        "ambiti": ["cs", "ce", "ai", "other_eng"],
        "lauree_triennali": [
            {
                "nome": "B.A. (Mod) Computer Science (100% IN INGLESE)",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "4 anni (BSc Honours irlandese, opzione master integrato a 5 anni)",
                "ambiti": ["cs", "ai", "ce"],
                "focus": "Algoritmi, intelligenza artificiale, architettura dei calcolatori, sistemi operativi e telecomunicazioni."
            }
        ],
        "lingua_triennale": "Inglese",
        "has_english_bachelor": True,
        "has_italian_bachelor": False,
        "ammissione": {
            "test_richiesto": "CAO (Central Applications Office) irlandese: conversione dei voti di maturità in punti CAO",
            "soglia_indicativa": "Voto di maturità molto alto (≥ 90/100)",
            "scadenze": "1° FEBBRAIO (tramite CAO.ie)",
            "requisiti_lingua": "Inglese madrelingua / Cambridge Advanced C1 o First con grade A / IELTS 6.5",
            "procedura": "Domanda su cao.ie entro il 1° febbraio allegando transcript voti",
            "difficolta": 4
        },
        "approccio_didattico": "L'ateneo storico più prestigioso d'Irlanda. Campus iconico nel centro di Dublino, accanto ai quartier generali europei di Google, Meta, Twitter/X.",
        "qualita_vita": "Dublino è accogliente e giovanile (Giovanni ci ha già vissuto per il PCTO a Clondalkin e centro città).",
        "soddisfazione_studenti": "9.1/10.",
        "rapporto_studio_vita": "Città vivace, ma il costo dell'alloggio a Dublino è il più alto dell'UE dopo Zurigo.",
        "borse_sussidi": "Lavoro part-time a 12,70 €/ora minimo legale.",
        "fit_score": 8.0,
        "fit_note": "Ateneo leggendario (#75 al mondo) in un Paese che conosci già bene. Purtroppo gli affitti a Dublino sono alle stelle (800-1.100€ solo per la stanza), rendendola difficile con un budget di 600-800€ senza lavorare molte ore.",
        "punti_forza": ["#75 al mondo QS", "Conosci già Dublino dall'Erasmus PCTO", "Silicon Docks con quartier generali tech europei"],
        "punti_deboli": ["Affitti proibitivi a Dublino", "Corso di durata quadriennale (4 anni)"],
        "url": "https://www.tcd.ie"
    },
    {
        "id": "galway",
        "nome": "University of Galway",
        "citta": "Galway",
        "paese": "Irlanda",
        "bandiera": "🇮🇪",
        "lat": 53.2778,
        "lng": -9.0600,
        "qs2027": 289,
        "qs2026": 289,
        "punteggio_qs": 39.5,
        "tasse_annue_eu": "~3.000 €/anno (contributo studentesco EU)",
        "affitto_mensile": "450–700 €/mese (molto più accessibile di Dublino!)",
        "costo_vita_totale": "~950–1.250 €/mese",
        "budget_mensile_val": 1100,
        "budget_rating": 3,
        "ambiti": ["cs", "ai", "other_eng"],
        "lauree_triennali": [
            {
                "nome": "B.Sc. Computer Science and Information Technology",
                "lingua": "🇬🇧 Inglese",
                "lingua_code": "en",
                "durata": "4 anni",
                "ambiti": ["cs", "ai"],
                "focus": "Forte polo per l'intelligenza artificiale e data science (ospita l'Insight Centre for Data Analytics)."
            }
        ],
        "lingua_triennale": "Inglese",
        "has_english_bachelor": True,
        "has_italian_bachelor": False,
        "ammissione": {
            "test_richiesto": "CAO.ie",
            "soglia_indicativa": "Punti CAO basati sul diploma",
            "scadenze": "1° Febbraio",
            "requisiti_lingua": "IELTS 6.5 o Cambridge",
            "procedura": "Domanda tramite portale CAO",
            "difficolta": 3
        },
        "approccio_didattico": "Didattica orientata al software e alle tecnologie mediche/data science.",
        "qualita_vita": "Galway è la capitale culturale e musicale d'Irlanda, affacciata sull'Atlantico, sicura e accogliente.",
        "soddisfazione_studenti": "9.2/10.",
        "rapporto_studio_vita": "Molto più vivibile e rilassante rispetto a Dublino.",
        "borse_sussidi": "Part-time a 12,70 €/ora.",
        "fit_score": 8.6,
        "fit_note": "Se vuoi studiare in Irlanda evitando i prezzi folli di Dublino, Galway è la scelta migliore: alloggi più accessibili, Insight Centre per il Machine Learning e vita studentesca festosa.",
        "punti_forza": ["Costi abitativi molto più bassi di Dublino", "Insight Centre for Data Analytics", "Capitale culturale d'Irlanda"],
        "punti_deboli": ["Durata quadriennale"],
        "url": "https://www.universityofgalway.ie"
    }
]
